### ISSUE TITLE
Error: Undefined array key "type_descriptions" in TSML UI shortcode

### ISSUE THREAD

**Issue by Studio88-KM** [code4recovery/12-step-meeting-list#1006]
Hey Josh, we were getting this error on the staging site in the error logs. Any chance you can advise or fix this? 

[Tue Dec 20 21:10:20.558117 2022] [proxy_fcgi:error] [pid 752:tid 139728732956416] [client 207.38.232.65:0] AH01071: Got error 'PHP message: PHP Warning: Undefined array key "type_descriptions" in /home/772911.cloudwaysapps.com/cmxfhtnqsb/public_html/wp-content/plugins/12-step-meeting-list/includes/shortcodes.php on line 122', referer: https://danyc.org/index.php/meetings/

We just went live with the site: http://danyc.org/

**Comment by joshreisner** [comment]
Hi @Studio88-KM moving this to TSML, we need a PHP fix. Not a big deal, just a warning, but we should fix it. Thanks

> Undefined array key "type_descriptions" in shortcodes.php on line 122

**Comment by Studio88-KM** [comment]
Great, thank you!

**Comment by petermixt** [comment]
Had this issue also. Thank Josh. Regions and districts not accessible. Pds
