### ISSUE TITLE
Can't edit Regions or Districts

### ISSUE THREAD

**Issue by MinnesotaSwanny** [code4recovery/12-step-meeting-list#1016]
Hi hi!  SCI is running Version 3.14.8 of the 12 Step Meeting List and we are receiving the following error when we try to edit Districts and Regions in the plug-in:  Sorry, you are not allowed to edit terms in this taxonomy.

Please advise. Thank you!  -Alan

**Comment by joshreisner** [comment]
looks like this is a side effect of our fix for #962 - we'll fix it!

**Comment by MinnesotaSwanny** [comment]
Hi Josh,

Sounds good!  Please let me know when there is a fix to download. 🙂

In Service,

Alan
________________________________

**Comment by joshreisner** [comment]
ok `3.14.9` should be on its way out now. please let us know if it doesn't fix the issue

**Comment by MinnesotaSwanny** [comment]
Hi Josh!

Good News:  I can now add/edit/remove Districts and Regions.
Bad News:  Some of the AA meetings I load from my load spreadsheet are showing up as "Undefined" time in a search return and in the detail of the listing, show up as "Appointment".  Help!

Example:  https://aasaintcloud.org/meetings/waite-park-thursday-night-group/?tsml-day=any&tsml-region=waite-park

Thanks!

Alan
[https://aasaintcloud.org/wp-content/uploads/2022/01/skier-1297083_1280-2.png]<https://aasaintcloud.org/meetings/waite-park-thursday-night-group/?tsml-day=any&tsml-region=waite-park>
Waite Park Thursday Night Group - St. Cloud Intergroup<https://aasaintcloud.org/meetings/waite-park-thursday-night-group/?tsml-day=any&tsml-region=waite-park>
aasaintcloud.org

________________________________

**Comment by MinnesotaSwanny** [comment]
Hi Again Josh,

I think I fixed it when I updated my Google Maps API in my Maps module/plug-in in Word Press.  Its working now.

Thanks!

-A
________________________________

**Comment by MinnesotaSwanny** [comment]
Hi Again.  This is back to not working.  I am using an unrestricted Google Maps API, no luck.  Can you take a look?  Search for meetings in "St. Cloud" or "Waite Park":  https://aasaintcloud.org/meetings/
[https://aasaintcloud.org/wp-content/uploads/2022/01/skier-1297083_1280-2.png]<https://aasaintcloud.org/meetings/>
Meetings Archive - St. Cloud Intergroup<https://aasaintcloud.org/meetings/>
106 7th Ave N: Waite Park: Closed, Digital Basket, Discussion, English, Online Meeting, Wheelchair Access: 7:00 pm : Saturday Night A.A. Group
aasaintcloud.org


Thanks - Alan
________________________________

**Comment by joshreisner** [comment]
Hi Alan, this sounds like a separate issue, and probably not API-related. If you are importing these meetings and they show up as Appointment then my guess is there is something unusual about the day or the time in your spreadsheet (for the affected meetings only).
