### ISSUE TITLE
Online Meeting type not getting set when importing from JSON

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#102]
**Describe the bug**
When importing meetings that have conference_url and/or conference_phone via JSON, the Online Meeting type does not get set. Everything else works fine.

**To Reproduce**
Import from a JSON feed that has online meetings. Eg https://www.aasf.co/apps/dbmanager/c360_meeting_json.cfm

**Expected behavior**
The Online Meeting tag should be applied for those meetings.

**Comment by tech2serve** [comment]
Thank you! I had picked up on this a couple of days ago, and had plans to work on it today.
