### ISSUE TITLE
Split Import & Settings

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1028]
### Requested Feature/Enhancment

Getting to the Settings tab takes more effort than it needs to. It should be `Meetings > Settings`, not `Meetings > Import & Settings > Settings` - I find that I'm always giving this instruction to others and wish it was simpler!

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by tim-rohrer** [comment]
Yes, I think it would make it easier if this changed. Splitting into two (or three?) options would simplify this.

Would changing the top level "Import & Settings" to "Configuration"  (or something similar) clarify the paths?

**Comment by joshreisner** [comment]
I'm thinking two different menu items, `Import & Export` and `Settings`

**Comment by joshreisner** [comment]
![import-export](https://user-images.githubusercontent.com/1551689/210151501-19e01a14-b61c-4371-ac30-2e3e00810798.png)

![settings](https://user-images.githubusercontent.com/1551689/210151504-ab9f12ff-a7fb-4129-b63e-7359bded90a5.png)
