### ISSUE TITLE
Meeting distance location variable not interpolated {{location}}

### ISSUE THREAD

**Issue by mrlynn** [code4recovery/12-step-meeting-list#103]
**Describe the bug**
Detail pane for meeting shows distance with  uninterpolated variable and error message string. e.g. `1.07 mi from [missing {{location}}]`

**To Reproduce**
1. Open Meeting Guide
2. Search for meeting near you. 
3. Tap on meeting for details. 
4. Notice the distance indication section (middle) of the display. Displays distance from [missing {{location}}]

**Expected behavior**
[missing {{location}}] should not be displayed - it should be a location or an error message indicating the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/192552/79075097-9b56aa00-7cbe-11ea-8323-6e2b5288054c.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Any
 - Version

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment]
Thank you for a substantively more complete bug report. Regrettably, this is the wrong place to file it :-) We only do `12 Step Meeting List` bug reports here so I'm going to close this.

I can tell you that the Meeting Guide dev team *is* aware of this bug though, and I believe has already addressed it for the next release. 

For future Meeting Guide bug reports, please use this [contact form](https://meetingguide.aa.org/contact).

Thanks.

**Comment by joshreisner** [comment]
Thanks @mrlynn this'll be fixed in `3.3.4`, in beta already.
