### ISSUE TITLE
Adding More Conference Providers

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#105]
Due to popular demand, I would like to add more providers to the default conference providers array. Here are the new array values that the MG app supports:

		'bluejeans.com' => 'BlueJeans',
		'freeconferencecall.com' => 'FreeConferenceCall',
		'meet.google.com' => 'Google Hangouts',
		'gotomeet.me' => 'GoToMeeting',
		'gotomeeting.com' => 'GoToMeeting',
		'skype.com' => 'Skype',
		'webex.com' => 'WebEx',
		'zoho.com' => 'Zoho',
		'zoom.us' => 'Zoom',	

Open to adding more as needed.

**Comment by tech2serve** [comment]
TSML currently has:

        'meet.google.com' => 'Google Hangouts',
	'gotomeeting.com' => 'GoToMeeting',
	'skype.com' => 'Skype',
	'webex.com' => 'WebEx',
	'zoom.us' => 'Zoom',
	'freeconference.com' => 'Free Conference',
	'freeconferencecall.com' => 'FreeConferenceCall'

I'll add `bluejeans.com`, `gotomeet.me` and `zoho.com`

MG might consider `freeconference.com` .

**Comment by joshreisner** [comment]
Ok sure I'll add freeconference.com. Trying to stay in sync
