### ISSUE TITLE
Feeds import puts 12x12 meetings in notes

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1073]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/1071

<div type='discussions-op-text'>

<sup>Originally posted by **anchovie91471** February  9, 2023</sup>
### Contact Details

anthony@bustedspring.com

### What happened?

First, thanks for the amazing plugin and all the hard work you have put in for the recovery community!! I used the plugin on several sites for districts & our area. It's a huge help!

I identified a bug today in the latest version:

When importing meetings from a JSON feed. The 12x12 meeting type gets imported into the Meeting Notes field instead of the meeting types array.

This appears to be due to a failing if statement on line 1521 of includes/functions.php.
`if (array_key_exists($upper_type, $upper_types))`

The key for all 12x12 meetings in the variables.php file is set to "12x12" (lowercase x) instead of "12X12" so it fails this test and gets put in the notes field.

I sent an email a week or two ago to info@code4recovery.org asking for info regarding how best to do pull requests but didn't hear back. I'd be happy to do the PR and fix if that's helpful.

### Relevant log output/errors

_No response_</div>

**Comment by 97eighty** [comment]
Is there a source JSON feed to test with?

**Comment by joshreisner** [comment]
sure here's one: https://sheets.code4recovery.org/storage/12KfpoNcLP4YqRsiN_jakbaxkF-ZQpcqTncISQ5Fr0e4.json

if i import it to our test site: https://code4recovery.org/meetings/odaat-2
