### ISSUE TITLE
Import Data Sources Redesign with Change Detection

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#1075]
### Contact Details

@kiyote33

### Requested Feature/Enhancement

Improve the Import Data Sources feature, allowing local admins to apply only the changes detected between an import feed and the local database. The current method which does a complete removal and re-entry of all feed records would no longer be necessary when refreshing. This proposed modification will not affect the existing methods of removing a data source's entire set of records from the local database. The option to enable Change Detection email reports will remain the same by including at least 1 Change Notification email recipient address on the Settings page. 

Dev Notes:
1. Change detection for Data Sources Import feeds needs to be more robust then jus relying on the "updated" field, as it may not be available on all imports. Instead, we will use a database matching record comparison to determine import update candidate records which are new, changed, or removed from the import. This type of differential updating would avoid the necessity of requiring certain fields (i.e. updated) to be present and accurate in the import feed records.
2. Each Data Sources Import feed is registered in the database with its feed URL ($data_source_url) appended to the import record in the database data_source field. This supports the updating and removal of those records in future operations. 
3. The Data Source Name field currently allows admins to name their feed import whatever they want. 
4. The current Import CSV feature will remain unchanged.
5. A debug feature will be included to give admins and developers the ability to see what changes have been detected and applied by the refresh operation. [$tsml_debug = true;]
6. The only perceivable change to the user interface for this feature will be minimal changes to the Import Data Sources text content describing high-level use of the feature.

**Comment by joshreisner** [comment]
i’m all for making the update more efficient. why should we keep the old way as an option? would there be a different outcome between the two methods?

**Comment by foundartfactory** [comment]
FWIW, I am all for this requested feature! I could maybe see wanting to be able to one-off refresh the database w/the entire feed contents -- but if that went away, I would miss it less than I would appreciate the new incremental feature.

**Comment by joshreisner** [comment]
again, im not clear what the benefit of having two methods would be. wouldnt the end result be exactly the same?

having two methods implies that we think the new way isnt 100% reliable, which should not be the case if we are comfortable shipping it

**Comment by kiyote33** [comment]
@joshreisner - I agree. The refresh process will always be there if the feed is dropped and then recreated. We wouldn't need to change that code (other than to change what code executes when the button is pressed). Much cleaner to modify the button text from "Refresh" to "Update" and have the button execute the new code to update the detected changes only.

I'm assuming you are not suggesting that we should prevent the ability to drop the feed, or is that something you think we should do?

**Comment by joshreisner** [comment]
no, of course, people need to be able to remove and add feeds. but when you write:

> The refresh process will always be there if the feed is dropped and then recreated

this suggests there is a difference, so perhaps i am still missing something. is there a different outcome when you delete and re-add the feed vs if you click the new "update" button?

does change detection need to be enabled?

**Comment by joshreisner** [comment]
ok thanks 👍 - just remember you sometimes will need to do geocodes

**Comment by kiyote33** [comment]
Yep! When address changes happen...

**Comment by kiyote33** [comment]
Closed with the release of version 3.15

**Comment by intuitivecat** [comment]
I love this contribution, but now the email lists almost every meeting as changed daily.   If I could just schedule the sync I would, then I wouldn't even care about the email.

**Comment by joshreisner** [comment]
we ran into this issue with another site - my guess is the feed you are importing from is not TSML - perhaps it is a Google Sheet or a custom database?

**Comment by intuitivecat** [comment]
Thanks, I'll see if I can see a pattern.  it is not all the meetings, just most of them.  They for sure are TSML,  here are the root domains 

- https://refugerecoverymeetings.org/ - definitely on an old version
- https://recoverydharma.org/ - maybe they don't have this latest update yet, I did deleter and re-add this one after the fix.
