### ISSUE TITLE
Add support for "regions" array when importing

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1079]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/1078

<div type='discussions-op-text'>

<sup>Originally posted by **fritzisa** February 15, 2023</sup>
**Dear friends,**

The REGION isn't the same when viewed from two different sites.

When filtering for the meeting Morton, the REGION is different on SEPIA website (1) than Area 59 website (2)

(1) https://aasepia.org/?search=morton

(2) https://area59aa.org/find-a-meeting/?search=morton

Area 59 uses the feed provided by SEPIA.

?? Is there a reason for this inconsistency ??

Thank you in advance.

**Scott Fritzinger**  |  Area 59 Web Servant  |  (610) 762-7792

![Morton-SEPIA](https://user-images.githubusercontent.com/95769327/219121834-30c5bf58-7586-4e0a-8369-33e2d6f78036.jpg)

![Morton-A59](https://user-images.githubusercontent.com/95769327/219121864-74fea18c-c64a-47d7-8201-deb6ec51747d.jpg)

</div>

**Comment by kiyote33** [comment]
Region array is now supported in version 3.15.
