### ISSUE TITLE
Don't show addresses for TC meetings in list

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#109]
My intergroup would prefer if meetings that are temporarily closed had their addresses and regions struck through (In addition to being grayed out), to be consistent with the visual treatment of the addresses on the inside page.

**Comment by FlipperPA** [comment]
@joshreisner Just to clarify on this one, that would be for temporarily closed meetings that don't have an online option? I'd like to match functionality on the Django side so we're consistent. Thanks!

**Comment by joshreisner** [comment]
Hey @FlipperPA the puts a gray background on meetings that are both TC and with no meeting option, but that's not what this request is, this is simply to strike through and mute the color on the TC addresses themselves.

**Comment by joshreisner** [comment]
Looks like your site isn't using the `Location Temporarily Closed` and `Online Meeting` types, so that would be another way to get some parity

**Comment by FlipperPA** [comment]
@joshreisner We're using them behind the scenes on the admin side, but had started using "SUSPENDED" before TSML had standardized the language. Our tech committee for SEPIA is meeting on Wednesday, and I'm hoping to have the clearance to standardize our language with TSML after that. We hadn't wanted to change the language in months past with all the recent change, but the timing feels right now, and we're inconsistent with Meeting Guide, which is never good. I've got most of the code ready, just need group conscience. Thanks amig0!

**Comment by FlipperPA** [comment]
This is the hack I've got in place that I'd like to remove:

https://github.com/code4recovery/wagtail-meeting-guide/blob/main/meeting_guide/views.py#L188

💯

**Comment by ebart455987** [comment]
Can we get the Temporarily Closed Locations on the desktop webpage Crossed Out, along with greyed out?  This would be consistent with the Mobile App.

**Comment by joshreisner** [comment]
I would like to amend the request, so I'm going to edit the name of the ticket as well. I think addresses for meetings that are TC should be hidden on the meeting list instead of being crossed out. 

It's good to keep them visible (and crossed out) on the inside page as they currently are.

**Comment by joshreisner** [comment]
this is looking good in `bw/attendance` -- closing request
