### ISSUE TITLE
[Bug]: Undefined index error in Upcoming Meetings widget

### ISSUE THREAD

**Issue by christopherokc** [code4recovery/12-step-meeting-list#1111]
### Contact Details

chrisokc@me.com

### Website With Issue

https://okcintergroup.org

### What happened?

When the Upcoming Meetings widget is added to any page and a meeting listed in the widget does not have a location set, then the follow error is displayed:

Notice: Undefined index: location in /home/toiz58k7yx2b/public_html/wp-content/plugins/12-step-meeting-list/includes/shortcodes.php on line 40

<img width="1493" alt="Screenshot 2023-04-05 at 9 48 32 AM" src="https://user-images.githubusercontent.com/9951620/230119632-fd50b637-da2b-49cb-bd3c-7f4b7cc6a0fb.png">

Workaround: Add location to the meeting 

### What browsers are you seeing the problem on?

Safari

### Relevant log output/errors

```shell
Notice: Undefined index: location in /home/toiz58k7yx2b/public_html/wp-content/plugins/12-step-meeting-list/includes/shortcodes.php on line 40
```

**Comment by christopherokc** [comment]
Oh right! Thanks!

**Comment by joshreisner** [comment]
this issue is also fixed by https://github.com/code4recovery/12-step-meeting-list/pull/1306
