### ISSUE TITLE
Include Meeting/group ID in "request change to this listing" default email

### ISSUE THREAD

**Issue by OSAwebsite** [code4recovery/12-step-meeting-list#112]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OSAwebsite** [comment]
Many in my membership use the quick comment email ("Request a change to this listing") to communicated changes in the COVID crisis. This is a fantastic tool to do so. I am wondering if it would be possible to include, in the email it auto-generates, the ID of the listing.
I am using the plugin for an Al-Anon Area site. There is currently no field/entry box for the WSO ID (AA equivalent: GSO ID) a.k.a. the group ID so I have this information in the meeting details.

My request is this:
can we either create an entry box for this ID and show it in this 'Request a change' email, or, alternatively, can we include the meeting information in this email? Both will do me fine.

A new entry box is probably going to be more work than including the meeting details.

Thanks,
Nicky

**Comment by kiyote33** [comment]
The meeting id is stored in a hidden field and can be accessed by the SendEmail portion of via $_POST['meeting_id'] in the tsml_ajax_feedback function. Simple item to add to "Enhance the 'Request a Change to this Listing' feature".

**Comment by kiyote33** [comment]
This feature is now included in our newly released 12 Step Meeting List Feedback Enhancement, available in the WP Plugin directory.

**Comment by OSAwebsite** [comment]
Uhm... it sounds great but I have never used this. Is there a tutorial on how to do this or can you clarify, please?

**Comment by OSAwebsite** [comment]
I am not a Wordpress or PHP developer so what you are saying is abacadabra to me, but it sounds like magic and I would like to learn :)

tsml_ajax_feedback function: where can I find this?
$_POST['meeting_id']: how to I use this?
"Enhance the 'Request a Change to this Listing' feature": where is this?

Where do I enter the meeting ID in the back-end?

**Comment by OSAwebsite** [comment]
I am on version Version 3.12, and there is no update available at this time. Am I missing something? It sounds like the latest version has exposed the hidden field so that I can enter it? And if so, is it also part of the import sheet? Or will it be?

**Comment by kiyote33** [comment]
Hi OSAwebsite, the unique meeting id associated with each meeting record is generated by your website software.  The "12 Step Meeting List Feedback Enhancement" is an add-on plugin which your webmaster can install from the WordPress Plugin directory. That plugin generates an email which will contain the Meeting Id of the meeting in question. Ask your webmaster to install that plugin if you want to try it out.  More information (including screenshots) can be found on the plugin home page at : https://wordpress.org/plugins/12-step-meeting-list-feedback-enhancement

**Comment by OSAwebsite** [comment]
Hi there,
I installed the plugin '12 Step Meeting List Feedback Enhancement' and
activated it but I cannot find any information about how to implement
changes. Can you help?
Thanks!
Nicky


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by tech2serve** [comment]
@kiyote33

**Comment by kiyote33** [comment]
Somehow the last couple comments slipped under my radar. I'm just seeing this today. @OSAwebsite is this still an issue for you?
The 12 Step Meeting List Feedback Enhancement plugin simply replaces the meeting detail page feedback functionality built into the legacy 12 Step Meeting List plugin.  Both feedback mechanisms are activated by adding at least one email address in the 'User Feedback Emails' textbox on the Meetings/Import & Settings page. Both feedback mechanisms manage communicating an email message between the website user and the website admin email account listed in the above noted "User Feedback Emails".  The generated email is a request from an end user to the website admin, suggesting a modification of meeting information available on the website. Changes are implemented in the usual fashion by the website admin, who normally would validate the data before implementing the requested change.

Hope this helps clarify this issue.

**Comment by kiyote33** [comment]
The "Notes" field can be used to convey external system information (like GSO's meeting ID) that is not part of or used by the 12 Step Meeting List utility.  As the Feedback Enhancement plugin and above comments now satisfy this issue ('Include Meeting/group ID in "request change to this listing" default email'), we should close this issue.  It can be reopened in the future if more clarification is required.

**Comment by OSAwebsite** [comment]
Hi,

I don't use that additional plugin for the request a change because the
power of the original feature is how simple it is.
So I have taken your suggestions and have now included the group ID within
Al-Anon in the notes section. Which means I see it whenever an email comes
in through this functionality.
With what I read about how the GSO ID is not unique within AA, I can see
that there is no interest in adding and ID field for non AA-users of the
plugin. My adjustments works well, so I am good with how things are right
now. Thanks for following up.


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*
