### ISSUE TITLE
[Bug]: Urgent! PLEASE HELP! After website move getting 404 error message on meeting list URL and meeting list not displaying

### ISSUE THREAD

**Issue by JoeBryan7873** [code4recovery/12-step-meeting-list#1138]
### Contact Details

joebryanmarketing@gmail.com

### Website With Issue

https://capecodaa.net/meetings/

### What happened?

Hi,

I am having an urgent issue. We just update dour website an after moving from a development server the 12 step meeting list plugin is not working.

I uninstalled and reinstalled the plugin and re-imported the meeting data I'm getting a 404 error for the meeting list URL
https://capecodaa.net/meetings/

I really need this fixed quickly
Please help!

### What browsers are you seeing the problem on?

Chrome

**Comment by joshreisner** [comment]
since there's [already a discussion for this](https://github.com/code4recovery/12-step-meeting-list/discussions/1137#discussioncomment-5930197) going to close the issue
