### ISSUE TITLE
[Feature Request]: Expand TSML Search Criteria to include more fields...

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#1141]
### Contact Details

Wayne

### Requested Feature/Enhancement

See Discussion item Scrolling not working #1140 from @hawswebmaster. Would like search criteria fields expanded so the returned resultset includes meetings whose region or district are being querried.

here is where we define the "searchable keys": [https://github.com/code4recovery/12-step-meeting-list/blob/main/includes/filter_meetings.php](https://github.com/code4recovery/12-step-meeting-list/blob/main/includes/filter_meetings.php#L61)
            $this->searchable_keys = ['name', 'notes', 'location', 'location_notes', 'formatted_address', 'group', 'group_notes'];

**Comment by hawswebmaster** [comment]
Well, it is working but for some reason, 4 meetings from orange county california come up for every search. Search Texas, and they come up, search Indiana, and those 4 come up. Not sure what's up with that...

**Comment by hawswebmaster** [comment]
Did not work
