### ISSUE TITLE
Option to open online meeting link in new tab

### ISSUE THREAD

**Issue by Trundlore** [code4recovery/12-step-meeting-list#115]
Hi, simply we have been asked by users of the site whether it would be possible to have the online meeting link to open in a new tab so that they are easily able to return to the meeting information page. Many members are not familiar with computer use so middle-clicking or ctril+click is not something they are likely to consider or know to do.

It might be helpful for this to be a toggle on/off option for those that don't find this useful.

Thanks

Pete

**Comment by tim-rohrer** [comment]
Hi Pete. We should be able to make this change without too much difficulty. Probably won't make it a configurable option, so hopefully more people will like the approach.

**Comment by tech2serve** [comment]
Thanks. We should be able to make the change. Hopefully most people will like that.

Probably won't make it configurable as that complicates the UI.

**Comment by Grateful-Viv** [comment]
This should easily be solved by adding target = “blank”. Hopefully it’s as simple as that.

**Comment by GCITechSC** [comment]
Just curious if this is still in development.
