### ISSUE TITLE
Feature Request:  show meeting phone number on meeting details page 

### ISSUE THREAD

**Issue by CheriJones** [code4recovery/12-step-meeting-list#1159]
### Contact Details

cherijones@cyberservices.com

### Requested Feature/Enhancement

when looking at meeting details on a computer the phone number doesn't show unless you mouse over the group phone button and then it only pops up in the lower left corner away from where the button is - and there really isn't any reason to mouse over the button since computers don't make phone calls - 
if a meeting has a phone number can it be displayed under the address so someone accessing the list from a computer will see it

![image](https://github.com/code4recovery/12-step-meeting-list/assets/88801930/40d8619e-45b1-4be5-aec2-1e2dbaa220df)

**Comment by joshreisner** [comment]
we should address this how TSML UI does, by displaying the phone number inside the button label

![Screenshot 2023-07-02 at 2 23 29 PM](https://github.com/code4recovery/12-step-meeting-list/assets/1551689/dd40ab5d-8064-4525-a37a-7ab48558141e)

also the email address should be in its button label, and we should strip `www.` from the website button label

**Comment by CheriJones** [comment]
looks good - and i like the others especially since mailto doesn't work with 3rd party mail apps
