### ISSUE TITLE
[Bug]: Localization issues with Russian language

### ISSUE THREAD

**Issue by al-bal** [code4recovery/12-step-meeting-list#1180]
### Website With Issue

https://russianspeakingaa.org/meetings/russian-group-online/?tsml-day=any&tsml-attendance_option=online

### What happened?

**Bug Report**
**Title**: Localization issues with Russian language

**Description**:

1. Issue: Incorrect translation and formatting for meeting time, day of the week is not capitalized “Tuesday, 8:00 pm to 9:30 pm”.

Current: вторник, 8:00 pmк9:30 pm
Suggestion:
- Вторник, с 8:00 pm до 9:30 pm
- Or: Вторник, 8:00 pm - 9:30 pm

2. Issue: Incorrect declension with numerals “6 other meetings at this location”.

Current: 6 другие собрания в этом месте
Suggestion:
- 6 других собраний в этом месте
Notes:
- 1 другое собрание
- 2 другие собрания
- 3 другие собрания
Alternative: 
- Других собраний в этом месте: 6 (Correct for any numbers)

![image](https://github.com/code4recovery/12-step-meeting-list/assets/104799022/7bbce47c-5edb-465f-a755-5e7fb808bd9f)

3. Issue: Capitalization error in “Japanese”.
Current: японский
Suggestion: 
- Японский

4. Issue: Incorrect translation of the medical term “Dual Diagnosis”.
Current: Двойная диагностика
Suggestion: 
- Двойной диагноз

![image](https://github.com/code4recovery/12-step-meeting-list/assets/104799022/3ead0d6d-7c12-45c9-b7cb-f7fff08b5d36)

5. Issue: Incorrect translation for the time of the day “Midday”.
Current: Полдник
Suggestion:
- Полдень
- Or: Середина дня

![image](https://github.com/code4recovery/12-step-meeting-list/assets/104799022/a2edcdb0-f4e5-4e29-aeac-7d94b3860b5f)

6. Issue: Word "Active" remains untranslated.
Current: Active
Suggestion:
- Действующий
- Or: Активный

7. Issue: Questionable translation for “In-person”.
Current: Лично
Suggestion:
- Живые (colloquially more common)
- Or: Живые собрания

![image](https://github.com/code4recovery/12-step-meeting-list/assets/104799022/2fb3670a-7352-4577-8a61-9aededd7ac09)

8. Issue: Incorrect capitalization in days of the week.
Current: понедельник, вторник, среда, ...
Suggestion:
- Понедельник, 
- Вторник
- Среда
- ...

![image](https://github.com/code4recovery/12-step-meeting-list/assets/104799022/1deb3d45-0cdc-425d-b8a3-b945a917a7e6)

**Comment by anchovie91471** [comment]
We do not provide translations within the main plugin code. Is it possible you got the translated strings from https://translate.wordpress.org/locale/ru/default/wp-plugins/12-step-meeting-list/? If so, we recommend you report the issue there or possibly contribute the changes you need.

If you are interested in switching to TSML UI (our new interface), we'd love to have you submit a translate of this file: https://github.com/code4recovery/tsml-ui/blob/main/src/i18n/en.ts

**Comment by joshreisner** [comment]
closing this issue since we don't have capacity internally to register as a plugin translator. 

we'd love it if @al-bal or any knowledgeable Russian-speaker were to register and make these changes at https://translate.wordpress.org/locale/ru/default/wp-plugins/12-step-meeting-list/

if requested, we'd be happy to start the process of adding translations to TSML UI and the types in the Spec
