### ISSUE TITLE
Bug: Address gets deleted when moving from Draft to Published

### ISSUE THREAD

**Issue by scottvanwa2** [code4recovery/12-step-meeting-list#119]
**Describe the bug**
We have moved several of our previously published meetings to "Draft" while we update them with their Virtual Meeting URL's. We then Republish them. The moment we republish the address gets wiped out of the Address field. An address then needs to be reentered and the meeting published again.

**To Reproduce**
1. Go to WP Admin > Meetings > Previously published meeting.
2. Change to type Draft > Update
3.  Click on Publish
4. Address is no longer present.

**Expected behavior**
The address should maintain through draft and publish.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 97eighty** [comment]
Hi Scott,
I'm picking this back up. Are you still experiencing problems? Can you tell us which Maps API you are using?

**Comment by tech2serve** [comment]
I just tested with 3.8.0 using Google maps, and did not see an issue. @scottvanwa2, can we close this?
