### ISSUE TITLE
Setting exact coordinates for location directly on WP admin

### ISSUE THREAD

**Issue by TheGreenSourcerer** [code4recovery/12-step-meeting-list#122]
**Is your feature request related to a problem? Please describe.**

Right now the location coordinates are either set automatically through geocoding or manually in the code. While the second method is designed for the exceptional cases, from my experience such cases are much more common than they may seem (especially outside of US). 

**Describe the solution you'd like**

Add optional (and possibly hidden/collapsed by default) fields for longitude and latitude inside the location pane on WP admin panel. 

**Describe alternatives you've considered**

The original plugin functionality may be extended by external plugin (if there are any technical issues with including it in 12SML).

**Comment by FlipperPA** [comment]
We've done this slightly different on the Django/Wagtail version; I'm not sure if it is a pattern that TSML might want to follow.

![image](https://user-images.githubusercontent.com/68164/86772899-e153ad80-c022-11ea-84f6-565ece1cc893.png)

The `Full Address` field populates suggestions from Google Geocoding API, and when you select one, it populates the Latitude / Longitude field. You can then move the pin or edit the Latitude / Longitude manually. This allows, for example, moving the pin to a rear or side entrance of a large building or complex.

**Comment by TheGreenSourcerer** [comment]
@FlipperPA this looks great! It would be awesome to have such functionality inside the 12SML in WP

**Comment by TheGreenSourcerer** [comment]
I know that this might not be a top priority in development, but I could propose some implementation (PR)

**Comment by tech2serve** [comment]
Hey @TheGreenSourcerer, happy to consider and discuss a PR. Haven't put a lot of thought into this yet as we're focused on requested improvements for online meetings, but I think with more outdoor meetings, business centers, etc., there is justification for being able to tailor the location of the marker.

**Comment by TheGreenSourcerer** [comment]
> Hey @TheGreenSourcerer, happy to consider and discuss a PR. Haven't put a lot of thought into this yet as we're focused on requested improvements for online meetings, but I think with more outdoor meetings, business centers, etc., there is justification for being able to tailor the location of the marker.

@tech2serve then I'll prepare some MVP 🙂

**Comment by tech2serve** [comment]
Hey @TheGreenSourcerer, Just wanted to follow up and see if you were working on this?

**Comment by TheGreenSourcerer** [comment]
Nope, nothing yet
