### ISSUE TITLE
Online Meeting Type gone after latest update

### ISSUE THREAD

**Issue by TwinSpringsWeb** [code4recovery/12-step-meeting-list#124]
After the latest update the "Online Meeting" type is gone from the checklist.

**Comment by tech2serve** [comment]
Hi @TwinSpringsWeb. 

We simplified the UI so that all you have to do is enter the URL for the conference (i.e., Zoom) and the code will automatically handle the rest. 

Please let me know if I misunderstood.

**Comment by TwinSpringsWeb** [comment]
No that's perfect! I just panicked when I couldn't find the Online Meeting
Box.

Thank you so much for your help.


*Mike Thompson*
*Twin Springs Web Development*
*502-376-3891*
*TwinSpringsWeb.com*


* <http://www.twinspringsweb.com>*
