### ISSUE TITLE
Testing TSML in WordPress 6.4 - no problems seen so far

### ISSUE THREAD

**Issue by dvcb** [code4recovery/12-step-meeting-list#1246]
### What happened?

I've spent several hours testing TSML in WordPress 6.4 RC 2 and have not found any problems so far.
Followed the testing checklist in both a fresh WordPress install and in a larger site with custom themes and many plugins. 
Tried both sites with both PHP 7.4.33 and 8.2.11
When 6.4 is released on 11/7 I'll upgrade our local central office site and will report any issues.  Thanks!

**Comment by joshreisner** [comment]
thank you @dvcb !!

i'll close this when i release a version that updates sets "tested with" to `6.4`
