### ISSUE TITLE
Error deleting plugin

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1342]
a user in #1341 reported an issue deleting the plugin, and i saw that too when trying it on our dev site:

<img width="806" alt="Screenshot 2024-02-07 at 5 01 51 PM" src="https://github.com/code4recovery/12-step-meeting-list/assets/1551689/5a45d7ab-7f08-4a1b-afd4-81dc4e26de59">

**Comment by kiyote33** [comment]
I've played with this a bit.  On a normal pristine installation, it seems to work consistently well.  The above problem happens for me when I've uploaded a new copy of the plugin, activated it, then deactivated it, and finally try to delete the plugin in the normal fashion. I then get the above error.

**Comment by joshreisner** [comment]
this should be fixed now in `3.14.30` (just released). thanks @gkovats !
