### ISSUE TITLE
Online meeting URL's can't be deleted

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1354]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/1353

<div type='discussions-op-text'>

<sup>Originally posted by **ljread** February 15, 2024</sup>
We just moved to a new web host provider. Don't know if this issue is related.

When trying to remove a URL for an online or hybrid meeting, the URL repopulates after pressing the update button (which sometimes requires pressing twice to get an update notification.) Changing or adding a URL works. All other editing functions appear to work. Deleting the meeting and adding back works. TSML appears to display and function normally.

I had thought to delete and reinstall the TSML plugin but would rather avoid this if I can. Any ideas to fix without going to this extreme would be appreciated.

I will try to logon to the old server and see if the issue occurs there as well. I also see there is a new version of TSML, so I will update and hope that fixes my issue.

Wordpress version: 6.4.3
TSML version: 3.14.30

Thanks, John Read</div>

**Comment by joshreisner** [comment]
seems like something is wrong in `save.php` i also observed a bunch of warnings while running with `WP_DEBUG` set to true

**Comment by douggreen** [comment]
I've had two related problems today. In both cases I cannot save.
1. removing the online information from one meeting
2. adding a new meeting that is online only
