### ISSUE TITLE
[Bug]: Deprecated

### ISSUE THREAD

**Issue by AquaZebra** [code4recovery/12-step-meeting-list#1399]
### Contact Details

mark@aquazebra.com

### Website With Issue

https://aainthedesert.org/meetings/choice-is-yours-meditation-meeting/

### What happened?

Page without the bug.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Relevant log output/errors

```shell
Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /home4/kmpmitmy/public_html/wp-content/plugins/12-step-meeting-list/includes/functions.php on line 1048
```

**Comment by gkovats** [comment]
Looking now, that's certainly a helpful PHP error.

**Comment by gkovats** [comment]
@AquaZebra for what it's worth, this is more a PHP warning we'll fix, but you may want to disable display of errors on your live site:
https://stackoverflow.com/questions/1987579/remove-warning-messages-in-php

That's just cosmetic though, the warnings will still exist, and depending on your host provider this may not be realistic.

**Comment by anchovie91471** [comment]
You may also want to add:

define('WP_DEBUG', false);
define('WP_DEBUG_DISPLAY', false);

to your wp-config.php to remove warnings and errors from showing up on your site. This is a wordpress security best practice.

**Comment by AquaZebra** [comment]
Thank you.

I added this to the wp-config.php file and the errors are no longer showing on the site.
The code was inserted before:
/* That's all, stop editing! Happy blogging. */ in the wp-config.php <https://developer.wordpress.org/advanced-administration/wordpress/wp-config/> file.

// Enable WP_DEBUG mode
define( 'WP_DEBUG', true );
// Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );
// Disable display of errors and warnings
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );


In Gratitude,

Mark E. Anderson
760-880-5174
***@***.***
https://aquazebra.com


￼

We earn our stripes every day
Helping authors turn their manuscript into a book.
Helping businesses capitalize their online presence by building websites that work.

On Mar 25, 2024, at 7:11 AM, Anthony Baggett ***@***.***> wrote:


You may also want to add:

define('WP_DEBUG', false);
define('WP_DEBUG_DISPLAY', false);

to your wp-config.php to remove warnings and errors from showing up on your site. This is a wordpress security best practice.

**Comment by gkovats** [comment]
@AquaZebra  thanks for the update. We'll close this issue for now, and address the PHP warning in a later patch.

**Comment by joshreisner** [comment]
version `3.14.34` released with fix ✅
