### ISSUE TITLE
Can't Customize Meetings URL

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#140]
In the FAQ, it says that users can change the URL of the meeting list by setting a value for `$tsml_slug` in their theme. This no longer works.

https://wordpress.org/plugins/12-step-meeting-list/#%0Acan%20i%20change%20the%20url%20of%20the%20meetings%20list%3F%0A

In addition, it would be useful for some users to disable the public meeting finder altogether (say if they were using the new shortcode).

**Comment by trivalleyaa** [comment]
joshreisner - you are awesome, thanks for your wonderful service
