### ISSUE TITLE
Improve coverage of gettext phrases on TSML classic frontend

### ISSUE THREAD

**Issue by gkovats** [code4recovery/12-step-meeting-list#1402]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/1401

There are some boilerplate phrases on the front end in TSML classic that can be wrapped with gettext and updated in the /languages/ pot file. Goal is to improve coverage on the front end for language translation.

**Comment by joshreisner** [comment]
fixed with release of `3.14.34`
