### ISSUE TITLE
Bug in widget layout on some themes with TSML UI appearance

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#1427]
on our website, if i add paragraphs to the top and bottom meetings page widgets using the TSML UI appearance, i see content appearing to the left and right of the meeting finder, when it should be above and below

<img width="1206" alt="Screenshot 2024-05-22 at 7 26 05 AM" src="https://github.com/code4recovery/12-step-meeting-list/assets/1551689/da60ce1f-bd6f-411e-899b-16cd6c52751d">

**Comment by k8fish3r** [comment]
Wish it were possible for meetings top - to disappear once an individual meeting has been selected (like it used to work).

**Comment by joshreisner** [comment]
@k8fish3r we haven't changed that. it still scrolls you to the meeting finder when you select a meeting.

**Comment by kiyote33** [comment]
Unable to repro this front end bug using the latest block themes. Was it fixed with the recent block theme updates?

**Comment by k8fish3r** [comment]
Many thanks guys, I had problems resetting github password. I appreciate your sharing - ninja web skills!! Id not have guessed the route of the issue.

**Comment by k8fish3r** [comment]
You've added extra widget positions too!! Thank you :)

Meetings bottom
Meetings detail bottom
Location detail bottom
