### ISSUE TITLE
Online Meeting Button Getting Cut Off

### ISSUE THREAD

**Issue by scottvanwa2** [code4recovery/12-step-meeting-list#143]
**Describe the bug**
On the meeting details page the Online Meeting section to the left of the map cuts off half of the Zoom button

**To Reproduce**
1. Go to 'http://www.vancouveraa.org/meetings/as-bill-sees-it-4/?tsml-day=4
2. Scroll down to Online Meeting
3. See error

**Expected behavior**
The full button should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/66804755/89133909-0679f580-d4d5-11ea-8e8a-f6c80196bcd6.png)

Happens on all browsers/ mobile and PC. If I need to modify a file just need to know which one. 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joshreisner** [comment]
Hi @scottvanwa2 looks like your theme has some CSS in it that is affecting the layout (and also uppercasing the text).

If I uncheck the 'float: right' property coming from main.css then the layout goes back to normal. 

You might try adding some custom css like `#tsml a.btn { float: none; }` to see if that fixes it.

<img width="1509" alt="Screen Shot 2020-08-03 at 9 55 45 AM" src="https://user-images.githubusercontent.com/1551689/89207533-bf8d0e00-d56f-11ea-8c3e-2aef7ff5968c.png">

**Comment by scottvanwa2** [comment]
Thanks for your help!



*Thanks,Scott Capistrant(775) 622-5056*
