### ISSUE TITLE
[Bug]: Meeting list not displaying showing following error "Timezone -04:00 is not valid. Please use one like Europe/Rome."

### ISSUE THREAD

**Issue by JoeBryan7873** [code4recovery/12-step-meeting-list#1435]
### Contact Details

joebryanmarketing@gmail.com

### Website With Issue

https://capecodaa.net/meetings/

### What happened?

Hi,

Contacted by user that the meeting list was no longer displaying. When you go to the page you get the following error message.
https://capecodaa.net/meetings/
![Timezoneerrormessage](https://github.com/code4recovery/12-step-meeting-list/assets/130705835/556419f7-3804-456b-8515-e7f7ace85084)

Timezone -04:00 is not valid. Please use one like Europe/Rome.

The problem only appears on desktop browsers, when I tested the site on my mobile phone it still appears to be working correctly.

Really not sure what the issue is, please advise.
Thanks in advance,
Joe Bryan

### What browsers are you seeing the problem on?

Firefox, Chrome

### Relevant log output/errors

```shell
Timezone -04:00 is not valid. Please use one like Europe/Rome.
```

**Comment by JoeBryan7873** [comment]
Sorry was able to correct the issue, thank you anyway. Really appreciate the work you do.

**Comment by joshreisner** [comment]
yes judging by your site name, your timezone should be set to `America/New_York` - this way daylight savings will work properly 

in the future please [create a discussion](https://github.com/code4recovery/12-step-meeting-list/discussions) rather than filing a new ticket, thanks!
