### ISSUE TITLE
Monthly Meeting

### ISSUE THREAD

**Issue by coressel** [code4recovery/12-step-meeting-list#145]
Do we have a feature or the ability to set a monthly meeting for the day of the week? It may be a little tricky to create the code, but for the last Sunday of a particular month?

**Comment by tech2serve** [comment]
Hi @coressel,

Are you saying the meeting only meets ones each month? Or, is this akin to the birthday meeting for a Sunday night meeting?

The best way to handle special event meetings is usually to put them into the notes for the regular meeting.

**Comment by coressel** [comment]
Yes, for a meeting that meets only once a month at the same time. So the last Sunday of the month each month is a meeting.

**Comment by FlipperPA** [comment]
Recurrence like this can get really tricky, unfortunately. We have some committee meetings in our Intergroup that meet the first Wednesday AFTER the first Monday of the month, for example.

**Comment by 97eighty** [comment]
Closing this here for now. Added issue to meeting spec at https://github.com/code4recovery/spec/issues/34. Probably should be in the spec before consideration here.
