### ISSUE TITLE
Sorting by location is not working as expected

### ISSUE THREAD

**Issue by TheGreenSourcerer** [code4recovery/12-step-meeting-list#146]
**Describe the bug**

When the user is sorting by the location the results are not ordered properly for Polish character set. 

**To Reproduce**
1. Go to https://spis.aa.org.pl/index.php/meetings/?tsml-day=any&tsml-region=wojewodztwo-mazowieckie
2. Click on 'Lokalizacja' column name (locations)
3. Scroll down to the row with 'Żabia Wola' in location column
4. The results seem to be ordered randomly in several cases

**Expected behavior**

The proper ordering including Polish characters is:

A Ą B C Ć D E Ę F G H I J K L Ł M N Ń O Ó P (Q) R S Ś T U (V) W (X) Y Z Ź Ż

**Screenshots**

![image](https://user-images.githubusercontent.com/51343011/90308926-200f3a00-dee4-11ea-954f-13b963fd3467.png)

![image](https://user-images.githubusercontent.com/51343011/90308991-92801a00-dee4-11ea-9b1b-626a845462b1.png)

![image](https://user-images.githubusercontent.com/51343011/90309021-d3782e80-dee4-11ea-8cd4-9beab564b0e1.png)

**Desktop (please complete the following information):**

 - OS: all
 - Browser: tested on Chrome and Firefox
 - Version: Chrome 84.0.4147.125, Firefox version unknown

**Smartphone (please complete the following information):**

Not tested on smartphone

**Comment by tech2serve** [comment]
Hello @TheGreenSourcerer, I've not been ignoring your issue here, but we didn't get a chance to discuss it among the team members during our last session. We'll try to look closer at this, and we may come back to you asking for some help with the polish alphabet :-)

**Comment by crispyatl** [comment]
It seems the issue is multi-fold. First, the current PHP and Javascript code "sanitize" meeting information strings before using them to sort, and this sanitization process drops some letters from the Polish alphabet (and presumably many other non-latin languages).  For example, "Łochów" becomes "ochow" after sanitization. Second, the sorting itself is done in a locale-naïve way, so that words starting with Z, Ź and Ż would all be sorted as if they were the letter "Z". I'm working on a fix for both of these issues.

**Comment by TheGreenSourcerer** [comment]
> It seems the issue is multi-fold. First, the current PHP and Javascript code "sanitize" meeting information strings before using them to sort, and this sanitization process drops some letters from the Polish alphabet (and presumably many other non-latin languages). For example, "Łochów" becomes "ochow" after sanitization. Second, the sorting itself is done in a locale-naïve way. For example, words starting with Z, Ź and Ż would all be sorted as if they started with the letter "Z". I'm working on a fix for both of these issues.

Thank you @crispyatl !

**Comment by tech2serve** [comment]
@TheGreenSourcerer -- 

If you're savvy enough with GitHub and you have a staging/test site, perhaps you could check out the code from the PR and test it? 

If not, no problem. We'll keep testing with our resources and hopefully it will work for you as well. :-)

**Comment by tech2serve** [comment]
Fix should be in 3.9.0.

**Comment by StudioLisa** [comment]
You rock.








:p
