### ISSUE TITLE
[Bug]: Drafts Not Changing to Published When Updated

### ISSUE THREAD

**Issue by DFWDesignGuy** [code4recovery/12-step-meeting-list#1466]
### Contact Details

rick@irickweaver.com

### Website With Issue

https://aaneok.org/

### What happened?

In the plugin, when we add a new meeting record, as has always the case, any “new” item always starts off as a “DRAFT and when we hit PUBLISH, the status changes from DRAFT to PUBLISHED. For some reason, When we add a new record in the MEETINGS area and hit PUBLISH now, it stays to DRAFT once the page fully reloads. How do we get it to read as PUBLISHED?

### What browsers are you seeing the problem on?

Chrome

**Comment by gkovats** [comment]
@DFWDesignGuy  could you share a screen shot of the edit page that's stuck in draft? I know sometimes there's a required field that can hold the meeting from publishing, would want to check all fields are supplied when you attempt to publish.

**Comment by anchovie91471** [comment]
Sometimes the address entered doesn't successfully geocode, which can cause this issue as well.

**Comment by DFWDesignGuy** [comment]
![Screenshot 2024-07-12 at 11 40 10 AM](https://github.com/user-attachments/assets/23ae5463-e42e-44da-8b41-0295347103f2)
![Screenshot 2024-07-12 at 11 40 24 AM](https://github.com/user-attachments/assets/255cefd8-1dd3-41c4-9e72-653efc757218)
![Screenshot 2024-07-12 at 11 40 38 AM](https://github.com/user-attachments/assets/e5b6fa16-76f7-40b0-a1b7-91db01567ba8)
![Screenshot 2024-07-12 at 11 40 47 AM](https://github.com/user-attachments/assets/fac18e5b-5981-4793-ac1f-c4e2cc937bda)

**Comment by anchovie91471** [comment]
In-person meetings require an address. This is very likely your issue. Can you enter an address and try to save?

**Comment by DFWDesignGuy** [comment]
Thanks.  That brings up another issue.  This is supposed to be a ZOOM only meeting and each time we try and choose the Virtual radio button and publish it reverts back to in person

**Comment by joshreisner** [comment]
for an online meeting, enter an approximate location, such as Las Vegas, NV, then check "no" under "can i currently attend this meeting in person" and be sure to include a valid zoom (or other) url

**Comment by DFWDesignGuy** [comment]
Thanks Josh, we will give that a try.

**Comment by DFWDesignGuy** [comment]
So, that didn't work. Here are some screenshots to show you what I have selected before hitting PUBLISH and it still saves as a DRAFT after publishing. 

![Screenshot 2024-07-12 at 3 58 24 PM](https://github.com/user-attachments/assets/af0726de-e77c-45f4-b5db-caed9fc233aa)
![Screenshot 2024-07-12 at 3 58 38 PM](https://github.com/user-attachments/assets/1d6cd616-0981-4eec-acd2-ccd9f6732eac)
![Screenshot 2024-07-12 at 3 59 08 PM](https://github.com/user-attachments/assets/23922b8f-1188-4d53-81de-a00e9ff1d949)
![Screenshot 2024-07-12 at 3 59 22 PM](https://github.com/user-attachments/assets/21a0eb95-287e-4970-a7fd-c5ca1aa84ba0)
![Screenshot 2024-07-12 at 3 59 45 PM](https://github.com/user-attachments/assets/15e38ed6-37e0-47df-a7a2-8cf350fb8d6b)

**Comment by joshreisner** [comment]
these screenshots are super helpful, thanks. normally the `City` dropdown says `Region`, but that's no big deal. i mean though enter Tulsa in the `Address` field. when you tab out, it should look this up and replace it with `Tulsa, OK, USA`. then you should be good to hit `Publish` and it should hopefully work 🤞

**Comment by DFWDesignGuy** [comment]
Thanks Josh! Headed to home group.  I’ll give it a try when I get home later tonight.  You da best!

**Comment by DFWDesignGuy** [comment]
Hi Josh!  VOILA!  That worked.  I did each of the things you suggested and when I published, it changed from draft to published.  You're the best.  Thank you so much!!!!!

![Screenshot 2024-07-12 at 10 18 23 PM](https://github.com/user-attachments/assets/4e5b9fa7-d99e-4ce8-9898-9279bc818b8b)
![Screenshot 2024-07-12 at 10 18 37 PM](https://github.com/user-attachments/assets/a3591d2b-d8f1-4493-8aff-f37e359ca3ba)
![Screenshot 2024-07-12 at 10 18 57 PM](https://github.com/user-attachments/assets/27e35dd3-94eb-4d9a-8737-f48455d8969a)
![Screenshot 2024-07-12 at 10 19 14 PM](https://github.com/user-attachments/assets/0adfc7c5-424b-4909-9248-8bdf06f5baae)
![Screenshot 2024-07-12 at 10 19 28 PM](https://github.com/user-attachments/assets/43620aaf-dcbf-4bdb-9bf7-cdcea29a8f0c)
