### ISSUE TITLE
Update Main Dashboard Widget to Highlight Need for Financial Contributions

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#1468]
### Contact Details

waynep@code4recovery.org

### Requested Feature/Enhancement

Our by-weekly discussion on July 13th pointed out the need for contributions from TSML end users to ensure that the development team members who are donating their time and efforts on behalf of the many recovery communities using our services are not also saddled with shouldering the financial burdens associated with maintaining and expanding the services that the Code For Recovery team provides. 
Some development team consensus has evolved where slight tweaks to the main dashboard widget function encouraging a $20 dollar annual contribution to Code For Recovery might help provide an incentive to TSML end users to make monthly/yearly support payments to help us pay our way. More detail could be added to the Contributions page. Most involved in the discussion agree a statement like "Our recommended donation for the use of 12 Step Meeting list is $20/year, but all contributions are appreciated!" would be beneficial. 
There is also considerable support for a larger re-write of the Dashboard widget or creating one of those plug-in pop-ups along the line of the following: 
"**Support Our Mission with a Monthly or Yearly Contribution**
Your donations help cover hosting fees, content delivery, geocoding, and other essential services that enable recovery communities to thrive. Every contribution makes a difference.
Our recommended donation for the use of 12 Step Meeting list is $20/year, but all contributions are appreciated!
[https://code4recovery.org/contribute]".

**Comment by kiyote33** [comment]
![image](https://github.com/user-attachments/assets/533ce878-2eb7-460c-912f-f5c94e5abe94)
Instead of modifying the dashboard widget, another alternative is to publish a TSML_alert() like this.

**Comment by joshreisner** [comment]
i support updating these zones with better messaging and a contribute button. i dont think we should add a new message though

<img width="514" alt="Screenshot 2024-07-16 at 6 07 01 PM" src="https://github.com/user-attachments/assets/dd46b307-c7d6-4ce8-b730-a2f2010cffb7">

<img width="515" alt="Screenshot 2024-07-16 at 6 07 27 PM" src="https://github.com/user-attachments/assets/4794d0be-dd20-414c-86f2-00e7c0e7ebac">

**Comment by joshreisner** [comment]
fwiw, if i were donating, this text on the contribute page would persuade me to make it a one-time contribution. 

> Please note that if you intend to cancel a recurring contribution that was set up in the past or if you have multiple recurring contributions, you may need to utilize the link provided in the receipt. The button above will only allow you to access the most recently created transaction.

we'd get better traction if the text was along the lines of

> Have a question about a past contribution? Contact us and we can help! contributions@code4recovery.org

**Comment by kiyote33** [comment]
Seems like the wordsmithing of these type of messages never end. I do appreciate the minimalist approach.
![image](https://github.com/user-attachments/assets/310572c7-62be-471c-a6f6-306a3ed06265)
The text  "Our recommended contribution to us for the use of 12 Step Meeting list is $20/year, but all contributions are appreciated!" could be added to the contribution page.

**Comment by gobborg** [comment]
Is there consensus on how to move forward with this? Change the dashboard text or add a popup?

**Comment by joshreisner** [comment]
i haven't had the opportunity to talk about it with the team yet but i still feel that these are the zones we should update: https://github.com/code4recovery/12-step-meeting-list/issues/1468#issuecomment-2232109861
