### ISSUE TITLE
user interface is supposed to use an ajax call to retrieve the meeting list upon delimiter selection.  It currently doesn't.

### ISSUE THREAD

**Issue by onemooresam** [code4recovery/12-step-meeting-list#147]
We received the following for https://nc23.org/meetings/. Any guidance is appreciated.

_The mobile meeting finder site's user interface is supposed to use an ajax call to retrieve the meeting list upon delimiter selection.  It currently doesn't._

**Comment by tech2serve** [comment]
Hey @onemooresam, I'm unclear what you're asking.

Can you elaborate what is meant by "mobile meeting finder"? Are you referring to TSML when viewed using a mobile device? Or the Meeting Guide app? Or something else.

Please have the originator help us understand what user experience isn't being met.

**Comment by onemooresam** [comment]
That would be viewing nc23.org/meetings on a mobile device.

**Comment by tech2serve** [comment]
Thanks @onemooresam,

I'm going to close this for now, and we if see a spike of related issues, we can readdress, including looking closer at your provider to see if there is a common thread.
