### ISSUE TITLE
[Feature Request]: Whatsapp / SMS Support for meeting organiser - contact details

### ISSUE THREAD

**Issue by k8fish3r** [code4recovery/12-step-meeting-list#1483]
### Contact Details

k8fisher9@gmail.com

### Requested Feature/Enhancement

With many meeting organisers / members preferring Whatsapp / txt - for communication it would be really helpful to add support to 12 Step Meeting List component.

Outcome for 12 Step Meetings List Component:
From the back end:
- Contact numbers can be setup as Call /  SMS / Whatsapp in the back end

From the front end:
-  When selecting a Whatsapp contact / SMS Contact:
Approximately `<a href="https://api.whatsapp.com/send?phone=15551234567">Whatsapp Bob</a>`
Approximately `<a href="sms:15551234567">Message Bob</a> `

The requested action is launched, instead of just "Call Bob"

Assuming there's probably as many people who don't want to be called, they'd rather respond to a text / whatsapp?

**Mindful ideas are like hands (everyone has them).**

**Comment by ginslo** [comment]
Hello @k8fish3r, development is in process to switch from Phone to SMS globally per your feature request #1463. Adding the ability to have a preference field or dropdown for Whatsapp and potentially other common chat providers is being considered.

**Comment by k8fish3r** [comment]
Many thanks @ginslo I wasn't sure if the query was just a discussion - so thought I should create a feature request.

Will request. I appreciate support of the team. 

Ty
