### ISSUE TITLE
Upcoming Meetings Widget Pull Multiple Days?

### ISSUE THREAD

**Issue by alexmurphy6194** [code4recovery/12-step-meeting-list#151]
Hey , just wondering if there is a way to have the Upcoming Meetings widget pull meetings for say, 2-3 days out. The Alano club only has one or two a day, so it would be beneficial to see more there.

Thanks
Alex

**Comment by tech2serve** [comment]
The short answer is no. We discussed it in the past, but the purpose of the widget is for people to quickly see remaining meetings that day. We do provide the option for you to add a message, if there are no additional meetings, stating someone should look at the complete meeting list for next day options, or whatever you want the message to say.
