### ISSUE TITLE
Edit [tsml_ui] shortcode to filter meetings by passed types

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#1511]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/1481

<div type='discussions-op-text'>

<sup>Originally posted by **district6wc** August  4, 2024</sup>
Hi

I'd like to list the Alateen meetings on our Alateen page, is there a shortcode that can manage this?

Thanks
Rose L</div>

Modify [tsml_ui] shortcode to accept passed parameter types. See the WordPress function [add_shortcode](https://developer.wordpress.org/reference/functions/add_shortcode/) and our short code `tsml_next_meetings($arguments)` for related details on how to do. The end case usage would be something like `[tsml_ui type="alateen"]:`

**Comment by kiyote33** [comment]
Creating a shortcode to accomplish filtering for TSML is a relatively easy task, with the result being an intermediate HTML selection table . Modifying the shortcode "tsml_ui" to do the same is much more complicated with a higher impact risk associated and changes necessary in multiple files. I suggest that TSML UI simply be filtered with an "Alateen" menu item and the following navagational path code: `/meetings/?type=Alateen`. I think that's what we want in the end here. Any thoughts on this?

**Comment by joshreisner** [comment]
historically when we've gotten this request we have suggested people add a link to their meeting finder with that type selected, but it's not what the user is requesting here. 

i heard the same request recently from New Orleans Central Office: they wanted to be able to embed a list of only Women's meetings on a specific page

i don't think it's quite as hard as all that though. i added an [item on the TSML UI readme](https://github.com/code4recovery/tsml-ui/?tab=readme-ov-file#override-type-defaults) showing how. i think we'll only need to make changes to `shortcodes.php`

**Comment by kiyote33** [comment]
@joshreisner, While this is doable for TSML, I've tried everything I can think of to get this to work for TSML UI. I see in our recent history you indicated in #1352 that this **might not** be doable. Has something changed that makes you think otherwise now?

**Comment by joshreisner** [comment]
that discussion was about how it's not possible for a local website to customize the react config object manually outside the shortcode, but since we have access to make changes inside the shortcode, we can do whatever we want ;) 

this is documented at the link i shared above, but i think we want it so that if you make the shortcode

`[tsml_ui type=["women"]]`

that the shortcode produce a config object like this:

```
var tsml_react_config = {
  defaults: { type: ['women'] },
}
```

**Comment by kiyote33** [comment]
Maybe you can see why this doesn't work:
```
    //Load Shortcode values passed, overriding default values
    print_r($atts);
    echo '<br>';
    $parms = shortcode_atts(array('key' => '', 'value' => '', ), $atts);
    $key = (isset($parms['key'])) ? sanitize_text_field($parms['key']) : 'Type';
    $value = (isset($parms['value'])) ? sanitize_text_field($parms['value']) : 'Any';
    
    if (!empty($atts)) {
        //apply settings when parameters are passed
        wp_localize_script(
            'tsml_ui',
            'tsml_react_config',
            array_merge(
                [
                    "defaults: { $key: [$value'] },",
                    'columns' => array_keys($tsml_columns),
                    'conference_providers' => $tsml_conference_providers,
                    'distance_unit' => $tsml_distance_units,
                    'feedback_emails' => array_values($tsml_feedback_addresses),
                    'flags' => $tsml_programs[$tsml_program]['flags'],
                    'strings' => [
                        $tsml_language => array_merge($tsml_columns, compact('types', 'type_descriptions')),
                    ],
                ],
                $tsml_ui_config
            )
        );

        print_r("defaults: { $key: ['$value'] },");

    `}`

```

**Comment by joshreisner** [comment]
wp_localize_script translates PHP arrays into javascript objects. looks like you're trying to pass in a string javascript object and should be passing in PHP. something like

`'defaults' => [ 'type' => ['women' ]],`

**Comment by kiyote33** [comment]
Thx... I'll give that a try.

**Comment by kiyote33** [comment]
That was exactly right! I'll push up a PR for this issue...
