### ISSUE TITLE
12 Step Program Not Listed

### ISSUE THREAD

**Issue by wsotreasurer** [code4recovery/12-step-meeting-list#152]
My 12 Step Program is not listed in the dropdown.  How can I get it added?

**Comment by joshreisner** [comment]
@wsotreasurer just let us know the name of your fellowship and what types you'd like. thanks

**Comment by wsotreasurer** [comment]
The fellowship is:  Compulsive Eaters Anonymous-HOW.   

Regarding types: do you mean meeting types? 

The following are the meeting types which will be expanded.  Our current meeting finder didn't allow to capture the type of meeting in a separate filed so as we load in the meetings we'll find more.

12 Steps & 12 Traditions
AA Comes of Age
As Bill Sees It
Big Book
Book Study
Came to Believe
CEA-HOW Concept/Tools
Daily Reflections
Happy Joyous and Free
Living Sober
Maintenance
Meditation
Pitch/Speaker
Promises
Relapse and Recovery
Steps/Traditions
Topic/Discussion

Thank you.

**Comment by wsotreasurer** [comment]
Hello checking back on this request.  What do you anticipate the timeline to be to get the program and meeting types loaded?  Thank you.

**Comment by joshreisner** [comment]
Hey @wsotreasurer the code change is made, so hopefully it’ll be released soon and you can update the plugin normally and you’ll see the new option in the drop down.

**Comment by wsotreasurer** [comment]
Thank you!

**Comment by tech2serve** [comment]
@wsotreasurer,

I'm tying to finish testing the 3.8.0 version so we can release it. If you're familiar with the steps, you can download the latest development version (`master`) and help us test the beta over the next couple of days?

**Comment by tech2serve** [comment]
Added with 3.8.0 release.
