### ISSUE TITLE
face-to-face meeting type

### ISSUE THREAD

**Issue by eae** [code4recovery/12-step-meeting-list#158]
**Is your feature request related to a problem? Please describe.**
Many users of our site are asking for an easy way to find which meetings are face-to-face.  It's great that there is an "outdoor meeting" type but as the weather changes and Covid is still with us, many of those meetings will become less popular, shut down, or move indoors.  

**Describe the solution you'd like**
It would be great if there were a "Face-to-Face" meeting type available in the list of checkboxes on the meeting edit screen and in the filter dropdown on the search page.

**Describe alternatives you've considered**
We are currently solving this problem by manually maintaining a list in a word document and periodically uploading a PDF which we link to on our home page.  We have considered extending TSML by adding a child theme and adding the type there, but there is some reluctance among the Web and Tech committees due to the concern that future servants filling our positions may not be tech-savvy enough to support any customizations at all, and the general group conscience is to stick to off-the-shelf solutions to the maximum possible extent.

**Additional context**

**Comment by tech2serve** [comment]
Please see #153. I'm closing this for now, but that isn't to say we won't discuss it in the future.
