### ISSUE TITLE
[Bug]: Error code: "Translation loading for the 12-step-meeting-list domain was triggered too early."

### ISSUE THREAD

**Issue by rut-on** [code4recovery/12-step-meeting-list#1582]
### Contact Details

bekkarut2@gmail.com

### Website With Issue

nai.is

### What happened?

When I updated to the newest WordPress version this error popped up and it won't go away. 
![image](https://github.com/user-attachments/assets/df1eb1aa-8dd5-4c43-87e9-5d36604fcb4a)

### What browsers are you seeing the problem on?

Firefox

### Relevant log output/errors

```shell
Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the 12-step-meeting-list domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see Debugging in WordPress for more information. (This message was added in version 6.7.0.) in /var/www/html/nai.is/wp-includes/functions.php on line 6114
```

**Comment by ginslo** [comment]
Hi @rut-on 

Based on this recent response from @joshreisner : https://github.com/code4recovery/12-step-meeting-list/discussions/1581#discussioncomment-11512194

I'm simply pasting Josh's response as this appears to be the same or similar. If not, please let me know.

it sounds like your site is in debug mode for some reason. this should be disabled in production. go to wp-config.php and make sure WP_DEBUG is set to false:

`define( 'WP_DEBUG', false );`

we'll be releasing a fix soon for this issue as well so you'll be able to have debug mode enabled and not see this message

**Comment by rut-on** [comment]
Thank you so much for the response.
I figured just now that the plugin is also interfering with Woocommerce, Woocommerce does not work when i have the 12 step meeting  list plug-in active anymore.

I can't reach the person that hosts the site, don't I need him to access the wp-config.php?


I'm sorry for the many questions.

**Comment by joshreisner** [comment]
@rut-on this should be resolved now with the latest version of the plugin
