### ISSUE TITLE
New error after WordPress upgrade to 5.5 - jQuery Migrate Helper

### ISSUE THREAD

**Issue by virtualtom** [code4recovery/12-step-meeting-list#159]
jQuery Migrate Helper — Warnings encountered
This page generated the following warnings:

https://buffaloaany.org/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.fn.size() is deprecated; use the .length property
Please make sure you are using the latest version of all of your plugins, and your theme. If you are, you may want to ask the developers of the code mentioned in the warnings for an update.

**Comment by tech2serve** [comment]
It is my understanding 3.8.0 resolves this specific error, so I'm going to close this issue. #168 is now addressing the longer-term issue.
