### ISSUE TITLE
restore tsml_link function for the enhanced feedback plugin

### ISSUE THREAD

**Issue by CyndR** [code4recovery/12-step-meeting-list#1592]
### Contact Details

tetrick.d@gmail.com

### Website With Issue

aacolumbia.org/meetings

### What happened?

Version 3.16.7 auto updated yesterday. When selecting a meeting info returned to user states "There has been a critical error on this website." 

To view the error https://aacolumbia.org/meetings/lunch-box/ 
![aacolumbiaerror1216](https://github.com/user-attachments/assets/75c2f4b9-bf7e-4892-b3e2-6caea842731f)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by joshreisner** [comment]
hmm, we're not seeing any errors on detail pages on our demo site, eg https://demo.code4recovery.org/meetings/spiritual-progress-group-monday-1205

would you be able to enable `WP_DEBUG` temporarily to see what the error is? go to `wp-config.php` and change this to `true` 

```php
define('WP_DEBUG', true);
```

**Comment by CyndR** [comment]
Just a quick update. When I deactivated the 12 Step Meeting List
Feeback Enhancement Plugin the site works as expected.

**Comment by joshreisner** [comment]
ah that's very helpful thanks! it might be that a recent update in TSML is clashing with that plugin

**Comment by CyndR** [comment]
I'll just leave it deactivated until I see that there is an update. I'd be
happy to guinea pig any tests if yall want a hand. I'm very grateful for
the fast response and the help with putting the error into debug. It was
Panic! At The Disco on this side so the help is appreciated.

**Comment by degrees57** [comment]
This bug hit me too, and disabling the Enhanced Feedback Plugin restored my site to working order.

**Comment by joshreisner** [comment]
just released TSML version `3.16.8` hopefully this fixes the issue, lmk thanks!

**Comment by CyndR** [comment]
This seems to be working as expected now. I enabled the TSML Feedback
Enhancement Plugin and I appear to be back in business! Thanks again for
the prompt responses and the very fast update to the TSML!
