### ISSUE TITLE
[Bug]: Venue Address not appearing on Legacy UI single meeting page

### ISSUE THREAD

**Issue by AATimes** [code4recovery/12-step-meeting-list#1597]
### Contact Details

editor@aatimes.org.au

### Website With Issue

https://meetings.aa.org.au/

### What happened?

Since a recent plugin update, the location address is not appearing in the under the location name on the single meeting page. 
Using Legacy UI
Plugin Version 3.16.8
Example - [https://meetings.aa.org.au/meetings/mill-park-beginners/](https://meetings.aa.org.au/meetings/mill-park-beginners/)
<img width="812" alt="ss01" src="https://github.com/user-attachments/assets/62af7729-d6b8-4983-9d6d-596ed8bb4127" />

**Comment by joshreisner** [comment]
just released `3.16.9` which should fix this issue

**Comment by AATimes** [comment]
Thanks for your prompt response.

All good now.
