### ISSUE TITLE
Sample Template

### ISSUE THREAD

**Issue by wsotreasurer** [code4recovery/12-step-meeting-list#161]
The current sample template does not appear to include fields for PayPal and Online Meeting Details (Zoom link).  Perhaps one of the fields included is intended to be used and is mapped in the import process, but its not clear which fields should be used.  One of the Conference fields?

**Comment by tech2serve** [comment]
Hey @wsotreasurer,

My apologies for a late reply to some of your issues; I've been out of commission for a few days. You are correct that we need to update the template.

The PayPal field is simply `Paypal`. `Conference URL` is used for Zoom (or other provider) links.

If anyone else is unsure about template field names, you can add dummy data to the field using the plugin, and then download your meetings in CSV format. Then look at the resulting file, and you should be able to see the field in question.
