### ISSUE TITLE
Return of "Mandatory Closing" time

### ISSUE THREAD

**Issue by CoryBofLI** [code4recovery/12-step-meeting-list#164]
When creating a new meeting, it again will not permit the entry of a blank ending time.
If editing an existing entry it does appear to permit leaving the close time empty.
Using latest versions of Wordpress & plug ins.
Cory Billard
Webmaster
Nassau Intergroup

PS - why has this board become so obnoxious to use all of a sudden

**Comment by tech2serve** [comment]
I just tested using the beta version 3.8.0, and I did not having any trouble adding a meeting without an ending time (I left it blank). I then added an ending time to another meeting, updated it, and confirmed the meeting included an ending time. Next, I edited that meeting and remove the end time, and updated the meeting. Back on the front end, no end time is shown for the meeting.

So, it appears that perhaps the problem you're experiencing is related to either Wordpress itself (we've not tested extensively with the Wordpress 5.5 series) or something else with your setup.

Can you provide a screen cast or at least screen caps of what you're experiencing when you try and remove the ending time and update the meeting?

We're also looking for beta testers if you're willing to help out in that regard?

**Comment by CoryBofLI** [comment]
This was an issue that had come up late last winter, earlier this spring. Cannot find any of the bug reports or resolution. It had been reported and resolved here - as I recall, Josh came up with the solution.
When putting together an update - a variable's name had gotten changed ? or something like that.

**Comment by CoryBofLI** [comment]
Gsot to thinking that it might have been on the original support forum - found it
here is link to the thread:

https://wordpress.org/support/topic/empty-end-time-is-now-turning-into-midnight/

from back then:
      Took a look at the dev site – as suggested above
      Bug report #125 says open & refers to #126
       which shows “this should fix #125”

       tech2serve you had responded
              "We have a fix that is being tested and *should* be released in the next update"

**Comment by tech2serve** [comment]
I remember the issue, and that we validated the bug. We provided what we believed was a fix in 3.7.2, which is the current stable release. 

I think I may have figured out what is going on. When I created a new meeting and simply deleted the end time, it worked correctly, leaving the end time blank. However, when I  created a new meeting and replaced the end time with spaces, the end time became 12:28 pm. 

Please confirm this matches the behavior your'e seeing? 

Are you importing data or using the backend to enter meetings?

**Comment by tech2serve** [comment]
Closing due to lack of response from the OP. Will revisit if more information is provided.
