### ISSUE TITLE
Meeting Search: javascript error if meeting contains only "11th Step Meditation" type

### ISSUE THREAD

**Issue by marcinyorkpa** [code4recovery/12-step-meeting-list#165]
**Describe the bug**
On the meeting list screen, if selecting a search term that returns a meeting that contains **only** the "11th Step meditation" meeting type, the search fails and the list of meetings is empty.

In a JavaScript console, the error "Uncaught TypeError: t.replace is not a function" appears.

I am almost certain that the error occurs in the first string replace of `sanitizeTitle` in https://github.com/code4recovery/12-step-meeting-list/blob/master/assets/src/public.js#L790

The problem appears to be that if one of the meetings has **only** the 11th Step Meditation meeting type, then `11` is an int and not a string, and thus `replace` doesn't work. For meetings that have multiple types, such as "Open", then the array is an array of strings and works fine.

**To Reproduce**
1. Create a meeting with **just** the 11th step meeting type. Save it
2. Go to the meeting list screen and search for that meeting. Observe error

**Expected behavior**
The meeting list would be populated with the search results

**Screenshots**

This screenshot shows the array with a single int for a meeting with just 11th step meeting type selected

![11th_step_meeting_error](https://user-images.githubusercontent.com/70951029/92470348-443cfe80-f1a4-11ea-8a86-e3b0ff0198ce.png)

This screenshot shows an array of strings for a different meeting that has more than just the 11th Step meeting type selected

![11th_step_meeting_no_error](https://user-images.githubusercontent.com/70951029/92470376-4c953980-f1a4-11ea-9c54-1ba9f8af8fd6.png)

I realize this is easy to fix on my end by adding another meeting type to the problematic meeting, and I'll do that. But I thought you should know about this unexpected behavior.

**Comment by tech2serve** [comment]
@marcinyorkpa,

Nineteen days ago when I added the label of "need more information", I also made a comment on this issue. I just noticed today that something prevented it from saving (I had poor Internet). :-(

I am not able to reproduce your issue with this version of TSML or the last one, so we need to look at some other things. I followed your steps to reproduce the error, but when I typed in the name of the meeting in the search field, it displayed as it should have. I've tested in both Safari and Chrome.

Are you still having the issue?
Please confirm your versions of TSML and Wordpress.

**Comment by crispyatl** [comment]
I can confirm that the issue exists in version 3.5.3 of the plugin, but not in the latest version (3.8.0).  I'm betting that the OP is running an older version.

marcinyorkpa: Upgrade to the latest version, and if you are still having a problem, please open a new issue.

**Comment by marcinyorkpa** [comment]
Works for me with 3.8.0. Thanks!
