### ISSUE TITLE
Not A Bug! About data maintenance

### ISSUE THREAD

**Issue by OSAwebsite** [code4recovery/12-step-meeting-list#167]
This is not a bug, it is a question about how best to enhance data maintenance in the TSML plugin.
A new user has asked me for assistance and because they had a reasonably organised Excel sheet, I agreed to help out.

I myself use a database (FileMaker) to maintain data in an offsite location.
But what about users that do not have FileMaker? Or have no knowledge to build something similar that can help with keeping their website updated?

Here is what I did: I used my existing database, since both the new user and I are in Al-Anon areas.
I imported and cleaned their data and was able to create an acceptable CSV output that I then loaded into the plugin on a staging site.

So now.... how do I maintain the meeting pages?
My user has hundreds of them. They can do maintenance online, but the Wordpress user interface does require a lot of patience. It is not always a quick thing. Importing is much quicker. Even though deleting a large bunch of meetings can result in an error 503 of the website. Which is very annoying. I am, as they will be, on a shared hosting plan and of course the vultures of the hosting provider are bugging me to upgrade to another plan with one tongue, and with the other telling me that refreshing 300 plus meetings once a week 'should never be a problem'. But it was. Painfully so.

So... what are the options for non technical users that want to have their meeting details offsite and online?
How do people do that right now?

My own MO is:
I have created direct links to the meeting details pages based on the post ID of the meeting.
That links give me access to that page within a couple of seconds. In Wordpress/in the plugin I have to go to the meetings list, find my meeting and then click that meeting to go to the details. Can take a long time depending on the day.

I also have links to other pages and this works so well that I do not often do refreshes by import anymore.

But it may be necessary to do that when I have, for example, an entire district that needs replacing. I am not willing to take 1-5 minutes per entry for editing details via the Wordpress/plugin interface. It is too much work.

This is nobody's fault, I realise Wordpress is focussed on data publishing and not on database type of queries and actions.

But I wonder if the plugin team has thought about improvements there, if at all possible.

My biggest wish would be that in some way or the other we would get an entry box for the unique meeting ID. For AA this is the GSO ID for us Al-Anons it is the WSO ID. And when we re-import a meeting, the plugin could then see if that meeting already exists and just overwrite it with the new import.

Right now the three options at import do not work as I expect.
When I perform two imports with exactly the same content, the plugin or Wordpress do not see that this is not a new entry. So I end up with two listing each. Which is why I usually delete the meetings I am going to replace and then import.

I would love to hear from others about this issue. Maybe I am overlooking something that new users might find useable?

Any input most welcome!

Cheers

**Comment by tech2serve** [comment]
Hi @OSAwebsite, 

It doesn't look like you had any takers for a convo, but I'll share a couple of my thoughts.

A lot of sites, some pretty darn large, use the TSML admin page for managing all of their meeting information, and then use the csv export feature to make archived copies for other uses. These sites use the csv import feature for the initial set up of the site, and then only if they need to restore it. Frankly, this is the recommended approach for most sites.

Another approach available that some areas use (but I truthfully don't know how many) is what we could call a federated system whereby the area (probably a capital A area, or a large Intergroup or Central Service Office) has districts maintain their databases (again, most likely using the admin page) which are then fed via JSON to the larger, more visible, website. Federation in this manner spreads out the workload and leaves managers closer to the meetings keeping them up-to-date. 

Code for Recovery is developing some additional tools for managing meetings that are in the alpha/experimental stages. In particular, we've got one that will use a Google Sheets doc to provide meetings to a front-end. Once released, a user should be able to simply maintain the spreadsheet. Of course, that does mean putting your data with Google, and some users aren't too crazy about that. Nonetheless, it is a start.

If you have suggestions or feature requests for TSML, please look through/search the existing issues to see if it exists; if so, feel free to comment on the thread. If not, feel free to open a new issue. We're a pretty small group, but we do want to improve the plugin without bloating it or causing breaking changes.

**Comment by OSAwebsite** [comment]
Thanks so much for your input!
I think the first paragraph describes how you can start with the plugin in the most simple way. I do too, for the most part.
I am very interested to hear about an option that gives general users (not people with special roles) the option to print a found set from the list into an Excel document. Or Google Sheet. Or PDF.   And if not via the found set, then at least per District. 

I will follow whatever posts are about these new developments - or else feel free to ping me about it

Thanks again!

**Comment by tech2serve** [comment]
It has been more than a month without discussion, so I'm going to close this thread.
