### ISSUE TITLE
Scrub plugin code for deprecated jQuery functions/calls.

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#168]
Just updated to v3.8.0 and received this error: /wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string when attempting to edit a meeting.

Error only occurs when editing a meeting. Does not occur in dashboard.

WordPress v.5.5.1.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Grateful-Viv** [comment]
Is anyone going to address this?

**Comment by tim-rohrer** [comment]
We expect to discuss this during our group session. We have not t

**Comment by Grateful-Viv** [comment]
WP 5.5 has been out since August 11. Version 5.5.1 was released September 1. Went through great pains to make sure all other plugins and theme was able to work with latest WP version. 

Rather than rollback the WP version, will rollback the plugin which didn’t through this error. 

Thanks.

**Comment by tech2serve** [comment]
My apologies for creating extra work. 

Please see #159 which was an issue submitted before we released 3.8.0.  We included a patch in this last release that we thought fixed the issue, but apparently we need to do more work.

**Comment by tech2serve** [comment]
Duplicates #159

**Comment by Grateful-Viv** [comment]
It’s actually not a duplicate. This only happens when trying to edit a meeting. This only happened after updating plugin to 3.8.0.

**Comment by tech2serve** [comment]
I am trying to look a this now with a site updated to Wordpress 5.5.1 and TSML 3.8.0.

I am not getting any warnings (jQuery or otherwise). Is there a particular part of the meeting you're editing when it occurs? Does the warning occur when you click Publish?

Any additional info will help as I'm having trouble reproducing what you're seeing. Steps to reproduce, screen caps, etc., would be helpful.

**Comment by tech2serve** [comment]
@Grateful-Viv,

My hypothesis didn't hold up to further scrutiny, so I don't know why you're getting the error/warning. I'm going to need more information, along the lines of what we call for in the bug report template please.

**Comment by Grateful-Viv** [comment]
OS: [e.g. iOS] Windows 10 v2004
Browser [e.g. chrome, safari] Chrome
Version [e.g. 22] Chrome 85.

I am running the Enable jQuery Migrate Helper plugin because of other issues with theme and plugins after updating to WP 5.5. They have since been resolved. I have since updated to WP 5.5.1.

I did not have issues with the TSML plugin at all until I updated to version 3.8.0.

I can view published meetings just fine. However, when I go to edit a meeting receive the following error:

https://sdi-staging.sussexaa.org/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string
https://sdi-staging.sussexaa.org/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string
https://sdi-staging.sussexaa.org/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string
Please make sure you are using the latest version of all of your plugins, and your theme. If you are, you may want to ask the developers of the code mentioned in the warnings for an update.

I can make the update and it sticks, but warning message persists. The same occurs if I try to add a new meeting to publish.
![Edit-Meeting-‹-Southern-Delaware-Intergroup-—-WordPress](https://user-images.githubusercontent.com/62247421/93718692-cab1f280-fb4b-11ea-9568-626f9a5fdd68.png)

**Comment by tech2serve** [comment]
But other than the warning messages, which is actually coming from another plugin, is anything not working?

**Comment by Grateful-Viv** [comment]
Not sure if you understand the purpose of the Enable jQuery Migrate Helper plugin (see https://wordpress.org/plugins/enable-jquery-migrate-helper/). This plugin serves as a temporary solution, enabling the migration script for sites to give your plugin and theme authors some more time to update, and test, their code.

Background: jQuery Migrate, a tool which WordPress had bundled, and enabled by default, for many years, has now been turned off by default with WP 5.5. This is a tool intended to help developers in a transitional period, when jQuery (a framework for writing JavaScript code) was upgraded and removed some features.

Hopefully, the tech team for the TSML plugin are working the problems with the deprecated code. The WordPress team is offering a solution to deal with the deprecated code via the Test jQuery Updates plugin (see https://wordpress.org/plugins/wp-jquery-update-test/).

So please do not blame the plugin. Yes, it works, but it is also producing errors which should be addressed. Thank you.

Footnote: I still have TSML v 3.7.2 on live site, and when running the Enable jQuery Migrate Helper plugin, do get same warnings about deprecated code. Specially, 

/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.fn.size() is deprecated; use the .length property
/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string
/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string
/wp-content/plugins/12-step-meeting-list/assets/js/admin.min.js: jQuery.parseJSON requires a valid JSON string

**Comment by tech2serve** [comment]
I'm not blaming the plugin. I have it installed on my dev site, and was able to confirm what you're seeing. 

I'm simply trying to make sure I understand if there is something not working on *your* website right this moment today. A warning is just that. We'll look into it in the course of updating and preparing for the next version of Wordpress.

**Comment by Grateful-Viv** [comment]
You said two days ago you were not getting any warnings. 

It doesn't make the program not work, but the warnings are there and that is why I reported it. 

Glad you're aware of it and working towards a solution.

Thank you.

**Comment by tech2serve** [comment]
As Wordpress continues to migrate to a modern version of jQuery, TSML code needs to be scrubbed for deprecated jQuery methods/functions.
