### ISSUE TITLE
Filter by meetings that are available in-person

### ISSUE THREAD

**Issue by jonsecrist** [code4recovery/12-step-meeting-list#171]
It is easy to find meetings that have temporarily closed by selecting that meeting type. However, it is difficult to find meetings that have reopened. If there were a meeting type like, “Face to Face”, “In-Person” or “Reopened.” Or if there is an easy way to find meetings that are NOT a specific type.
The “Location Temporarily Closed” was a good idea. However, now we need someway to reverse this. In fact, I wonder why I would want to find meetings of the type, “Location Temporarily Closed” because I could not attend it because it is closed. Yet we need such a type to identify such meetings.
You have been great as we came into this pandemic adding things like online meeting link. I’m sure you will find a way as we come out of the pandemic as well and easily find meetings that have reopened. 
My email is jonsecrist@gmail.com or manager@aacincinnati.org

**Comment by tech2serve** [comment]
Please see #153 and #158 for our basic thoughts. In summary, we recognize the need for better filtering and more granularity with the status of a particular meeting. Our goal has been to keep the meeting types more focused on the "traditional" format types so that the list of said types doesn't become more unwieldy for users.

**Comment by Grateful-Viv** [comment]
We added in the notes section (you can do this for any of the note text fields) the meeting has reopened. Then added a menu bar  item called "Reopened Meetings" using the string _/meetings/?tsml-day=any&tsml-query=reopened_.  If you prefer, you could call this "in-person", and then do similar search.

**Comment by CoryBofLI** [comment]
As another very viable work around - add special notations to the particular meeting name:
for example ;  Smithtown Big Book Group * * * Reopened * * *,
By adding it to meeting name, other meetings of same group can remain with the '"temporarily closed status"
While this will not add a type to the drop down menu - is entered into the "Search" box the appropriately marked groups will show up in that list. Several other items of importance can easily be added using this technique.
Used by https://nassauaa.org/meetings or even more extensively by https://suffolkny-aa.org/meetings/?tsml-type=UNK
Hope this helps
Cory B

**Comment by tech2serve** [comment]
Included in TSML v3.11.0, available in beta.
