### ISSUE TITLE
Better Handling for Approximate Locations

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#173]
It's possible to use the address field to enter approximate locations. This is great and should be done more and more for online meetings, especially now that Meeting Guide supports this behavior. The problem is that in TSML these approximate locations, eg `Prague, Czechia`: 

1. show as a discrete point on the map
1. show a concrete distance when in 'near me' or 'near location' mode
1. allow a user to get directions

That an address is approximate can be inferred in the geocoding response from Google. For such addresses `[location_type] => APPROXIMATE`

It would be great to also display this info to the user when editing a meeting (eg "Location is approximate, map and directions will be disabled."

Be sure to also add the approximate boolean value to the local geocoding cache.

**Comment by tech2serve** [comment]
Should be included in 3.9.0
