### ISSUE TITLE
How do you change the Intergroup information listed in The Meeting Guide?

### ISSUE THREAD

**Issue by jammer032898** [code4recovery/12-step-meeting-list#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tech2serve** [comment]
I'm assuming you're talking about the service entity that shows up with a meeting listing on the app's screen. That information is controlled by GSO when they import the data. It is not controlled by `12-step-meeting-list`.

Please contact appsupport@aa.org for all questions regarding the Meeting Guide app.
