### ISSUE TITLE
Meeting Search Page not working properly

### ISSUE THREAD

**Issue by puebloaa** [code4recovery/12-step-meeting-list#175]
When you use the search page not all fields are working and when you change a second field, all the other fields return to default.

**To Reproduce**
1. Go to the meeting search page
2. If you click on the day option, you can not change to anything but Wednesday.
3. If you click on an other field, it will change to your selection; but, if you click on another field it will return your original selection to its default value.

**Expected behavior**
1. I expect the day menu allow me to select an option besides Wednesday.
2. I expect the field menu selection to remain when performing a search

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox
 - Version 81.0.  The same problem occurs in Chrome version 85.0.4183.121.

**Comment by tech2serve** [comment]
It appears the issue you're experiencing is likely related to the SuperFish plugin that is throwing errors on your site. Please try disabling that, and see if you continue to have troubles with TSML.

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/31904316/95368773-2eeaeb00-089c-11eb-8927-c07b50067df5.png">

**Comment by tech2serve** [comment]
A check of the [OP's website](http://www.puebloaa.org) seems to indicate this issue is resolved. Please let us know if that is not the case @puebloaa.
