### ISSUE TITLE
Broken Link To Support

### ISSUE THREAD

**Issue by ebart455987** [code4recovery/12-step-meeting-list#176]
**Describe the bug**
The Link on the Import & Settings page to Need Help > Get Support needs to be updated.

**To Reproduce**
1. Go to '..Import & Settings'
2. Click on '.Get Support ..'
3. See error

**Expected behavior**
This link should lead to 
https://github.com/code4recovery/12-step-meeting-list/issues

**Screenshots**
[https://github.com/code4recovery/12-step-meeting-list/issues](url)
<img width="266" alt="Screen Shot 2020-10-11 at 10 25 28 AM" src="https://user-images.githubusercontent.com/55007577/95686614-f2392f80-0bcc-11eb-9362-ab6699a6deb8.png">

**Desktop (please complete the following information):**
 - OS:    MAC
 - Browser  safari
 - Version 10.15.7

**Comment by tech2serve** [comment]
In 3.9.0
