### ISSUE TITLE
Google Maps Showing Wrong Address

### ISSUE THREAD

**Issue by technologynhaa** [code4recovery/12-step-meeting-list#188]
I am not sure if this is an issue with TSML, but any group using the address found below yields the wrong address in Google Maps Directions:

https://nhaa.net/meetings/sisters-in-sobriety-group-2/?tsml-day=1&tsml-region=manchester

This is what it ought to be:

https://www.google.com/maps/place/695+Mast+Rd,+Manchester,+NH+03102/@42.9929711,-71.5069354,17z/data=!3m1!4b1!4m5!3m4!1s0x89e2491e50f7e333:0x5772a9514bcdde9b!8m2!3d42.9929711!4d-71.5047467

**Comment by tech2serve** [comment]
Hmmm. Well, I tried both your links and they went to the same place for me:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/31904316/96376062-6bdb9b00-1142-11eb-8959-e12fa043041d.png">

Also, do you get routed to the wrong location if you use your phone to get directions?

When I've seen issues with directions going to the wrong place, even though it looks correct in TSML, the problem has been with Google. You can submit the issue to them. 

You also might have some luck with with [this override option](https://github.com/code4recovery/12-step-meeting-list/wiki/Frequently-Asked-Questions#i-need-to-correct-a-meeting-address-or-change-a-pins-location) from the [plugin's FAQ](https://github.com/code4recovery/12-step-meeting-list/wiki/Frequently-Asked-Questions)

**Comment by technologynhaa** [comment]
Thank you for the very fast response!  When I do the following:


   1. Navigate to https://nhaa.net/
   2. Choose NH MEETINGS->NH MEETING INFO & DOWNLOADABLE LISTS
   3. online meeting list
   4. Select "Manchester" as Location
   5. Click Primary Purpose Group
   6. Click Directions

It sends me to
https://www.google.com/maps/dir/Highlands,+Manchester,+NH+03103/42.9929711,-71.5047467/@42.9730552,-71.5147191,13z/data=!3m1!4b1!4m8!4m7!1m5!1m1!1s0x89e24ea4c1a2ef29:0xb00908d3677b4c6!2m2!1d-71.4625883!2d42.9572735!1m0

Interestingly, it works on my iPad.  I did the above on a Chromebook.  Any
ideas?  I am sorry, I could not follow what I would need to do on the
override option.  This looks like code and I am not sure where to modify.
I will also pursue the Google support route.

**Comment by tech2serve** [comment]
Is this marker at the correct location?

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/31904316/96376889-279ec980-1147-11eb-8aec-ee2ae0147157.png">

**Comment by technologynhaa** [comment]
Yes, it is correct.

**Comment by tech2serve** [comment]
Ok, so that is the location to which I get directions using two different browsers on my MacBook. I've used Safari and Chrome. 

If the only device you're getting incorrect directions with is the Chromebook, can you try resetting the cache on it? Does the Chromebook provide you your correct location?

**Comment by technologynhaa** [comment]
Very strange.  I tried both Safari and Chrome on my MacBook and get the
same results as the Chromebook.  I Cleared Browsing Data on all to know
avail.  The destination comes up as Pinardville, Manchester, NH and current
location comes up as Highlands, Manchester, NH.  Neither of these are
correct.  Do you know where location services are configured?

**Comment by tech2serve** [comment]
That is bizarre. Frankly, checking your location was kind of a long shot that I think just went away. But, something is causing you to see different results that me.

Try the Meeting Guide app from your phone or iPad and tell me if you get the correct directions then.

Also, when you request directions through TSML, are you logged into Wordpress? If so, can you try logging out as if you were a normal everyday user, and see if you get directions to the correct location then?

**Comment by technologynhaa** [comment]
Sorry...just picking this up again.  The Meeting Guide app works fine on
iPhone and iPad, though it is a slightly different process in that I have
to select which Mapping App I use.  Google works.

It is the same behavior when logged out of our site.  How may we debug?

**Comment by tech2serve** [comment]
Will you please attach a screen cap of the location you get by directions that is wrong? And another screen cap of what is the correct location? I want to be certain that I am seeing this correctly.

**Comment by technologynhaa** [comment]
I think this may have resolved itself.  It may have been an issue with
Google Maps.  Thank you for your help.

**Comment by tech2serve** [comment]
I love it when a plan comes together.
