### ISSUE TITLE
Meeting Import CSV - Import Methodology to "Update" Exisiting Meetings

### ISSUE THREAD

**Issue by CCFAAWebmaster** [code4recovery/12-step-meeting-list#190]
**Describe the bug**

>> This may be PEBKAC  <<  

We have 3 methods to import csv files to TSML
 A = don't delete anything
 B = delete only the meetings, locations, and groups for the regions present in this CSV
 C = delete all meetings, locations, groups, districts, and regions

This may not be a bug 
Q = Is there an ability to import and only update the (imported) meeting data?

**To Reproduce**

When importing properly formatted TSML csv file, 

A = don't delete anything 
<< Use case = Import .csv all new meeting data.
<< If used properly, slam in a bunch of data for new meetings. Nifty 
<< If used "improperly", creates 2 of same meeting except where updated field(s). Not Nifty
 
 B = delete only the meetings, locations, and groups for the regions present in this CSV 
<< Use case = Import .csv for some meetings
<< If used properly, (?) ex. import a (single) meeting & delete same (single) meeting, Nifty
<< If used improperly (?) ex. import a (single) meeting & delete entire Region. Not Nifty 

 C = delete all meetings, locations, groups, districts, and regions
<< Use case = Remove all meetings, submit clean import
<< If used properly, nuke all meeting data and import all new meeting data. Nifty
<< If used improperly, nuke all meeting data+ import fails,  Not Nifty 

**Expected behavior**
For sake of argument, I get Options A & C.
I am less clear on Option B. My mistake (may be simple lack of understanding of use case) is that the imported file was for a single meeting (update) an I nuked an entire region. I was able to re import from backup using Option A as I had nuked the region ;)

**Additional context**
Q = Is there an ability to import and only update the (imported) meeting data?

Q1 = If I new the Meeting Key (field) column, maybe I import the key + only changed field? 
A1 = No, if region (field) is null, all meetings will null region would be deleted.

Q2 = To edit a single, few meetings using the import tool, maybe I should take a full export, edit and import using C
A2 = No, that's a headache and may cause more issues than needed.

Q3 = To edit a single, few meetings do not use the import tool.
A3 = Yes of course, as needed use the front end and not import. Save import for en mass. Hence the basic question on how to simply just update (overwrite)

Most grateful for your continued hard work on TSML. Really a plugin gem.

Humbly submitted,

- Pete B.

**Comment by tech2serve** [comment]
Hi Pete (@CCFAAWebmaster)--

>  am less clear on Option B. My mistake (may be simple lack of understanding of use case) is that the imported file was for a single meeting (update) an I nuked an entire region.

As I look at this, I sure can't fault you for being confused :-). But yeah, **B** is giving the user the option to replace data in  the database for a region. The other options are basically, "Hey, let's add a bunch of meetings to the current database" (**A**) or "I want to replace the entire database with this new set of meetings" (**C**).  

I believe it is useful to understand the intent of the csv imports. The feature is more designed for when someone is setting up a new site or recovering a lost site/database. And **B** in particular is useful if someone is building a site for a large metro area, and they had been tracking the data by Region. Say if they had three regions, they would import three different csv files to set up their site.

Although some people are tracking and making changes in a spreadsheet for routine management of meetings, and then importing using **C** (or **B** if you have multiple spreadsheets by region), my personal experience is that this approach tends to lead to problems: First, tracking versions of spreadsheets is more difficult; Second, the importer doesn't always get updated as quickly as other parts of the plugin; Third, there just seems be more conflicts with data or fields in files coming from certain spreadsheet programs. 

To more succinctly answer your question: there is no way to use the importer to only update the changed data without risk of deleting other data. 

I believe the best approach is to use the Meeting Edit page to change individual meeting, group and location data. Leave the spreadsheet for recovery and setup.

**Comment by tech2serve** [comment]
Hi @CCFAAWebmaster,

Is there anything else I can do to help you with this issue?

**Comment by CCFAAWebmaster** [comment]
Good to close >>> Thanks for all the extra efforts
