### ISSUE TITLE
What is best plugin backup to insure TSML data restore?

### ISSUE THREAD

**Issue by CCFAAWebmaster** [code4recovery/12-step-meeting-list#191]
**Is your feature request related to a problem? Please describe.**
Apologies if this is not a Feature Request, more like a General Question.

We are reviewing our website Backup / Restore structure & want to insure TSML is properly set for Backup AND Restore.

We run Backups as follows:
Weekly - Linode 
Weekly - WP Plugin = UpdraftPlus Backup/Restore (Free)

I dug around on UpdraftPlus. UpdraftPlus does not backup TSML.

**Describe the solution you'd like**
Q1 = Can we run all backups as needed AND still have a TSML Backup on the side?
A1 = Assume yes, this would be optimal. That way as needed we can restore just what we need.
Q2 = What is best plugin to insure TSML data Backup?
A2 = ??
Q3 = Is this just a matter of exporting several files manually and calling it a day?
A3 = Yes, export meetings and filename.??? 
Q4 = Is this just a matter of finding a "better" Free Backup Plugin OR please no ... spending $?
A4 = ??

See Q's 1-4 above

**Describe alternatives you've considered**
See Q's 1-4 above

**Additional context**
So as to insure we have tested a good clean backup / restore, we are cloning the site so we can play around with this more. 

As always you all rock.

Best to you in safety, good heath and peace.

- Pete B.

**Comment by tech2serve** [comment]
> I dug around on UpdraftPlus. UpdraftPlus does not backup TSML.

TSML does not create it's own tables, so any solution that backs up your entire Wordpress database will also cover TSML. Using any decent Wordpress backup service plugin is a good idea.

The other step I recommend is related to your previous question ( #190 ). A common use of csv files after you've set up your site is to create off-site backups of your TSML meetings. After you've updated all of your meetings, click on Import & Settings, and then download in "CSV format"

<img width="277" alt="image" src="https://user-images.githubusercontent.com/31904316/96523591-b2f98700-123b-11eb-9453-1396222767aa.png">

**Comment by CCFAAWebmaster** [comment]
<><><>
We run Backups as follows:
Weekly - WP Plugin = UpdraftPlus Backup/Restore (Free)
This backup includes full WP db. So we may be fine here
<><><>
Q3 = Is this just a matter of exporting several files manually and calling it a day?
A3 = Yes, export meetings and filename.???
>> We already do this so we may be in an ok position.

Thanks for the assist as always.
