### ISSUE TITLE
Testing Beta Version 3.9.0b - Need to Save permalinks

### ISSUE THREAD

**Issue by EverettReef** [code4recovery/12-step-meeting-list#193]
I installed the update from 3.80 to 3.9.0b on my test and home group websites. Before I could get to my meetings page I had to go in to Settings, Permalinks and save changes. Otherwise I was getting a page not found error. 

The issue was the same if I deactivated the 3.9.0b version and activated the 3.8.0 version.

This is my first time testing, so this may be expected behavior, but I thought I'd point it out.

**Comment by Grateful-Viv** [comment]
Had same experience. Didn't need to change anything, but needed to SAVE CHANGES for meeting list to open.

**Comment by tech2serve** [comment]
Thank you both. I didn't have to do that, and I'm not sure why. 

Now it has me wondering if this is related to how we installed the version. Did you both deactivate the 3.8.0 before installing 3.9.0b?

**Comment by Grateful-Viv** [comment]
Yes. Followed instructions as written.

**Comment by EverettReef** [comment]
I have a third site that I tested again this morning. Same result. I had to save permalinks before I could see the meetings. I was very careful to deactivate the plug-in before beginning the installation of the 3.9.0b version.

 

I used the ZIP file that I received from Tim via email. I am not sure that makes any difference.

 

One the three sites, the php versions are 7.2, 7.3, and 7.4 if that matters. Two if the site are running WP version 5.5.1 and my test site is running version 5.3.2 Any other site information I can provide, I am happy to do it.

 

-Bruce

**Comment by tech2serve** [comment]
Who is your hosting provider?

**Comment by EverettReef** [comment]
One is HostGator, one is SiteGround and the final one is running on a Synology NAS in my house.

**Comment by EverettReef** [comment]
I download and installed the new update (3.9.0b1), this solved the problem on me.

**Comment by Grateful-Viv** [comment]
restored backup to original, uploaded 3.9.0b1, opened meeting list perfectly. this is now resolved. thank you.

**Comment by tech2serve** [comment]
I'm going to close this issue then. Thank you both for testing again.
