### ISSUE TITLE
BETA Test v3.9.0-rc

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#198]
After activation, version reports as same as previous one (3.9.0b1). Made sure to deactivate previous version. After testing. see no discernable difference. Please verify version  is correct in 12-step-meeting-list-3.9.0-rc.zip  Thanks. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment]
Yeah. The release candidate got bungled. I just created a new one and sent out an email.
