### ISSUE TITLE
Modeling TSML Plugin Like AA SF/Marin

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#202]
This feature is not related to a problem, but I see there is already a solution designed and published. Wondering how close is the TSML plugin update coming along to function like the AA SF/Marin site (see https://aasfmarin.org/meetings)?

This version has in List View the Address renamed as Address / Platform and displays a graphical depiction in this field (as well as a street address if it is an in-person meeting).

![AA SF Meetings List](https://user-images.githubusercontent.com/62247421/97767879-8d9b3180-1af5-11eb-89b7-1b9562e01001.png)

Drilling down to the meeting displays the Zoom ID (and Passcode if it exists) under the Zoom Graphical Link. Under the Phone link, it displays Dial-in number, Meeting ID and PIN. It also does not display a map if it is a remote meeting only, though it gives a geographical location (SF / Marin County, CA, USA) to function with the Meeting Guide App.

![AA SF Meetings Info](https://user-images.githubusercontent.com/62247421/97767954-f7b3d680-1af5-11eb-8d3e-069da093d1e7.png)

If there are multiple meetings at same location, instead of showing text that says xx amount of meetings at this location, it actually lists the day, time and link to each meeting. 

![AA SF Meetings Location Info](https://user-images.githubusercontent.com/62247421/97768032-8fb1c000-1af6-11eb-9252-787a3b03ad4e.png)

**Comment by tech2serve** [comment]
We are discussing approaches to the front end, including some modifications to better support online meeting. 

We have not decided what route we will take, but it is being worked.

**Comment by tech2serve** [comment]
@Grateful-Viv, 

Are you looking for something like [South Eastern Pennsylvania Intergroup](https://www.aasepia.org)?

**Comment by Grateful-Viv** [comment]
I'm looking  for something like what SF/Marin has which I believe is a modified version of the TSML plugin on the WordPress platform. I don't think SEPIA is running on WordPress.

What I particularly like about SF is that it is not showing suspended meetings that are not online by default. In fact, I don't even see this as a type to choose from. 

I like the dropdown for type of meeting shows a number next to it (this is both sites).

If it is not possible show filter out temp closed meetings, the crossing out the address in the list view, as well as adding "temp closed" in the map when looking at meeting detail is preferred (SEPIA does this). 

On both sites, I do like the graphic images in list view, though I do prefer the darker ones on the SF site.

Which direction is Code For Recovery going in with all this?

**Comment by tech2serve** [comment]
SEPIA is running a new front-end based on ReactJS that some of our members are developing. And a shortcode has been developed for TSML so that this can be used in place of the existing WordPress meeting list on the front-end. 

I'm going to at some point work on directions for people, but in theory it should be pretty simple. Add the shortcode `[tsml_react]` to a page on your site and link a menu to it. That is the theory.

If you wish to experiment, be our guest. I'd also be happy if you wrote up and steps or hiccups and emailed them to us. 

After knocking down a couple more bugs, I do plan to do some more work with TSML and how we handle attendance options for meetings (in-person, online only, hybrid).

**Comment by Grateful-Viv** [comment]
Very cool! I do have comments to add and wonder if I should email them as you suggest above, or capture them in here.

Thank you.

**Comment by tech2serve** [comment]
In this case, unless they're clearly a bug or feature request related to TSML (as it exists today), please email me.

**Comment by lovethecodelabs** [comment]
Is there a contributor git site for the React TSML App?

**Comment by tech2serve** [comment]
I'm not clear what you're asking. There isn't really a "React TSML App". There is a react-based front-end/app (basically,  the link you put there is it) that can be be used with TSML as a shortcode. 

So if you want to contribute to the react-based app, please fork the project you linked (Be advised, I'm hoping to change the name of that repo to more accurately reflect what it is in the near future). If you want to experiment and write documentation for the the shortcode in TSML, probably best to use this project site.

Hopefully that makes sense.

**Comment by tech2serve** [comment]
Adding this to TSML v4.0 milestone which involves implementing the [TSML-UI front end](https://github.com/code4recovery/tsml-ui) in place of the legacy Wordpress front-end.

**Comment by Grateful-Viv** [comment]
What about the Wordpress plugin? Is this going to be phased out? I sure
hope not.

**Comment by tech2serve** [comment]
The plugin is not going to be phased out. We'll just change how we provide the front end.

**Comment by Grateful-Viv** [comment]
I made a few comments and had some questions which I posted here:
https://github.com/code4recovery/tsml-ui/issues/91

If this is not the correct place, please let me know.

Thank you.

**Comment by 97eighty** [comment]
Not seeing any issues here just a list on #91. Closing this specific ticket.
