### ISSUE TITLE
Version 3.9.2 Problems

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#205]
Version 3.9.2 froze my back end on the live site. Restoring backup until I can figure it out. Refreshing permalinks was not possible since once the update was made, I could no longer get to anything in the back end.

Worked fine on the staging site however.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment]
Released v3.9.3.

**Comment by district6wc** [comment]
I just updated this plug-in and am having the same issue.  I am unable to get to wp-admin dashboard.  The webpage comes up blank.  I had to call GoDaddy and they renamed the folder for now and this deactivated the plugin.  This file contains all the meetings in my district that I entered manually.  Please help!

**Comment by Grateful-Viv** [comment]
3.9.3 has resolved the issue. Thank you!

**Comment by DCastelino** [comment]
@Grateful-Viv v. 3.9.3 resolved the error? I created a new issue on the problem with the search functionality. It also created a fatal error which prevented me logging into my dashboard.

**Comment by tech2serve** [comment]
Thanks again for the help this morning @Grateful-Viv.
