### ISSUE TITLE
Undefined Function Causing Error on Search Functionality

### ISSUE THREAD

**Issue by DCastelino** [code4recovery/12-step-meeting-list#206]
@tech2serve a recent update (I think version 3.9.2 or 3.9.3) introduced a regression on the meeting search / filter functionality.

I received this recent error with the plugin on our aatoronto.org site. I had to revert back to v.3.9.0. See below:

[Sat Oct 31 13:52:07.683654 2020] [php7:error] [pid 21989] [client 99.230.120.3:32092] PHP Fatal error: Uncaught Error: Call to undefined function db_update_addresses_cache_approximate_location() in /nas/content/live/aatorontoprod/wp-content/plugins/12-step-meeting-list/includes/admin_meeting.php:33\nStack trace:\n#0 /nas/content/live/aatorontoprod/wp-includes/class-wp-hook.php(287): tsml_admin_init('')\n#1 /nas/content/live/aatorontoprod/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(false, Array)\n#2 /nas/content/live/aatorontoprod/wp-includes/plugin.php(478): WP_Hook->do_action(Array)\n#3 /nas/content/live/aatorontoprod/wp-admin/admin-ajax.php(45): do_action('admin_init')\n#4 {main}\n thrown in /nas/content/live/aatorontoprod/wp-content/plugins/12-step-meeting-list/includes/admin_meeting.php on line 33, referer: https://www.aatoronto.org/meetings/?tsml-type=ONL
--

Please let me know if this was resolved in v 3.9.3 or if it's still an oustanding bug.

**Comment by Grateful-Viv** [comment]
@DCastelino, What were the exact steps you took that returned this error?

**Comment by DCastelino** [comment]
I didn't do anything. I had updated the plugin to v 3.9.2, and this started happening.

I couldn't login to my dashboard. We're setup on WPEngine, so the above was what I got from the error logs.

All the search functionality was broken. I had to refresh the page with the query string parameters to get my search.

**Comment by tech2serve** [comment]
@DCastelino,

Please update to v3.9.3

-------------------
Please comment to this thread with as complete of a report as possible:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by DCastelino** [comment]
Ah! Awesome! Okay, updated to v.3.9.3 and it looks like it's resolved the issue.

**Steps to Reproduce the 3.9.2 bug (if it even were a bug, or my site was caching) **
1) Go to 12 step meeting list
2) Type in search criteria
3) Hit Enter, or Select the Search dropdown "Search" option
4) Also select any option from the "Everywhere / Locations" dropdown, and/or select an option from the "Any Day" dropdown

**Expected Result**
Search results should load dynamically depending on search criteria, and dropdown selections, without refreshing the page

**Actual Result**
Search results would not dynamically load / search results would just go blank and nothing would appear

Screenshot of what was happening provided from a user:
![Capture 2020-10-31 at 13 55 31](https://user-images.githubusercontent.com/9858065/97787380-211d4280-1b88-11eb-9d03-65d2e50cd10e.png)

@tech2serve sorry...I'm a developer, and I didn't even fill out the proper clear details on the ticket earlier (facepalm)

**Comment by tech2serve** [comment]
> 
> @tech2serve sorry...I'm a developer, and I didn't even fill out the proper clear details on the ticket earlier (facepalm)

What languages? PHP and Wordpress, by chance?

-Tim
_Mediocre Developer, Expert Coffee Drinker_

**Comment by DCastelino** [comment]
Yup! I've coded a few Wordpress plugins myself. For the previous company I was working at.

I do more .NET and Angular stacks now at my current job.

I actually talked to Josh about joining the dev team for the 12 step meeting list. Do you guys have a Slack channel?

**Comment by tech2serve** [comment]
Yes, and I'm happy to add you to it if you're wanting to contribute to our efforts, especially since it sounds like you know Wordpress :-)

Please shoot an email to devs@code4recovery.org using the email address you wish to join Slack with, and I'll send you an invite.

**Comment by DCastelino** [comment]
Awesome! Email sent! Hahaha, my current employer's app uses a combination of server-side javascript/.NET, which is so similar to PHP. That was back from when everyone wanted to make their own proprietary languages.

I talked with Josh, and now that my time is freeing up from rotating out of service commitments, I really want to start contributing to the code4recovery repo 👍
