### ISSUE TITLE
Unable to Publish Changes/New Meetings

### ISSUE THREAD

**Issue by AAEasternNC** [code4recovery/12-step-meeting-list#210]
Hello,

I am the website admin for the AA District 60 group covering eastern NC and need some help with the Meeting Guide app please. The app is updated to the most recent version and still has the same issues as before. When I try and make changes/additions to certain meetings like the times, dates, etc. the app does not allow for me to publish the changes but only remains in draft mode. Please see the screenshots below of the Beaufort County Group attempted changes. We have over 100 meetings with many needing updating recently due to the COVID-19 situation.
Any help would be greatly appreciated and most of the meetings are outdated now and the website gets about 1,000 hits per month seeking details about meetings. Attached are some screenshots for your review.

![screenshot 1](https://user-images.githubusercontent.com/74005338/98253372-f1d05200-1f48-11eb-9d33-742360359aae.png)

![screenshot 2](https://user-images.githubusercontent.com/74005338/98253326-e0874580-1f48-11eb-925a-18cb23d93710.png)

![screenshot 3](https://user-images.githubusercontent.com/74005338/98253337-e5e49000-1f48-11eb-8f13-4f200627fee3.png)

Thank you. James Smith 
919-610-5310 cell
AADistrict60@gmail.com  email

**Comment by tech2serve** [comment]
To help our continued education efforts, you're talking about the Twelve Step Meeting List Plugin for Wordpress, and NOT Meeting Guide. Meeting Guide is the mobile app on our phones and it is managed by GSO.

Now, to your issue, please make sure you've updated to the latest version of TSML.

Please tell me what version of Wordpress you have installed. If you have not updated to v5.5, hold off.

If you are using Wordpress 5.5 or later, or don't want to hold off on updating, you should install and activate another plugin called `Enable jQuery Migrate Helper`. Once those steps are done, please try changing the meeting again.

You may see some warnings on the meeting edit page after you install `Enable jQuery Migrate Helper`. You can safely disregard them.

If your problem persists, tell me if you're using Google or Mapbox for maps. And confirm the MapBox key is valid.

Let me know...

**Comment by AAEasternNC** [comment]
Hello,

Today i contacted tech support with GoDaddy regarding the Meeting Guide
Wordpress plugin and was informed that we are already using version 5.5.3
of the plugin. The tech support person reached out to some colleagues and
nobody knows what TSML is and they do not support it. However, they did
manage to add the plugin for the jQuery Migrate Helper. Lastly, we are
using Google for maps.
Since the problem remains the same is there anything else you can do to fix
the problem? Would it help if I were to just reacreat the Meetings page
with 106 meetings and reinstall the app? Lots of work but if it would fix
the problem then I can do it.

Thanks, James Smith (Web Admin) 919-610-5310 cell

**Comment by tech2serve** [comment]
TSML is short for Twelve Step Meeting List which is the name of the Wordpress plugin you're using to manage meetings.

Please open a developer console so you can watch for errors. Does a map show up of your meeting location after you enter a valid Address?

My lead suspicion is that something in another plugin is creating a conflict. Please disable your other plugins, especially those that are changing the Edit Meeting page (like Yoast SEO?). and see if your problem is resolved.

**Comment by Grateful-Viv** [comment]
@AAEasternNC - from the screen shots, it doesn't look like you entered a day and time for your meeting. It has doesn't look like you entered a street address for the church which won't publish unless it is an online meeting.

**Comment by AAEasternNC** [comment]
I've ttied entering the address, etc. but it wont save/publish. That's the
entire issue I'm having...can't modify any meetings.

Thanks, Jamez

**Comment by tech2serve** [comment]
@AAEasternNC, have you tried the things I suggested? In particular, opening a developer console and looking for errors? And disabling all other plugins to see if that resolves the issue?

**Comment by tech2serve** [comment]
@AAEasternNC,

I'm quite confident that whatever is causing the errors shown here is interfering with TSML geocoding addresses for the meetings. 

![image](https://user-images.githubusercontent.com/31904316/99441214-319a2080-28dd-11eb-9c8f-53ffce22468e.png)

Disable the other plugins, or otherwise resolve those issues, and I suspect the publishing problem will be corrected.

**Comment by AAEasternNC** [comment]
Hello,

Just an update to the probleem whiiich stiill  exists after trying thee following...

Disabled all plugins except for JQuery Migrate Helper
Updated all themes, plugins
Wordpress is set to auto-update

Google Maps is not populating the maps when I add addresses in the Location Information block
The publish button goes gray after i anter any address details

![image](https://user-images.githubusercontent.com/74005338/101058821-9307f380-355b-11eb-8994-cd594d7b18ef.png)

Today I am able to publish changes to meeting times, dates which is an improvement.
I'm thinking the Yoast SEO plugin is not working or something?
My knowledge is limited as i'm now a developer or familiar with JSON scripting.

Any further suggestions would be appreciated.

Thank you. 

James Smith 
919-610-5310 cell

**Comment by tech2serve** [comment]
You can safely ignore the warnings for now. Over the next few days I hope to release a version that will address our compatibility with Wordpress 5.6 (being released soon). For now, I'm going to suggest people don't update their Wordpress further.

I have seen people experience issues with Yoast SEO plugin.

In #208, I suggested that some sites are experiencing issues (and I an occasionally duplicate this) where the geocoding needs to be triggered again before the Update button will activate. The easiest way to address this is to return to the address field and remove the "A" in "USA". Then hit tab to trigger the geocoding. See if that causes the map to load up. 

If not, are you experiencing this issue with all addresses or only some?

**Comment by AAEasternNC** [comment]
Thanks for the update. I will try your suggestion and yes, the problem
occurs with all addresses.

James

**Comment by tech2serve** [comment]
BTW, I just looked at your site and you're still getting the error I mentioned above. I really think you need to resolve this:

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/31904316/101067292-fe9e9080-355c-11eb-89cb-adf8f406f6b5.png">

This is not a TSML issue. This is an issue with your API key, or your site's ability to communicate with Google.

**Comment by AAEasternNC** [comment]
Should I perhaps creat a new API key?

**Comment by tech2serve** [comment]
I didn't study it closely. But on the surface, the issue appears to be your Google API key in which case it could be something with the key itself. I would start with logging into your Google Console and checking for errors and restrictions on the key which are preventing it from working. I also think there are cases where Google may invalidate the key if the billing information is clearly out-of-date, but I don't know that for sure. Generating a new key may or may not be necessary.

Another approach is to use Mapbox which would help narrow down the issue.

**Comment by AAEasternNC** [comment]
Thanks!!!   Instead of using the Google API I tried Mapbox and now it works
great.

James
