### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by Web-R88** [code4recovery/12-step-meeting-list#211]
**Describe the bug**
Contact information on a smart phone is not the good one. If we ask for contact information near home, we have a false info for Région 88 Sud-Est du Québec: webmestre88@aa-quebec.org which is the old contact. Now we use : webmestre@aaregion88.org. The web site info is OK.

**Expected behavior**
use the new contact information

**Screenshots**
Showing what we have on our web site (desktop) showing the good info
![contact mG](https://user-images.githubusercontent.com/62248556/98401322-7d261200-2033-11eb-9a43-01c943d40768.jpg)

**Smartphone (please complete the following information):**
 - Device: samsung S20 Ultra 5G
 - OS: android
 - meeting guide

**Additional context**

**Comment by tech2serve** [comment]
When you say "on a smart phone", do you mean in the Meeting Guide app?

**Comment by Web-R88** [comment]
Yes when we use the Meeting Guide application from drummondville, for exemple, at the buttom of the screen we have Contact button. Clicking on it, we have false email contact = webmestre88@aa-quecec.org Now we use email= webmestre@aaregion88.org. Thank you
 
Amour et Service
Raoul C.
Webmestre https://aaregion88.org
 
courriel: webmestre@aaregion88.org
 

 
 
 
De : Tech2Serve <notifications@github.com> 
Envoyé : 6 novembre 2020 13:38
À : code4recovery/12-step-meeting-list <12-step-meeting-list@noreply.github.com>
Cc : Web-R88 <web-r88@aaregion88.org>; Author <author@noreply.github.com>
Objet : Re: [code4recovery/12-step-meeting-list] Contact information (#211)
 
When you say "on a smart phone", do you mean in the Meeting Guide app?

**Comment by tech2serve** [comment]
Please contact appsupport@aa.org. GSO controls the information provided in the Meeting Guide app. 

If after you talk with them, you still need help, please come back and let me know and we'll figure something out.
