### ISSUE TITLE
Want to query to display certain meetings

### ISSUE THREAD

**Issue by indelg1** [code4recovery/12-step-meeting-list#212]
Simple question I hope.  I have a query to separate records from the Meeting room database.  This is what I put into my WordPress site: **https://sca-recovery.org/WP/meetings/?tsml-day=any&tsml-type=ONL

This is fine if I want records where the type is equal to ONL.  I would like to construct a query that gives me everything NOT equal to ONL.  I tried "<>"  but that does not seem to work in WordPress.  Is there another symbol for NOT Equal I can use?

Thanks for your help.

Greg

**Comment by tech2serve** [comment]
Regrettably, Wordpress doesn't support that type of search.

We will be working on some changes for how we handle attendance options (i.e., in-person, online only, hybrid), but not promise on a timeline.

I'm going to close this under the assumption I've answered the question (even if it isn't what you were hoping to hear :-) ).
