### ISSUE TITLE
Add a New Meeting Type for "In Person" or Face to Face"

### ISSUE THREAD

**Issue by indelg1** [code4recovery/12-step-meeting-list#215]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way for me to separate out our current "Face to Face" meetings from our new Virtual meetings.  Since we have to include an address for all meetings, it can be confusing to those viewing the database.  Some believe the meetings are hybrid meetings where they can use Zoom or come in person.  We do not have the capability of having hybrid meetings so we do not want to give people the impression we can do that.

**Describe the solution you'd like**
If we had a meeting type that was called "In-Person" or "Face to Face", we could classify all meetings that meet in a brick in mortar location and separate them out onto a separate list and label the list "In-Person Meetings".  The hope is that this would be clearer to those searching for a meeting that fits their needs.  They would pick the In-Person list on our website and be sure all meetings on the list are actually available for an in-person experience.  A new meeting type for "Virtual" meeting would also be helpful as well because we would not have to have a Region called Zoom, which is also a bit inaccurate

**Describe alternatives you've considered**
I have tried to create a query that excludes Region, but I am told that a "Not Equal" type of query is not possible.  I put all Zoom meetings into a region called Virtual and figured if I just excluded the virtual meetings, I would have a clear list of "In-person" meetings, but the inability to construct the proper query made that solution unworkable.  

**Additional context**
I think if we can easily separate the In-Person meetings from the Virtual meetings and display a list easily and separately of each, it would minimize the fact that all of our current virtual meetings must have addresses and reduce the amount of confusion by our members.

**Comment by tech2serve** [comment]
We have a different approach we intend to implement. We do not plan to add more types.

**Comment by tech2serve** [comment]
I should add that you are welcome to add your own custom types. Please see the FAQ on the Wiki page.
