### ISSUE TITLE
Cant publish and maps not working

### ISSUE THREAD

**Issue by rs0715** [code4recovery/12-step-meeting-list#217]
Just installed the plugin on a godaddy platform and no publish button, i installed jquerry and deactivated yoast... no luck

also no google maps after entering api key

**Comment by tech2serve** [comment]
If, after you've installed the "Enable jQuery Migrate Helper" plugin (not the same as installing jQuery which is already installed with Wordpress), and a valid API key (either Google without restrictions, or Mapbox), if you're still not seeing a map appear after entering a valid address, then you should disable all other plugins, open a debugging console (depends on the type of browser) and try to capture any errors.

Interesting this is the second report from a GoDaddy user.

**Comment by rs0715** [comment]
Got both working - thx - after i add all the mtgs how do i get them on a page?

**Comment by tech2serve** [comment]
See [this entry](https://github.com/code4recovery/12-step-meeting-list/wiki/Frequently-Asked-Questions#where-are-my-meetings-listed) in the FAQ which then provides you the link to the meetings. 

Make that link an entry in a menu item.

**Comment by rs0715** [comment]
Since it doesn’t create pages in the pages section, how can I edit the list or the meeting pages to tie them in with my theme?

 

Sincerely,

Richard Speigel

Phone: 856-305-1796

 <http://www.datarightservices.com> www.datarightservices.com

**Comment by rs0715** [comment]
Also the get directions function seems to have disappeared

 

Sincerely,

Richard Speigel

Phone: 856-305-1796

 <http://www.datarightservices.com> www.datarightservices.com

**Comment by rs0715** [comment]
Any ideas on the get directions issue?

**Comment by tech2serve** [comment]
What is the link to your website?

**Comment by rs0715** [comment]
http://bgf.26d.myftpupload.com/

 

 

Sincerely,

Richard Speigel

Phone: 856-305-1796

**Comment by tech2serve** [comment]
I'm now seeing a potential common thread between this and what #208 evolved into (@marcesher, @marcinyorkpa). 

This afternoon or tonight, I'll try to patch a more robust check of approximate value and get it to you and others for testing.

**Comment by rs0715** [comment]
Great thx

 

Sincerely,

Richard Speigel

Phone: 856-305-1796

**Comment by tech2serve** [comment]
@rs0715, what version of PHP is your website using?

**Comment by rs0715** [comment]
7.3

 

Sincerely,

Richard Speigel

Phone: 856-305-1796

 <http://www.datarightservices.com> www.datarightservices.com

**Comment by tech2serve** [comment]
@rs0715 I'm closing this as it now duplicates #208. Please follow that issue for updates and continued discussion.

**Comment by rs0715** [comment]
I read thru 217 and it looks like you are narrowing down the issues – to add further detail, I have disabled the jquerry and re-enabled yoast, and on or off the get directions is still not present.

 

Let me know if you need anything from me to aid in a solution.

 

Sincerely,

Richard Speigel

**Comment by tech2serve** [comment]
Please see my last comment in #208. I'm continuing to try to consolidate information to try and determine what is different about your sites. Thank you.
