### ISSUE TITLE
Seems to be stuck at 79% syncing

### ISSUE THREAD

**Issue by volaer** [code4recovery/12-step-meeting-list#218]
Hi guys... When I refresh the meetings, I am stuck with 79% syncing. Is there any way for me to successfully sync it? 

Also, is there a way to automate the refresh instead of manually clicking the button, it will automatically sync at the background let's say every week? 
![Screen Shot 2020-11-12 at 4 44 30 PM](https://user-images.githubusercontent.com/11605367/98917737-b49b2f80-2507-11eb-92aa-b2e15719b806.jpg)

**Comment by tech2serve** [comment]
Hey @volaer —

At first blush, this appears to be something conflicting on your site. Please start by opening a debugging/JavaScript console so you can monitor for errors while running tests. 

Disable other plugins to see if the problem persists.

If you’re running Wordpress 5.5, please ensure you have the Enable jQuery Migrate Helper plugin installed and active.

Clear your browser cache. And if you have access to website cache, clear that as well. 

Report back with your findings and we’ll go from there.

There is no automatic update process. A friend in Europe developed the potential capability but then he disappeared, and we’ve not been able to get it to work. And unfortunately, none of us seem to have time to focus on it right now.

**Comment by volaer** [comment]
Hi tech2serve, 
It is still stalling at 70% + here's the snapshot of the console. 
![Screen Shot 2020-11-14 at 8 35 26 AM](https://user-images.githubusercontent.com/11605367/99133351-955de880-2654-11eb-8348-e47912d72b5f.jpg)

I already installed Enable JQuery Migrate Helper plugin and disabled a couple of plugins. But if you try to look at the error, it looks like the server resource isn't it? Sorry, I am not a coder and very technical person that's why I need guidance.

**Comment by tech2serve** [comment]
@volaer,

To me, that error says something is wrong with your Google API key. Please check that or switch to Mapbox and see if the problem gets cleared.

**Comment by 97eighty** [comment]
@volaer 

Can you send the feed URL? I'll run it local.

The ApiNotActivatedError is defined here: https://developers.google.com/maps/documentation/javascript/error-messages

**Comment by volaer** [comment]
Hi there! 
I finally managed to finish the syncing to 100%. I tried to deactivate Events Calendar Pro plugin and it finished the sync and is able to install a Mapbox API. However, here's my take I think that when it is syncing, it is using a lot of resources from the server the reason that it stalls most of the time. Deactivating Events Calendar Pro seems like easing the load of the server that's why it was successful this time. About the error, I am referring to the second error. 
![Screen Shot 2020-11-14 at 8 35 26 AM](https://user-images.githubusercontent.com/11605367/99199265-c23b0880-27d8-11eb-8ea6-a3d91ec06bdb.jpg)

If I send you the feed link can i send it privately? Sorry, I was instructed not to post it publicly.

**Comment by volaer** [comment]
Here's our website by the way: https://aawesternsydneybluemountains.org.au/

**Comment by 97eighty** [comment]
@volaer - You can send it to devs @ code4recovery . org (take those spaces out).

**Comment by volaer** [comment]
@97eighty  I already sent you the link.

**Comment by tech2serve** [comment]
@volaer Two of us tested the link and the plugin seems to be accepting the feed. I do suspect you had an issue with Google Maps that may have also contributed, but not positive.

I'm going to close this but can reopen if necessary.
