### ISSUE TITLE
Start & Stop Dates

### ISSUE THREAD

**Issue by eranstrong** [code4recovery/12-step-meeting-list#219]
**Is your feature request related to a problem? Please describe.**
I'm often given meeting schedule changes that are post dated, today i was given one to start on 12/1. I currently need to keep the request around and remember to do it, should i file it early it gets lost. On the flip side I'm given end dates for meetings as well, a fellowship lost their lease this summer and i had to remember to take it down. This would also be useful for moving of fellowships.

**Describe the solution you'd like**
I would like two nullable date fields, START DATE and END DATE, should they be null they would not effect the behavior of the meeting. However if there is a date in the START DATE field I wouldn't want that change to synchronize to The Meeting Guide app until that date, If there were a date in the END DATE field i would want it to removed from The Meeting Guide as of that date.

**Describe alternatives you've considered**
I manage it via a manual workflow - leaving requests in the inbox if i can't service them until a certain date.

**Additional context**
N/A

**Comment by tech2serve** [comment]
Hi @eranstrong,

Thanks for the idea. It is not one I've heard of before. I suspect most people create the meeting but leave it in draft.

I'm going to close this for now, but if we get a lot of people asking for it, we may revisit. And we can reopen at that time.

Yis,
