### ISSUE TITLE
Question Default to Everywhere

### ISSUE THREAD

**Issue by COMPUMEC** [code4recovery/12-step-meeting-list#220]
How can I set my meeting list to default to Everywhere when page is viewed?
Thank you!

**Comment by 97eighty** [comment]
Hi, Please add your meeting URL to the open issue.

**Comment by COMPUMEC** [comment]
http://02ba63c.netsolhost.com/clydebailey/meetings/
It is currently still being built.

**Comment by COMPUMEC** [comment]
There wont be a lot of meetings here maybe a dozen  or so.
I would like to see them all displayed on load. 
Maybe Any Day. 
What ever it takes to show all meetings.

**Comment by 97eighty** [comment]
Try this: http://02ba63c.netsolhost.com/clydebailey/meetings/?tsml-day=any

**Comment by COMPUMEC** [comment]
Perfecto! I just use this as my meeting page correct?

**Comment by 97eighty** [comment]
@COMPUMEC Yes, that will work just fine.

**Comment by COMPUMEC** [comment]
Thank you!
