### ISSUE TITLE
Is there anyway to use this plugin for our Squarespace site? Any help would be appreciated.

### ISSUE THREAD

**Issue by saludapictureman** [code4recovery/12-step-meeting-list#221]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 97eighty** [comment]
@saludapictureman At first glance SquareSpace offers a Premium offering which has the ability to create Code Blocks to add your own JavaScript. See: https://support.squarespace.com/hc/en-us/articles/205815928-Adding-custom-HTML-CSS-and-JavaScript. 

With this option you may be able to use the React interface. Instructions for setup are here: https://github.com/code4recovery/react

**Comment by tech2serve** [comment]
@saludapictureman, I had no knowledge of SquareSpace. If they have a system that allows Wordpress plugins to be used with it, you might be able to get it to work. 

As @97eighty alluded to, we have a new front end interface in development that is generally ready for people to test in limited deployments. As this only handles the front end, you'd need to use some other backend for managing the meeting data itself. Unless you're technically astute, this may not be the best option for you at this time.

If you're trying to quickly get a site up, finding a reputable Wordpress hosting service is probably your best bet. We have a lot of people report problems who use GoDaddy, so it might be best to avoid them.
