### ISSUE TITLE
Problem with determing if  location is approximate

### ISSUE THREAD

**Issue by AATimes** [code4recovery/12-step-meeting-list#223]
In the latest update, almost all our meetings have had the 'is_approximate_location' set to true so the precise map doesn't show up.

I tracked down the problem to be in the function 'decide_if_location_approximate'. It's counting the number of commas in the address returned from google maps and anything less than or equal to 2 sets the flag.

Problem here is Australia is that a valid address returned by google maps has only 2 commas. Standard addresses don't have a comma between the suburb and the state.

1 King St, Richmond, VA 23222, USA
1 King St, Richmond VIC 3121, Australia

How can we fix configure this function to work correctly for us?

**Comment by tech2serve** [comment]
Dang. We knew this was a possibility but I had hoped we'd dodged it.

Do you know, is this true across all of Australia? And what would a real approximate location look like down under? Would it be "Richmond VIC 3121, Australia"?

**Comment by AATimes** [comment]
Yes, this is the standard address format across all Australia set by
Australia Post and followed by google.
Approx addresses have only one comma - "Richmond VIC 3121, Australia"

This works:
if(!function_exists('decide_if_location_approximate')) {
  function decide_if_location_approximate($formatted_address) {
    if (substr_compare($formatted_address, ', Australia', -12))  return
(substr_count($formatted_address, ",") <= 1);
    return (substr_count($formatted_address, ",") <= 2);
  }
}

**Comment by tech2serve** [comment]
You sound like you know your way around php? We're always looking for volunteers to jump in and help maintain the plugin if you're looking for more service :-)

I'm trying to implement this while also addressing a bit of weirdness with how the rest of this feature is (or, is not) working. With luck, I'll have it to beta testers today/tonight, and released shortly thereafter.

**Comment by AATimes** [comment]
Thanks for your prompt response.

I have corrected our data now.

After the plugin update, I think the system uses the flag from google maps
to set the *is_approximate_location *flag rather than relying on
*decide_if_location_**approximate()* to decide. Is that right?

**Comment by tech2serve** [comment]
When new meetings are put in, that is correct. The next release will improve this and I believe help create a more reliable conversion from javascript to php, which I believe may be the cause of some people's problems. 

The `decide_if_location_approximate()` function is used during database updates as we improve this feature. That function will stop being used shortly.
