### ISSUE TITLE
Meetings disapear from list when removing a Data Source from Import & Settings

### ISSUE THREAD

**Issue by AATimes** [code4recovery/12-step-meeting-list#225]
Our list of meeting was initially imported from another system.

So when modifying meetings, there is always a message "'This meeting was imported from an external data source. Any changes you make here will be overwritten when you refresh the data.".

Now that we are using 12-step-meeting-list exclusively, we want to remove the entry for the Data Source in the Import & Setting page. But when I do that, all the meetings disappear from the listings (although they are still present in WP).

How can we get around this problem?

**Comment by tech2serve** [comment]
With all the data in your site, export the database to a csv by navigating to _Import & Settings_, then look over to the right by "Where's My Info"

![image](https://user-images.githubusercontent.com/31904316/99460105-e2f88080-28f4-11eb-8410-394800fbd994.png)

Export a csv of the meeting database, then delete the source. After you have a empty database, import the csv overwriting any data.

I think that should work. 

Just curious, are two sites going to manage all the meetings or are the two sites going to split them up?

**Comment by AATimes** [comment]
There is only one site where meeting data is maintained
http://meetings.aa.org.au

Which other site are you referring to?

**Comment by tech2serve** [comment]
IDK. I inferred from your desire to break the feed that were creating a new site. But I suppose you could simply be moving from one database to another. 

In any case, if the steps I gave you above are sufficient, please close this issue. Otherwise, let me know if you need more help.

**Comment by AATimes** [comment]
Thanks
