### ISSUE TITLE
Front End Submission Form

### ISSUE THREAD

**Issue by slaafws** [code4recovery/12-step-meeting-list#227]
Our Fellowship (S.L.A.A.) does not have a complete structure of Intergroups and Regions like AA does.  We have individual meetings in many places where there is no Intergroup at all.  We also have Intergroups with no website who would need to use a front end form to list their meetings with us.  

**Describe the solution you'd like**
We need a front end meeting submission form that defaults to Pending Review in Wordpress.  

**Describe alternatives you've considered**
We have looked at several event calendars for Wordpress, but they all require too much customization to make them work for our needs.

**Comment by tech2serve** [comment]
That is an interesting suggestion, but neither Wordpress nor TSML are set up for this.

My suggestion is to consider setting up a couple of trusted agents to access the backend, or use the email feature to report meetings. 

Code for Recovery will be releasing a [new product](https://github.com/code4recovery/react) (it may be available now with limited support) that is based on ReactJS vice Wordpress. This tool will make use of spreadsheets (i.e., Google Docs today) to manage and provide meetings to the front end. This may provide another option for you.
