### ISSUE TITLE
Mixed Meeting Types

### ISSUE THREAD

**Issue by COMPUMEC** [code4recovery/12-step-meeting-list#228]
Do you have a solution for mixed meeting types? 
We have a mix of NA AA Recovery and such.
http://02ba63c.netsolhost.com/clydebailey/meetings/?tsml-day=any

**Comment by tech2serve** [comment]
Not directly. The best bet is probably to create your own custom types (see the FAQ as part of the Wiki). 

Just remember that custom types will not be recognized by GSO's Meeting Guide if that is important to you.

If I haven't answered your question, we can reopen the issue.
