### ISSUE TITLE
Updating a single meeting takes almost a minute

### ISSUE THREAD

**Issue by AATimes** [code4recovery/12-step-meeting-list#229]
**Describe the bug**
When updating any meeting, it takes nearly a minute. We often get the message "Connection lost. Saving has been disabled until you’re reconnected. We’re backing up this post in your browser, just in case."

**To Reproduce**
Modify and update any meeting.

**Expected behavior**
This makes modifying meetings a tedious task. It also slows down the user experience. Needs to be quicker. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox or anything else

**Additional context**
Have tracked down the problem in the code - in the tsml_delete_orphans() function this SQL query takes over 50 seconds.

> 'SELECT g.ID FROM wp_posts g WHERE g.post_type = "tsml_group" AND (SELECT COUNT(*) FROM wp_postmeta m WHERE m.meta_key="group_id" AND m.meta_value = g.id) = 0'

Most of the time, this query returns empty. It is only relevant when a meeting is deleted or changes group.

We have 
*    2,127 meetings
*    1,401 locations
*    1,843 groups
*    29 regions

**Comment by 97eighty** [comment]
Hi @AATimes, For reference. Can you tell us a little about your hosting environment?

**Comment by AATimes** [comment]
cPanel from a local ISP on a dedicate server
PHP 7.1
MySQL Version 5.7.32

Could the MySQL version could be the problem?
I'm contacting our ISP to see if we can get that looked at.

We only recently went live using 12 Step Meetings List. We cover all meetings nation wide in Australia. We migrated our data from a 15 year old, custom built system that was becoming unmaintainable. 

Hope this is helpful.
What other information would be useful to you?

Thanks for your assistance.

**Comment by 97eighty** [comment]
Hi, The version of MySQL shouldn't be a problem. How much memory does the machine have? Have you reindexed lately? How many records are in WP_POSTS and WP_POSTMETA? - I'm trying to match locally to run some tests.

**Comment by AATimes** [comment]
I don't know the amount of memory - cPanel doesn't tell me. I'll would
need to ask the ISP

I've just done a REPAIR and OPTIMIZE on both tables. Updates are now around
30 seconds

I haven't done a REINDEX as cPanel currently won't let me.

SELECT * FROM `wp_posts`  -  records 5649 total, Query took 0.0004 seconds
SELECT * FROM `wp_postmeta` - records 22694 total, Query took 0.0003
seconds.

SELECT g.ID FROM wp_posts g WHERE g.post_type = "tsml_group" AND (SELECT
COUNT(*) FROM wp_postmeta m WHERE m.meta_key="group_id" AND m.meta_value =
g.id) = 0
MySQL returned an empty result set (i.e. zero rows). (Query took 30.5442
seconds.)

Hope this helps.
Should I contact ISP and ask about REINDEX ?

Perhaps of interest - I have a test site elsewhere on a totally different
server with a totally different ISP. Similar amount of records and it takes
around 50 seconds

Thanks again for your help.

David M

**Comment by 97eighty** [comment]
This issue is getting stale. If there is still a performance problem. Reopen.
