### ISSUE TITLE
Change Visible Phone Number To An Email Address

### ISSUE THREAD

**Issue by Mrchrisv** [code4recovery/12-step-meeting-list#231]
We have a "12 Step Hotline" phone number listed on our website, and
![20201121_082443](https://user-images.githubusercontent.com/74823227/99879541-b20d9980-2bdb-11eb-9a05-3e756d12bdae.jpg)
 that is being displayed as a contact number for the "connected site".  We would like to know  how we can change that to show an email address; "web@area15district3aa.org"
App support said it was a TSML issue.
Thanks iin advance for any help you can be.
Chris V.

**Comment by tech2serve** [comment]
Hmmm. I'm not sure I am understanding the issue well enough yet. 

Please show me a screen cap of the meeting in question on TSML, and what data fields you have filled out on the admin side. Then show me how they're being display in the Meeting Guide app. 

cc: @joshreisner

**Comment by joshreisner** [comment]
This is definitely an app support / not TSML issue, I'll let em know.

**Comment by tech2serve** [comment]
Thanks @joshreisner. It sounded that way to me too.

@Mrchrisv I apologize that you're getting a run around. I know how frustrating that is. Hopefully Josh's involvement will address the issue.

**Comment by vicspin** [comment]
I have a similar request. My email address is being pulled correctly but it has the wrong phone number, how do I update the phone number or is that pulled from a district database of some sort?

**Comment by tech2serve** [comment]
If your issue is indeed the same, and your data is correct in TSML but showing incorrect in Meeting Guide, contact appsupport@aa.org.

**Comment by vicspin** [comment]
What is TSML? Thx

**Comment by tech2serve** [comment]
12 Step Meeting List (TSML). This Wordpress plugin.

**Comment by vicspin** [comment]
Thank you for the clarification. I can't find where the phone number is set
up in the TSML is the thing but it does appear in the app. Is there a spot
in the TSML that you can set your phone number as I don't know where it is
getting the number from. - thx

**Comment by tech2serve** [comment]
For TSML, you can set meeting and group contact information. 

But, if your issue relates to what is showing in Meeting Guide App, please contact them at the email address I gave you above. We don't have any control over that.
