### ISSUE TITLE
Filtering the map view of the meeting list by excluding online meetings

### ISSUE THREAD

**Issue by mikepoconnor4** [code4recovery/12-step-meeting-list#232]
This is a suggested enhancement - but I didn't want to conflict with other ideas you have going on.

We filter the meeting list via several tsml tags to display only online or physical or either. The meeting list in list format is fine. But I'm thinking showing the online meetings on the map view could lead to confusion - that people might miss the individual meeting is online only and instead drive to the physical location only to be disappointed. Is there a way to exclude online only meetings to display in the map view? or would that be an enhancement? or does such a suggestion conflict with other directions that the plugin is going in?

I really appreciate all the work you've done on this plugin - it's a great help to all AA.

**Comment by tech2serve** [comment]
This has been discussed in other issues. Wordpress doesn't allow "exclude" in a search. So, we are looking to add additional data fields to simulate some of the same behavior.

In the meantime, with v3.9.3, locations can now be entered as approximate (city and state) and then directions won't show up in the plugin or the Meeting Guide app. If a meeting is only online, this should be the approach taken. If a meeting is in person, having a full address while simultaneously not having the meeting typed as "Location Temporarily Closed" best reflects a traditional in-person meeting. If online meeting information is added to such a meeting, the meeting should be seen has hybrid.

HTH.
