### ISSUE TITLE
Meeting Types

### ISSUE THREAD

**Issue by rs0715** [code4recovery/12-step-meeting-list#233]
What field are others using to designate if a meeting is in person, zoom or hybrid? Also is there a way to add to the list of meeting types?

**Comment by tech2serve** [comment]
Hi @rs0715, Please check the FAQ in the Wiki for how to create custom types.

Although we intend to implement a feature to track different meeting attendance options, today any meeting that doesn't have an online link or marked as TC should be considered as in person and open.
