### ISSUE TITLE
Support Topic : Changing Mapping API Keys

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/12-step-meeting-list#237]
**Is your feature request related to a problem? Please describe.**
Requesting support topic related to information on changing Google/Mapbox API Keys.  Found out that mapbox requires the "pk." prefixed key, instead of the "sk." prefixed one.  In looking throughout the site, am not seeing information related to changing out the API Key for the service.

**Describe the solution you'd like**
Instructions on where to go, what to do to change the key.

**Describe alternatives you've considered**
Another option would be information on resetting the key to the default value.

**Additional context**
This will be useful information for individuals who may be having mapping issues who need to add a different key.

**Comment by tech2serve** [comment]
Hi @jcookson-infoblox, 

I have not come across what you're describing as an issue before. My experience is that a user creates a Mapbox key and then copy and pastes that key to the field in our Settings tab. My key does prefix with `pk`, but TSML doesn't care about that. It simply stores that key and then uses it for mapping lookups with Mapbox.

Perhaps you can elaborate on how you ended up with a key prefixed with "sk" and what didn't work when you tried using it?

**Comment by jcookson-infoblox** [comment]
I logged into map box, selected the "create a token" button.  Gave it a name, selected desired scopes and clicked the create button.  I then copied that token value and pasted it into the tsml mapbox token entrypoint and saved.  I went to the create a meeting page and noticed an error occurred in the page.  When I looked at the error I noticed it referenced the token and its "sk." prefix.  I then tried to figure out how to switch out the token and have not found anything about that, hence the topic request.

**Comment by tech2serve** [comment]
Thanks for elaborating. 

I suspect the issue is in the scopes you selected. As I said, I don't believe TSML cares what the key starts with. So I believe the issue is that you set a scope restricting the type of call TSML needed to make to Mapbox. 

If you have language (a sentenced or two) you think could be added to the FAQ (perhaps under Installation?) I'd be willing to consider adding it. Frankly, this hasn't been an issue in the past. I suspect most people just take the default scopes/settings provided by Mapbox.

**Comment by jcookson-infoblox** [comment]
That may be the case.  I did create an API key for what I thought would be utilization from the site, so we may want wording that indicates to just utilize the default public key offered by the site as it have basic needed privileges for what we are trying to accomplish.  Other than that, can you suggest best course of action for changing key to default public key?

Language suggestion, "Please copy and paste the key shown in the user profile screen which begins with the 'pk.' prefix, it should be easily shown and copyable from the main profile screen.  Note: TSML's map box integration looks for this key specifically and if not will return an error referencing incorrect key.  Unless the account holder has knowledge of scopes and permissions for map box and their integration points within the TSML application, it is best to utilize the public key offered (hence 'pk' prefix)."

**Comment by tech2serve** [comment]
Ok. I'll look at something like that. I am not convinced the prefix is relevant. Again, TSML just cares that the key is there so it can be presented to Mapbox.

I'm thinking simply an addition that says: "NOTE: Unless the user has knowledge of Mapbox scopes and permissions, it is best to stick with defaults options when creating the key."

Is that a clear enough warning?

**Comment by jcookson-infoblox** [comment]
Sorry about the lag.  Got a new service position, Area 72 Webmaster.  aLanguage is perfect, thanks.

**Comment by 97eighty** [comment]
This issue is stale. Reopen if still an issue.

**Comment by tech2serve** [comment]
This may be a minor word tweak @donwatkins could address.

**Comment by donwatkins** [comment]
What can I address @tech2serve ?
