### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by COMPUMEC** [code4recovery/12-step-meeting-list#240]
Hello, Is there a way to remove the top bar with all the buttons as well as remove the columns Location, Address and Region?
Thank you for all you do!
![1](https://user-images.githubusercontent.com/37122057/100799390-f6c2dd00-33f2-11eb-9de4-685f989f0304.jpg)

http://02ba63c.netsolhost.com/clydebailey/meetings/?tsml-day=any

**Comment by tech2serve** [comment]
Seek the FAQ under the Wiki. It covers how to override pages.
