### ISSUE TITLE
Help Importing CSV

### ISSUE THREAD

**Issue by technologynhaa** [code4recovery/12-step-meeting-list#241]
I do not know if this is a bug or not, but the attached will not upload and produces no errors in the console.  I have checked the data against the specifications and am unable to see any non-compliance.  What shall I do?

[meetingdata.csv.zip](https://github.com/code4recovery/12-step-meeting-list/files/5629664/meetingdata.csv.zip)

**To Reproduce**
1. In a WordPress site with TSML installed, go to Meetings->Import & Settings
2. Click on 'Choose File' and select the attached unzipped file
3. Click 'delete all meetings...'
4. Click 'Begin'
4. What it has become:

**Expected behavior**
When the import works, a progress bar appears and the meetings load up.  I would also expect districts to populate since we added that data

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser Chrome
 - Version Version 86.0.4240.198 (Official Build) (x86_64)

**Comment by tech2serve** [comment]
The file uploaded fine on my system using Safari. I didn't try on Chrome. Shows bunched of districts.

Keep looking at your site. Something is causing issues.

**Comment by technologynhaa** [comment]
I will try on Safari

**Comment by technologynhaa** [comment]
I think I found the problem.  For some reason, there are two instances of
functions.php in the public.html and stage.nhaa.net folders.  I commented
out the preprocessing code in the other file and it is working now, though
it seems to stop at 25 meetings.  Did your import get all the way through?

**Comment by technologynhaa** [comment]
I am getting these errors in the console:

JQMIGRATE: Migrate is installed with logging active, version 1.4.1
jquery-migrate-1.4.1-wp.js?ver=1.4.1-wp:56 JQMIGRATE: jQuery is not
compatible with Quirks Mode
migrateWarn @ jquery-migrate-1.4.1-wp.js?ver=1.4.1-wp:56
jquery-migrate-1.4.1-wp.js?ver=1.4.1-wp:58 console.trace
migrateWarn @ jquery-migrate-1.4.1-wp.js?ver=1.4.1-wp:58
admin.min.js?ver=3.9.3:1 parsererror SyntaxError: Unexpected token / in
JSON at position 0
    at JSON.parse (<anonymous>)
    at n.parseJSON (jquery.js?ver=1.12.4-wp:4)
    at jQuery.parseJSON (jquery-migrate-1.4.1-wp.js?ver=1.4.1-wp:318)
    at Wb (jquery.js?ver=1.12.4-wp:4)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)

**Comment by tech2serve** [comment]
Yes. The import went all the way through on my site. The Enable jQuery Migrate Helper plugin and TSML are the only active plugins on my site. If you're getting and error, it is likely caused by something else.

**Comment by technologynhaa** [comment]
So, it worked (I think it was working all along, but was just really
slow).  The problem is that when I select "Switch to Districts", nothing
happens.  What shall I do?

**Comment by technologynhaa** [comment]
This is what is in the console:

JQMIGRATE: Migrate is installed with logging active, version 1.4.1
x.js?ver=7.2.3:1 Uncaught TypeError: Cannot read property 'csstransforms'
of undefined
    at x.js?ver=7.2.3:1
    at Module.<anonymous> (x.js?ver=7.2.3:1)
    at n (x.js?ver=7.2.3:1)
    at x.js?ver=7.2.3:1
    at x.js?ver=7.2.3:1
(index):863 Uncaught TypeError: $window.scrollBottom is not a function
    at HTMLDocument.<anonymous> ((index):863)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)
DevTools failed to load SourceMap: Could not load content for
https://stage.nhaa.net/wp-content/themes/x/framework/dist/js/site/x.js.map:
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by technologynhaa** [comment]
I imported the TSML compliant file on our production site and vey thing
works :-). So, staging is just broken and I will copy production to
staging.  Thank you for your help!
