### ISSUE TITLE
Updating customized fork to newest version

### ISSUE THREAD

**Issue by ghostaln** [code4recovery/12-step-meeting-list#242]
Needing some help here. Our area website was developed in 2016, and the person who built the website took the existing TSML plugin (2.01, I believe) and heavily customized it to our purposes. He told me that future updates were not backwards compatible, so the plugin was frozen. I need to update to the newest version for Wordpress compatibility and new features (specifically, online-only meetings by approximate location). I am certain that the new versions do everything that we need and currently use (and more). I am either looking for a process for upgrading our existing plugin or confirmation that I can do a meeting export, uninstall current plugin and install new version, then import. TIA.

**Comment by tech2serve** [comment]
I think I would start by spinning up a test Wordpress site and installing the latest TSML. Export the current `template.csv` to use as a guide for that fields/data the current TSML can accept.

On your existing site, export the data to a csv. Manually map to the new csv format, and then try importing into your test site.

Make sense?

**Comment by tech2serve** [comment]
No further engagement from OP. Can reopen if OP returns.
