### ISSUE TITLE
Issues with "publishing" an already saved Draft or Private meeting

### ISSUE THREAD

**Issue by CoryBofLI** [code4recovery/12-step-meeting-list#244]
If an entry has been set to "Draft" or "Private" in the Publish section of the Edit Meeting page, it cannot be changed at a later point in time.
From the "Meetings" page choosing the "Draft" meeting list results in showing list of draft entries.
Choosing the "edit" pulls up the page with the already entered information. 
However - in the "Publish" section, none of the "edit", Status: Draft; or Visibility: Public - lead to any further choices.
Something seems to run Status  "/post.pp?post=17568&action=edit#post_status" but nothing happens 
and with visibility : "/post.pp?post=17568&action=edit#post_visibility" and again nothing happens

This has just started with the most recent update, both to TSML v3.9.4 and WP v 5.6
Cory B
Nassau Intergroup

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment]
I'll try to explore this tomorrow.

In the meantime, can you confirm for me what happens if you head down the address field and force the system to geocode the entry?

**Comment by CoryBofLI** [comment]
Adding an  address to a "Draft" will permit it to be switched to "Published" by using the Publish button - but the edit button does nothing,
For the visibility problem, once a previously properly geocoded meeting has been changed for "Public" to "Private" there is no way to return it to "Public" - as above edit button does nothing.
Also there seems to be no way at the moment to change a meeting from "Public" to "Private"

**Comment by CoryBofLI** [comment]
Going back to Wp 5.5
When activating the "edit" buttons - additional drop boxes appear for each one of the choices, these are no longer available

**Comment by tech2serve** [comment]
Hey @CoryBofLI --

I'm using Wordpress 5.6 and TSML 3.9.4, and so far I've not been able to duplicate the issue. Here I am in with a draft status for a meeting, and I seem to have all the options available:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/31904316/102251347-af4c4e80-3ed2-11eb-914a-dd9ad3c919cf.png">

If this is not what you're experiencing, then I'd suggest looking in the dev console for errors and proceeding down the traditional troubleshooting patch of disabling other plugins to rule out a conflict from one of those with Wordpress 5.6.

Happy to help further if I can. Let me know what you're able to find out with other test.

cc: @machouinard

**Comment by CoryBofLI** [comment]
Followed your suggestion of playing with the Plug Ins.
Turns out WP 5.6 has conflict with the plug in
    Page Builder by SiteOrigin
Once that was disabled, drop downs for Status, Visibility & Publish reappeared.
Thanks for your help,
Keep up the good work on this life saving plug in

**Comment by tech2serve** [comment]
Glad I could be of service. I admit you had me concerned because we had made a change with how we handled draft meetings, but since that change wasn't related to that part of the edit page, I was scratching my head.

cc: @machouinard
