### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by mpgeek** [code4recovery/12-step-meeting-list#245]
When using the data sources feature to aggregate a JSON feed from another site's TSML data, i'm now getting JSON parse errors in the admin ui. This just stopped working within the last month or so.

Steps to reproduce:
1. Go to **/wp-admin/edit.php?post_type=tsml_meeting&page=import** to add a data source
2. Fill in a title, then paste this URL for the source: https://www.pdxaa.org/wp-admin/admin-ajax.php?action=meetings 
3. Click on _Add Data Source_

Nothing is imported, and an error shows in the admin:
![Screen Shot 2020-12-16 at 12 47 22 PM](https://user-images.githubusercontent.com/1072643/102405292-c6a43e00-3f9d-11eb-9a48-cac45190f8c4.png)

I've run the JSON from the feed through various JSON linters and it comes up clean every time. I would normally start at the data source to see if there's a formatting problem, but the validator makes me think something else might be going on. 

Has anyone run into this before? Is it just me?

Desktop (please complete the following information):**
 - OS: Mac Catalina
 - Browser: Chrome
 - Version Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by tech2serve** [comment]
Hey @mpgeek,

I just tried your link using both Safari and Chrome on a Mac, and the data imported just fine both times.

Which version of TSML are you using? Wordpress? If not, consider upgrading both to the latest versions.

I would then take two steps if the problem persists: 
1) Disable all of your other plugins and see if the problem clears up. You can and should also look in the developer console for errors that might point towards the offender.
2) Clear your website server and browser caches.

Keep us posted.

**Comment by mpgeek** [comment]
Thanks for the quick reply and test @tech2serve. This site is what comes out of a default WP install from siteground, getting rid of the plugin cruft looks to have fixed it. It was either Yoast or WPFormslite being removed from the system that fixed it. I'm betting Yoast is not the culprit.

**Comment by mpgeek** [comment]
Closing here, my issue has been resolved.
