### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by wendydunning** [code4recovery/12-step-meeting-list#246]
Hey,

I updated to the newest version - always awesome - but now I don't see the "export to csv" option anywhere. It is no longer in the Import and Settings Area. Am I just missing it somehow? 
Thanks in advance, I know you are busy.

Wendy

**Comment by tech2serve** [comment]
Hi @wendydunning,

On your Import & Settings page, you should have a pane like this:

<img width="279" alt="image" src="https://user-images.githubusercontent.com/31904316/102412094-02043400-3fc1-11eb-9bec-87c69cd51fef.png">

If you don't see one, please send me a screen cap of what you do see.

**Comment by wendydunning** [comment]
Man, head up butt. Must have looked right at it 3x --I got it. You guys are the absolute best.
Sorry about that!!

 Thanks alot

Wendy

**Comment by tech2serve** [comment]
No problem. We’ve all been there.
