### ISSUE TITLE
Meetings not found - no changes made.

### ISSUE THREAD

**Issue by aanecswebmaster** [code4recovery/12-step-meeting-list#249]
**Describe the bug**
(Similar to problem #247 )  This problem has the same symptoms as that problem, Meeting web pages show no meetings found.   Admin can see meeting info, using exact url for a single group works, etc.  Now the problem has gone away.  Reporting it here for information in case someone else experiencing the problem, or someone knows the cause.  

The problem was first reported at 7:00 p.m. (CST) last night.  We have  made no changes or updates to WP nor any plugins nor the theme.  Looking at what limited logs we have showed nothing.  Then about 10:00 a.m. (CST) today, we made some seemingly unrelated changes and the problem went away.  We made two minor updates to Formidable Forms plugin, and we upgraded the WordPress from 5.5 to 5.6.    Perhaps the problem happened to fix itself about that time, or one of the changes triggered something to fix it.

Again, no action requested on this.  You can close it now.  Just posting in case someone else experiences the problem.

**To Reproduce**  Website is aaneok.org.  Cannot reproduce.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 97eighty** [comment]
@aanecswebmaster This sounds like a Permalink issue. This can be manually triggered by going into Settings->Permalinks and pressing Save. The action of updating plugins could have triggered the Permalink reset and fixed your problem.

**Comment by aanecswebmaster** [comment]
Thanks
