### ISSUE TITLE
Add "Meeting Removed from Schedule" to conditions prompting Change Notification

### ISSUE THREAD

**Issue by 2021metamalc2021** [code4recovery/12-step-meeting-list#250]
I wonder if it could be arranged for those receiving Change Notification Emails to be alerted when a meeting is deleted from the schedule. At present, notifications are sent when a meeting is created or updated, but not when it is deleted.

**Comment by tech2serve** [comment]
We can discuss that. Admittedly, we've not had a lot of bandwidth for new features.

**Comment by 97eighty** [comment]
Duplicate conversation going on in #503.
