### ISSUE TITLE
Problem With Cell Not Pulling Correct Information 

### ISSUE THREAD

**Issue by keligirl43** [code4recovery/12-step-meeting-list#251]
Hi! 

I have one meeting that always reverts back to saying Zoom Only in the location. It's correct on the spreadsheet (with the location), but whenever I update the spreadsheet, it still says Zoom Only. I have to go back in and edit that meeting individually. I checked my spreadsheet and there is no mention of Zoom in that cell. Do you have any idea why it may be doing this? 

Thanks!

**Comment by tech2serve** [comment]
@keligirl43 --

Can you send me a copy of your spreadsheet? Use tsml@code4recovery.org.

Also, tell me more about what meeting is experiencing the issue.

**Comment by tech2serve** [comment]
@keligirl43, 

I'm seeing non-standard types in the type field. Have you defined those in a child theme functions.php?

**Comment by keligirl43** [comment]
Hi!

Sorry for the delay. I am not sure what you mean by that. Our spreadsheet
seems to be working OK minus a few cells.

I'm not sure how to define those in the child theme.

**Comment by tech2serve** [comment]
You can't just define a meeting type using whatever you want in the cell of the spreadsheet. You have to use the types defined in the spec, or those you custom define.

For example, "Zoom only" is not a type we use. Nor is "Across from McDonald's". While types not recognized should be simply moved to notes, I'm not clear why you're putting that type of information in types, and I'm wondering if that is causing your error?

Make sense?

**Comment by keligirl43** [comment]
Hi!

It does make sense. I have another lady who is updating the spreadsheet for
me.

Where can I find the exact specs needed to make sure we are entering things
correctly?

**Comment by tech2serve** [comment]
There are three ways to get them.

1. The admin page for editing a meeting.
2. The source code itself (`variables.php`).
3. The specification's home page [meeting types](https://github.com/code4recovery/spec#meeting-types).

If memory serves, you should be able to put the code or the description in the field of the CSV. 

Once this has been cleaned up, please retest and let me know where we stand.

**Comment by 97eighty** [comment]
Closing this stale issue. Please reopen if still a problem.
