### ISSUE TITLE
Meetings are now virtual only

### ISSUE THREAD

**Issue by BartBlom** [code4recovery/12-step-meeting-list#253]
I tried adding a virtual only meeting;  It would not go in until I provide a street address (for which I used Mississauga City Hall) 
And made a note the address was fictional
I understand this is needed for the map function, which makes sense. 
But if a meeting is virtual only maybe providing a city name only should be sufficient? 

Thanks for a great function you guys provided 

Bart

**Comment by tech2serve** [comment]
> But if a meeting is virtual only maybe providing a city name only should be sufficient?

Hi @BartBlom,

You need to enter city **and** state (and that must geocode), and then the online details, and it should take (assuming you're using v3.9.4). 

Although a meeting can be online only, it still must be tied to a parent region/area (if you will). Groups and GSO both requested this so as to help with broader organization and accounting of 7th Tradition contributions.

When you geocode a city and state, you should still see a map but without a marker. This reflects an approximate location and the directions feature for TSML (Meeting Guide for that matter) is disabled.

If you find you're still having difficulties please let me know and we can reopen this.

**Comment by BartBlom** [comment]
City name and Province works!
Thanks!
