### ISSUE TITLE
Meeting Type Request

### ISSUE THREAD

**Issue by smhay** [code4recovery/12-step-meeting-list#254]
I want to mark meetings types as "Veterans" or "Lead" meetings.
Would it be possible to add these to the list of meeting types?

For now I have those terms in the Location Notes field. Thank you!

**Comment by tech2serve** [comment]
Please review [the FAQ](https://github.com/code4recovery/12-step-meeting-list/wiki/Frequently-Asked-Questions) which has a section on adding your own custom meeting types. 

If you still have questions, we can reopen this as necessary.
