### ISSUE TITLE
Map / API Key Issue - Cant Add or Update Meetings due to Address Geocoding Lookup Issue

### ISSUE THREAD

**Issue by rfc12399** [code4recovery/12-step-meeting-list#256]
Hello and Happy New Year!

- This week I suddenly noticed that I cannot Update or Add meetings in most cases
- I traced the problem to an issue with "Address" field in the "Location Information" panel on the Edit Meeting screen:
-  - Its using one of Googles API's to check the address, and finally
-  - Most address lookup calls, but not all, return an error calling out an issue with the API Key:

_This IP, site or mobile application is not authorized to use this API key. Request received from IP address 198.71.228.26, with empty referer_

- We have been using the Mapbox option for several years now...
- I tried Chrome, Firefox, Edge - issue always persists
- I tried some random addresses that I know are valid, all of them returned the error
- I found that one of the addresses / meetings on our site works, and does not return the error
- The initial example (below) has an apostrophe in it - at first I thought that was the problem, but I then discovered its most addresses and apostrophe doesn't matter
- Examples:

**An address we have been using for years:**
"Google gave an unexpected response for address <code>108 Carbon Hill Rd, O\'Fallon, IL 62269, USA</code>. Response was <pre>(object) array(
   'error_message' => 'This IP, site or mobile application is not authorized to use this API key. Request received from IP address 198.71.228.26, with empty referer',
   'results' => 
  array (
  ),
   'status' => 'REQUEST_DENIED',
)</pre>"

**Heres an address that DOES work:**

442 S Demazenod Dr, Belleville, IL 62223, USA

**Heres my own address, failure:**
"Google gave an unexpected response for address <code>2 Melrose Ct, Swansea, IL, 62226</code>. Response was <pre>(object) array(
   'error_message' => 'This IP, site or mobile application is not authorized to use this API key. Request received from IP address 198.71.228.26, with empty referer',
   'results' => 
  array (
  ),
   'status' => 'REQUEST_DENIED',
)</pre>"

**To Reproduce**
1. Go to Edit Meeting on any meeting
2. Note whether the map shows up when the page loads
3. Open browser dev tools console
3. (No need to save) change the address to: 108 Carbon Hill Rd, O' Fallon, IL 62269, USA
4. See error in the console

Thanks in advance for any insight,

Rob

**Comment by tech2serve** [comment]
Duplicates #255.

The underlying issue is the same: High billing costs from Google. We're working to resolve as quickly as possible.
