### ISSUE TITLE
Meetings no longer listed on page

### ISSUE THREAD

**Issue by gnawsome** [code4recovery/12-step-meeting-list#258]
There are no meetings listed for any day/every location/any time/etc.  All of them stopped showing up.  

**To Reproduce**
1. Go to '...' aaminnesota.org -> Meetings -> Minnesota Meetings
No meetings listed regardless of what combo of settings you pick.  

**Expected behavior**

On Wordpress -> Meetings it still shows the 2488 published meetings.  

This occurs on every device and every browser tested on.

**Comment by tech2serve** [comment]
By looking in your debugging console, it appears you have an error with your API key. Do you have your own Google API Key entered in Settings?

**Comment by gnawsome** [comment]
I am trying to set up the google API key as I am unsure if this is related to the other major issue going on or not.   It was previously running on a mapbox API key which also wasn't displaying meetings.  I can change it back to that if that would assist you.

**Comment by tech2serve** [comment]
Did you modify line 585 in your `functions.php` to add your own Google API key? With your Google API key, did you turn on the geocoding API?

If you haven't modified line 585, then please do put the Mapbox key back in and let's focus on one issue at a time.

Try these steps:
1. Refresh your permalinks (Settings->Permalink->Save).
1. Disable all other plugins and see if the problem persists. I do not A LOT of warnings and errors in your console.
1. Clear your website cache (through your hosting provider).
1. Look at your meeting list on the admin page and make sure their status is published.

BTW, how did you get your meetings into your site? 2,488 meetings is a lot. Are you taking feeds from the areas?

**Comment by gnawsome** [comment]
I've completed steps 1-4 and it's still not working.  I did also set it back to the Mapbox Key. 

As far as I know all of these meetings were manually entered over the last few years.  We did have a previous HTML database that may have been imported when we started using this plugin.

**Comment by tech2serve** [comment]
It looks like the errors and warnings cleaned up. 

When did the issue start?

I just realized you didn't list version numbers of Wordpress or the plugin. Are you using the latest of both?

What theme? Are you using a child theme or have you made any modifications or customizations?

**Comment by gnawsome** [comment]
I was notified of the issue Saturday Evening - so January 1st.  

Wordpress Version 5.6
12 Step Meeting List 3.9.4

Weaver Xtreme Theme 4.4.3 - I am unaware if any modifications have happened in the past other than appearance changes. 

PHP Version 7.3.6

**Comment by tech2serve** [comment]
Try editing a single meeting, and republishing it. See if that meeting then shows up on the front end.

Confirm please (because I didn't see your answer) that you did not replace our API key with your key on line 585.

**Comment by gnawsome** [comment]
Confirmed - I did not replace your API key with my own on Line 585.

I edited and published one meeting and now they have all shown up again... it appears to be working properly now.  I'll let the group records service position know that it appears to be resolved for now.
