### ISSUE TITLE
Join by phone button

### ISSUE THREAD

**Issue by district6wc** [code4recovery/12-step-meeting-list#262]
Hello,

Re: Meeting Guide App for Al-Anon users

I have had multiple reports that when a person clicks on the "join by phone" option to connect to a meeting, the connection stops at 'enter meeting ID and does not connect.  Is anyone else reporting this?  I tested on my android phone and did not have a problem.

Thanks

**Comment by 97eighty** [comment]
I read last week that Zoom will start to disable "join by phone" support on Free accounts. They are a bit overwhelmed I guess.
You might check http://tiaa-forum.org too. Lots of technology folks over there who might be experiencing similar issues.

**Comment by district6wc** [comment]
Thank you for the quick response.  The zoom meetings are not free as our
district pays for them.

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by tech2serve** [comment]
Hey @district6wc,

Please give us a link to the meeting in question, and we can try it on our phones. However, if you're getting a prompt from Zoom to enter information, that would seem to indicate TSML has done its part.

p.s., Just to make sure we don't confuse anyone, Meeting Guide is the mobile app used by AA. For here, we're talking about 12-step-meeting-list (TSML)

**Comment by district6wc** [comment]
Here is the url https://alanonalateen6nc.org/ and then click on meetings.
An example is Downtown Durham on Tuesday/Friday.

Sorry for the confusion. It is the 12-step-meeting-list (TSML) that I am
referring to.

Yours in Service,
Stephanie Holopainen
Learning To Live AFG, Graham

District 6 Website Coordinator Panel 59
336 675-1301

**Comment by tech2serve** [comment]
I tested on my phone (iPhone 11 w/ later iOS) and it dialed without a problem. 
![IMG_4DBADF5AE183-1](https://user-images.githubusercontent.com/31904316/104132237-825c5180-5341-11eb-8720-4ae9fa04c272.jpeg)

You may want to ask those raising the issue what they're using to dial? If they're on a desktop computer/laptop, they would need to configure an app to do the dialing (Google is their friend). As far as I can tell, everything on our end is working as designed.

I'm going to close this issue, but if your users provide more information that would help us research further, we can always open it again.
