### ISSUE TITLE
Inaccurate link on import and settings page

### ISSUE THREAD

**Issue by L-squared** [code4recovery/12-step-meeting-list#265]
**Describe the bug**
When users are first getting started with the plug-in there is a link associated with Google's map pricing that is not accurate. 

**To Reproduce**
Go to the plugin in wordpress - before any mapping key has been added
Choose Import and Settings
See the first link in Enable Maps on Your Site
When you click it it just goes to meetingguide.aa.org. I believe there used to be content that supported learning more about Google map pricing but a redirect was put in place after AA acquired the app

**Expected behavior**
Link takes you to accurate information or is removed

**Screenshots**
![image](https://user-images.githubusercontent.com/10970074/104748318-35002b80-5717-11eb-810e-027e08eb6b47.png)

**Additional context**
This is a minor issue since it isn't visible once people input a mapping key.

**Comment by tech2serve** [comment]
Good catch!  Thank you. Will get that link removed.
