### ISSUE TITLE
Time Zone Information

### ISSUE THREAD

**Issue by indelg1** [code4recovery/12-step-meeting-list#266]
It would be helpful to have a field where we can have TIME ZONE information.  We now have a lot of virtual meetings and people from New York often attend meetings that originate in LA.   If we had a clear Time Zone designation, people in New York could easily determine that a 9am PST meeting is actually 12 noon EST.  This would help show how virtual meetings are actually a good fit for many outside the time zone that the meeting is actually taking place.

Let me know if this is possible....  Thank you..

Greg

**Comment by tech2serve** [comment]
@indelg1,

This is an interesting idea and I'll look into it at some point, but it also adds complication that may lead to many more troubles for users. And the priority is likely to remain pretty low for our team given the other issues we're working. If you or someone you know is handy with PHP and JS, we'll entertain a pull request. 

In the meantime, I suggest putting the timezone information in the online meeting notes so it will show up prominently when someone views the meeting.

**Comment by joshreisner** [comment]
@indelg1 @tech2serve I think this is actually a front-end issue, not than a backend one. We should talk about what experience we want users to have, but there's already a kind of solution in place for sites that use TSML UI.

For example, let's say it's 11:45 am on the east coast and a Philadelphia user goes to aasepia.org, they see meetings starting at noon.

Simultaneously, it's 8:45 am on the west coast, and a San Francisco user goes to aasepia.org, they also see meetings starting at noon.

We're not converting the time zone for the user (although there is a [request](https://github.com/code4recovery/tsml-ui/issues/93) to do that), but the UI is aware what the next meeting is regardless of timezone.

The solution we agreed to for Meeting Guide was also not to convert, but to display a message to the user when there's a discrepancy between the user's time zone and the website's time zone. That would be possible using javascript without any data model changes.

**Comment by joshreisner** [comment]
The only use-case I can think of where we'd want an administrator to be able to specify a time zone would be for those sites that list meetings in multiple time zones. Those typically are not AA websites, although I do think Secular AA would be one of these.

**Comment by annieshines** [comment]
I see this is a little old, but I wanted to share that I'm maintaining a site that could use a Time Zone feature. We have meetings all over the world, some exclusively online, and I'm not sure how to best represent that now.

Thanks for this plugin, it's a big help.
