### ISSUE TITLE
Display issue on the autofill search field

### ISSUE THREAD

**Issue by andxres** [code4recovery/12-step-meeting-list#270]
There’s a display issue since v 3.9.4 on the list that appears below the search field as you start typing. 

**Issue:**
![image](https://user-images.githubusercontent.com/61430063/105205384-e35c0480-5b4d-11eb-8058-521d4906d3dd.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/61430063/105205806-4f3e6d00-5b4e-11eb-99b3-95d340d2296f.png)

**Comment by tech2serve** [comment]
Please provide standard information like website link (Houston, TX?), Wordpress versions, theme, other plugins, etc. 

My quick suspicion is that this is related to another plugin causing issues with jQuery Migrate. Once I have your website link I can see if I can duplicate the issue. If I'm not able to duplicate (which if it is aahouston.org, another our members already reported he cannot duplicate the issue on three different browsers) it, then please try different browsers/computers to see if the issue goes away.

**Comment by andxres** [comment]
Yes, the website link is https://aahouston.org/meetings/, just that I rolled back the plugin to 3.9.3 because of the complains we received. I'm going to update the plugin right now so you can take a look. 

WordPress version: 5.6
Theme: Divi

**Comment by tech2serve** [comment]
Ok. Yeah. Confirmed.

I would by disabling Enable jQuery Migrate Helper (if installed) and other plugins to see if the issue goes away. Something is interfering with jQuery Autocomplete. If the problem doesn't go away, we'll need to look and see if something isn't getting installed correctly on your server. Maybe try clearing server cache?

And to confirm, are you saying you only have the issue if TSML 3.9.4+ is installed?

**Comment by andxres** [comment]
Thanks for checking!

Yes, it started when we first updated to 3.9.4. We rolled back to 3.9.3, but 4 days ago we updated the plugin again to 3.9.5 and the issue persists. 

No "Enable jQuery Migrate Helper" installed. We'll disable all the plugins, as you suggested, to see if the issue goes away and let you know.

Thanks!

**Comment by tech2serve** [comment]
I also just realized you have a customization here that *might* be a contributor.

<img width="226" alt="image" src="https://user-images.githubusercontent.com/31904316/105209985-15e70c80-5b10-11eb-9e8d-cc9f1358dc02.png">

**Comment by andxres** [comment]
@tech2serve I just found the plugin that interferes with the autofill. It's **ShiftNav - Responsive Mobile Menu**. Once I deactivate it, the autofill list is displayed properly.

The "Enter search info here:" is a CSS customization that doesn't seem to be a problem (I removed it and tested).

Any ideas about how to make these two plugins work together?

**Comment by andxres** [comment]
I found the option from **ShiftNav** that messes the autofill list. It's **Shift Body** from **General Settings**. I think we can live without it...

![image](https://user-images.githubusercontent.com/61430063/105331472-2b296d00-5bdc-11eb-9c07-13daffddf942.png)

@tech2serve Thank you for your help!

**Comment by tech2serve** [comment]
Glad we got it resolved quickly.
