### ISSUE TITLE
Page no found for public meeting list

### ISSUE THREAD

**Issue by technologynhaa** [code4recovery/12-step-meeting-list#273]
Hi!

We were updating plugins, brought the site down and had to restore from backup.  When we clicked on the public meeting page in import and settings, we received a page not found.  We put in a redirect to our staging site as a workaround, but how do we correct this on the production site?

Thank you!

Sean K.
Technology Chair, Area 43 (NH)

**Comment by brianw-area24** [comment]
Many times it's a simple fix to repair these page not found errors. Go into the "Permalinks" page under Settings in the WordPress admin pages, and click "Save Changes". You don't need to change any settings, just save changes. 

Hopefully this will fix the issue, if not, let us know and we'll dig deeper.

Brian W

**Comment by technologynhaa** [comment]
You are the best!  That worked :-)

Sean
