### ISSUE TITLE
Map is mot showing on for the Address after recent update

### ISSUE THREAD

**Issue by district6wc** [code4recovery/12-step-meeting-list#275]
**Describe the bug**
I'm using the Al-anon template when viewing meeting information, the map is showing error.

**To Reproduce**
1. Go to 'Meetings in the dashboard'
2. Click on 'a specific meeting'
3. Scroll down to 'Region and look at map below'

**Expected behavior**

Map usually show meeting location but now shows error.  I am using a  current API key

**Screenshots**

![image](https://user-images.githubusercontent.com/1336342/106066868-87542b80-60cb-11eb-973f-5baaf6b76c2c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brianw-area24** [comment]
I think I found the your website, and using the Web Console in Firefox, I see the following error:
```
Google Maps JavaScript API error: RefererNotAllowedMapError
https://developers.google.com/maps/documentation/javascript/error-messages#referer-not-allowed-map-error
Your site URL to be authorized: https://alanonalateen6nc.org/locations/binkley-baptist-church/
```
​What I think this means is your Google API key is restricted in what URL's can use the key, and this page isn't allowed. Therefore, I think you can go into the Google Console and allow this site to use your key.

The Restricting API Keys section on this page gives pretty good instructions:
https://developers.google.com/maps/documentation/javascript/get-api-key#restrict_key

Brian W.
