### ISSUE TITLE
New Meeting Type

### ISSUE THREAD

**Issue by aacincinnati** [code4recovery/12-step-meeting-list#276]
Problem: It is difficult to filter for “Face to Face” meetings because there is no F2F meeting type. I was told if the meeting is not marked “Location Temporarily Closed” it is meeting face to face. What about online only meetings which we may now add with just a city and state.
Solution: Create a new meeting type call Face to Face F2F.
Alternatives considered: we tried adding a note in the meeting notes like, “Now meeting face to face” then people can search for “face” but that doesn’t work when searching near location.

**Comment by tech2serve** [comment]
Multiple issues (use search) discuss our plans for resolving the issue. Hopefully, we'll be able to focus on this once the geocoding issue is resolves sufficiently.

**Comment by aacincinnati** [comment]
Thank you
