### ISSUE TITLE
Upcoming Meeting Removed Too Soon

### ISSUE THREAD

**Issue by DonnaColon** [code4recovery/12-step-meeting-list#281]
We use the app on our home page and it shows upcoming meetings for the day; however, it is removing meetings 4 - 5 hours too soon.  Consequently, by 3pm the evening meetings have already been removed.

Is there a fix for this?

**Comment by tech2serve** [comment]
Please start by checking the time zone settings for your Wordpress installation and browser. Experiment and see if you can get the settings to match/sync.

**Comment by tech2serve** [comment]
Will reopen as necessary if OP returns.
