### ISSUE TITLE
Changing/adding text for 'Request a change to this listing' feature on Meeting Detail page

### ISSUE THREAD

**Issue by namdrino** [code4recovery/12-step-meeting-list#282]
Hi.  Quick question - is there a way I can modify the text displayed after hitting 'Request a change to this listing' feature on the Meeting detail page.  Right now it says "Use this form to submit a change to the meeting information above."  I would like to add some additional text to clearly specify the information needed when updating a listing.  Thanks.

**Comment by brianw-area24** [comment]
This may do what you need to do. It allows you to put text there, but I don't think you can add html, so it's somewhat limiting. But it's easy to do. 

Many themes allow you to add additional CSS to your site. With the theme on my test site, in the WordPress dashboard, I went to Appearance -> Customize -> Additional CSS and added the follow line of code:

`form#feedback li.list-group-item-warning:after {content:"Be sure to include ..."; display:block; font-size:0.8rem; color:#000000; }`

Of course you can change the content, and other CSS styles to change the look of it. Experiment a little and see if this will work for you.

Brian W.
