### ISSUE TITLE
How to connect Site Meeting with App

### ISSUE THREAD

**Issue by BKDesigns10** [code4recovery/12-step-meeting-list#283]
Hi,

I am new to this plugin and having some challenges with integration. Just have few questions.

I used this plugin for one of the newly develop AA group and the meeting list is already on the website. How will I be able to connect my site to the App?  

Is there something I need to do?

Noob here

**Comment by tech2serve** [comment]
Hey @BKDesigns10,

This is a good reminder that we need to get a new video made showing how to do this, or get it added to our FAQ.

The process is pretty simple. On your settings page, you should see fields down and to the right that look like this:

<img width="275" alt="image" src="https://user-images.githubusercontent.com/31904316/107557069-25a1c000-6ba7-11eb-9b17-dfa08022fe13.png">

Type in "Meeting Guide" and click "Add". That creates the necessary key for AAWS/GSO to add your meetings to Meeting Guide.  You should probably also send them an email (appsupport@aa.org) to help coordinate and make sure everything is working.

Good luck!

**Comment by tech2serve** [comment]
If this isn't resolved, please let us know and we can re-open the issue if needed.

**Comment by BKDesigns10** [comment]
Hi,

I followed what you suggested but im still not seeing the meetings we have
on our site on the app.

**Comment by tech2serve** [comment]
If Meeting Guide shows (right above the input box), then please contact appsupport@gso.org.

If not, post a screen cap of that part of your settings page.
