### ISSUE TITLE
TSML 3.10.0 Question (NOT A BUG)

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#284]
In this version, you've added a BETA feature for API Gateway to replace direct geocoding calls to Google. Where would I put the Google API key? I am using a Mapbox Access Token, but happen to have a Google API key for our events plugin.

On Jan 1, you said we can change line 585 of the functions.php file to our own API key. Is this still the case? I do not have a child theme, and would not be comfortable doing anything unless I did. Unfortunately, my time is limited, so I would like to understand if this is the process, or if you will be adding in the future a clear place where the API key can be provided by the plug-in user?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment]
> In this version, you've added a BETA feature for API Gateway to replace direct geocoding calls to Google. Where would I put the Google API key? I am using a Mapbox Access Token, but happen to have a Google API key for our events plugin.
> 
The approach we took is that a user would have a Google key, or a Mapbox key, but not both. If they choose to use a Google key with geocoding enabled, they would also use that for mapping (and have the mapping API enabled).

> On Jan 1, you said we can change line 585 of the functions.php file to our own API key. Is this still the case? 

With the API Gateway, we believe we're heading off the need for webmasters to bother changing line 585 in functions.php, or implementing a different solution in any way. 

>I do not have a child theme, and would not be comfortable doing anything unless I did. Unfortunately, my time is limited, so I would like to understand if this is the process, or if you will be adding in the future a clear place where the API key can be provided by the plug-in user?

My suggestion is try out the beta API gateway and use your Mapbox key for mapping. That will be the simplest approach for new admins. Eventually, we will make the gateway the default geocoding approach.

However, if a webmaster still wants to use their own Google key for mapping and geocoding, they must start by putting their key in for mapping (thus clearing the Mapbox key). That Google key is then available for geocoding:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/31904316/107900470-1906ca00-6f0f-11eb-9492-30eadf8d1401.png">

 One would also need to enable the geocoding API in their Google console for this to work.

Again, the API gateway is the easiest.

**Comment by Grateful-Viv** [comment]
Thank you. I will use the BETA Gateway, and leave Mapbox as the key. Will let you know if there's any issues.

**Comment by tech2serve** [comment]
Thanks!
