### ISSUE TITLE
Unable to update meeting address

### ISSUE THREAD

**Issue by AkronAA** [code4recovery/12-step-meeting-list#286]
I have been unable today to update or add a new address to a meeting. I believe it has to do with the geocoding as the map does not change and the update button is greyed out. We are using The 12 Step Meeting List version 3.10.0 on WordPress version 5.6.1. We have a Mapbox token and are using the Legacy Method. I did try changing the method to BETA with no effect.

**Comment by tech2serve** [comment]
Hi @AkronAA,

Please continue to use the beta api gateway as that will help us improve it and perhaps troubleshoot.

Am I correct in assuming your website is akronaa.org?

I am seeing some errors that were probably generated from your requests. Did you get any errors returned? 

Please open a develop/debugging console in your browser and watch for any errors when you try entering an address.

Also, please give me a couple of examples of addresses you tried. The error I am seeing is "Error: No Geocode Result Found". This indicates Google didn't have a result for whatever address you entered. I'd like to explore that further.

**Comment by AkronAA** [comment]
Yes, the website in question is akronaa.org. Here is the error I get back when I try to enter the address for a reopened meeting. It is, btw, an address we have used before.
https://akronaa.org/wp-admin/admin-ajax.php?action=tsml_geocode&address=130%20Broad%20Blvd%2C%20Cuyahoga%20Falls%2C%20OH%2044221%2C%20USA&nonce=87e5ce7b32 500 (Internal Server Error)

When I try to update a meeting's address to 201 N Market St. Wooster OH 44691 I get the same error, although the console says it is geocoded and I can see a Lat/Long that was returned.

Please forgive me if I am not providing enough information as I have never done a ticket before.

**Comment by tech2serve** [comment]
You're doing fine. 

So I am not able to see an error that occurred on your site in that manner (it is unique to your site). But if you can make a screen cap of it, and post it here, that might be useful.

I just tried entering the Market St address on my dev site and it worked perfect. The fact that you get a geocoding response makes me think the issue is specific to your site. Are you seeing anything else in the console that might be an error.

Try disabling other plugins and see if that affects the results.

I have to run to "work", but I'll be back this evening and will search logs again.

**Comment by AkronAA** [comment]
I can't seem to be able to attach a jpg. Here is the log:
[akronaa.org-1613659820422.log](https://github.com/code4recovery/12-step-meeting-list/files/6003651/akronaa.org-1613659820422.log)

**Comment by tech2serve** [comment]
To create a screen cap on a Mac, you can simply type cmd-ctrl-shift-4, then click and drag the part of the window you want to share, and when you release, the image is copied to the clipboard. Then simply come to the editor here, and type cmd-v to paste the image. Like so:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/31904316/108400991-79cd2580-71e1-11eb-8577-8d17a89b39fb.png">

As you can see, on my site, when I entered "201 N Market St. Wooster OH 44691" into the address field on the new meeting page, I got the correct geocode, without errors in the console. I also tried entering "202 North Market St, Wooster", and that worked also.

Please spell out the exact detailed steps to reproduce the issue on your site. Feel free to also switch to Legacy for geocoding and watch the console again. See if there are any differences, please. 

Also, click on the caret next to the geocode in the console to confirm if the response came from geocoding or cache:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/31904316/108402044-a2095400-71e2-11eb-851c-73e2f614c365.png">

If it comes from cache, then something else is going on.

Also, did this problem (also) coincide with you upgrading Wordpress to 5.6.1? 
Have you tried disabling other plugins?

**Comment by AkronAA** [comment]
Digging through our errors, we found that the ajax request was failing due to a php module not being installed (curl). The problem apparently started when we upgraded php on our server last week. It is working as expected again.

**Comment by tech2serve** [comment]
That would do it!
