### ISSUE TITLE
google maps not showing on website aaboston.org 

### ISSUE THREAD

**Issue by dmacdon** [code4recovery/12-step-meeting-list#287]
**Describe the bug**
google maps not showing on website aaboston.org 
**To Reproduce**
1. Go to 'www.aaboston.org'
2. Click on 'meetings.'
3. Select any meeting'
4. See error - blank map

**Expected behavior**
Map visible for each meeting
**Screenshots**
[screenshot-aabos-nomap.docx](https://github.com/code4recovery/12-step-meeting-list/files/6004909/screenshot-aabos-nomap.docx)

**Desktop (please complete the following information):**
 - OS: [Win 10]
 - Browser [chrome]
 - Version [Version 88.0.4324.182 (Official Build) (64-bit)]

**Smartphone (please complete the following information):**
 - Device: [Pixel
 - OS: [Android 10]
 - Browser [chrome
 -  - Version [e.g. 22]

**Additional context**

**Comment by tech2serve** [comment]
Look at the output in your browser console/debugging tools. With Chrome, something like cmd-option-i should open them.

In the output, you'll see a bunch of errors that seem to indicate you have an invalid Mapbox key entered for mapping. If you fix  that, your problem should be resolved. 

If not, please contact Mapbox and determine what is wrong with your key, or generate a new Mapbox key.

We can reopen this issue if it appears something else is going on.
