### ISSUE TITLE
How to Configure/View within WP

### ISSUE THREAD

**Issue by workgrigby** [code4recovery/12-step-meeting-list#288]
A very beginner question:  I have the plug-in installed, but not sure how to configure/view the Plug-in within the WP site.

Thanks!

**Comment by tech2serve** [comment]
In your admin page for Wordpress, you should see a "Meetings" options:

<img width="156" alt="image" src="https://user-images.githubusercontent.com/31904316/108612108-e5aeba00-73aa-11eb-9569-aa5b8b896779.png">

All plugin specific settings are under the "Import and Settings" page, right hand side. 

Please check out [our FAQ](https://github.com/code4recovery/12-step-meeting-list/wiki/Frequently-Asked-Questions). You will need to enable a mapping key (Mapbox is easiest), but other than that, the default settings should be okay.

Explore, play and you'll learn.

**Comment by workgrigby** [comment]
haha, thanks!  ...after I submitted the question, I just noticed.  smh; sorry about that.  I have found: https://github.com/code4recovery/spec/find/master, though wasn't sure how to capture/import the data feeds.  Still digging/exploring and will check out the FAQ.   ...I do have the Google API key installed (I'm not 'completely' lost. :) )  Much thanks!
