### ISSUE TITLE
Meetings missing

### ISSUE THREAD

**Issue by NCDistrict02** [code4recovery/12-step-meeting-list#289]
Not all of our meetings are showing on the Meeting Guide app.  I am the new Webmaster for the district and am not a coder.

**Comment by tech2serve** [comment]
Please see #285 and other closed issues. 

In short, if the meetings are showing up on your website page (i.e., they're published), and you've working to AAWS/GSO to connect your meeting feed to them, but you're not seeing some of those meetings in MG, you will most likely need to coordinate with AAWS/GSO (appsupport@aa.org) to determine why those particular meetings are not showing up. Usually it has to do with how they geofenced reporting entities.
