### ISSUE TITLE
Latest Update - Add Meeting Not Working

### ISSUE THREAD

**Issue by Cushing3** [code4recovery/12-step-meeting-list#291]
Updated to the latest version. Now when I add a meeting, it auto saves a draft without nothing but the Title saved.  

When I attempt to edit the saved draft - can't "Save Draft" or "Publish" - either immediately or on a set date.

Help?

**Comment by tech2serve** [comment]
What else did you update?

What version of Wordpress are you running?

Are you using the beta geocoding api? Legacy? Or your own Google key? 

Any errors showing in the developer/debug console?

Provide a link to your website.

**Comment by Cushing3** [comment]
As soon as I add "Location" - an existing location – "Publish" grays out, and "Save Draft" becomes non-functional (press it...nothing happens.)

I have double-checked my Google API - Map API and Geo-coding are both enabled.

I have turned off all other plugins - same.

Running Wordpress 5.6.2.

**Comment by Cushing3** [comment]
www.centralalaa.org

Haven't turned on logging for debug.

**Comment by Cushing3** [comment]
I have tried all three settings - Legacy, Google API, and beta

**Comment by tech2serve** [comment]
If you would, please pick beta and lets test that for a bit.

Depending on what browser you're using, you can easily open a debugging console (you often don't need to turn anything else on). In Safari (the one browser I know of that may require you to turn on Developer tools first), it will look something like this when you click tab after entering the address:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/31904316/109240276-d1006680-779c-11eb-8edf-7722aba75b25.png">

This is a useful thing to do to see what errors are being given back to you (separate from PHP debugging with Wordpress).

Also, please tell me what address you're trying to enter.

**Comment by Cushing3** [comment]
I'm in Chrome
![Screen Shot 2021-02-25 at 7 14 30 PM](https://user-images.githubusercontent.com/79673933/109240770-b1b60900-779d-11eb-8231-ede438da316f.png)

**Comment by Cushing3** [comment]
centralalaa.org is the 
![Screen Shot 2021-02-25 at 7 16 03 PM](https://user-images.githubusercontent.com/79673933/109240863-e924b580-779d-11eb-90bf-03e4ea11303a.png)

**Comment by tech2serve** [comment]
It looks like you have an error with your mapping key. You may have locked it down?

Yeah, try clearing restrictions and see if the issue resolves.

**Comment by Cushing3** [comment]
![Screen Shot 2021-02-25 at 7 18 03 PM](https://user-images.githubusercontent.com/79673933/109241019-3143d800-779e-11eb-8423-3d507a995545.png)

**Comment by Cushing3** [comment]
Hang on...Google Maps isn't liking "Cir" instead of "Circle". When I type in the address (without the Group name) I get the map and my buttons back.  

I don't like change. :-(. But I'm glad it's a Google thing, not a Code4Recovery thing...and thanks for showing me the developer's console - never used that before.

**Comment by Cushing3** [comment]
Ohp - spoke too soon.  It was the restrictions.  Now it's cleared (the 5 minute rule) even with "Cir"

**Comment by tech2serve** [comment]
So with the restrictions cleared, you're able to enter the address?

I was able to see a map on your front end, so I know at least part of it is working.

**Comment by Cushing3** [comment]
Yes - I'm trying to turn back on the http:  restriction to watch my quote (probably not a problem given the nature of the call), and leaving the API unrestricted.

That also appears to work, but I'll try again in 5 minutes.

**Comment by tech2serve** [comment]
Not having looked at your site before, I can't tell you when this started:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/31904316/109241616-3fdebf00-779f-11eb-8db3-5dd7fa20da24.png">

But it is unrelated to TSML. And my guess is that it *is* related to the errors getting thrown by Google when you lock down (and I agree you should) the key. You may need to work with your hosting providing to get the SSL set better.

**Comment by Cushing3** [comment]
We're about to move hosting...we're on Fatcow - I don't recommend it.

**Comment by tech2serve** [comment]
Also, if you want a simpler approach, switch your mapping key to Mapbox and then use the beta API gateway (or legacy) for geocoding.

**Comment by Cushing3** [comment]
Never used Mapbox.  I'll check it out.  But the beta is what it's set on with Google.

**Comment by tech2serve** [comment]
Keep in mind there are two different mapping-related services being performed. The first is mapping itself which shows a map and a marker of the meeting.

The second is geocoding. We prefer to take care of geocoding using our key (i.e., the beta API gateway or legacy method for now) because it is simpler to set up and we have testing Google geocoding extensively. 

For mapping, Mapbox doesn't require a credit card to acquire an API key, which is better for a lot of groups.

**Comment by Cushing3** [comment]
Hmmm.  I don't remember giving Google my credit card.  But I may have.  Set up the API 7 years ago.

**Comment by tech2serve** [comment]
Anything else inside the purview of TSML I can help with? Otherwise I think we can close this issue?

**Comment by Cushing3** [comment]
Nothing at this time (well, nothing this time either, apparently).

Thank you for excellent support!  Close the ticket.

**Comment by tech2serve** [comment]
I'm glad we were able to point you in the right direction. Sounding boards are often quite helpful.
