### ISSUE TITLE
Updating addresses

### ISSUE THREAD

**Issue by NCDistrict02** [code4recovery/12-step-meeting-list#293]
There are import errors for our Keep It Basic meetings - the street address for those meetings may not be input correctly in our plug in.  Where do I go to change them?  The street address should be 215 Memorial Dr., Jacksonville, NC 28546

**Comment by tech2serve** [comment]
On your admin page, click on Meetings, and then find the meeting you want to edit. Click on that meeting and a page will come up with all the gory details. You edit it there.

In general, "Location" should reflect the general name of the location. For example, the name of church where the meeting is held. That location information is for you and your website.

Then enter the full address in the "Address" field, and tab or click elsewhere. The plugin will automatically geocode the address, and if there are no issues, you should be able to publish the meeting.

Looking at your website, you have the street address under "Location". That isn't correct for an in-person meeting. You should change it as I described above.

Good luck. We can re-open the issue if something else is weird or not working.
