### ISSUE TITLE
Time Zone Information

### ISSUE THREAD

**Issue by indelg1** [code4recovery/12-step-meeting-list#297]
Is there a way to list Time Zone Information on the list screen.  This would be helpful because we have a lot of West Coast members who are actually wanting to attend East coast meetings.  Also, there are attendees from Europe who look to attend meetings in the USA.

It would be so much easier for them to determine if the meeting time is right for them if we included time zone information in the meeting record.  We have tried putting it in the notes filed but people seem to miss it if they are not looking closely.  But if we can have it appear on the meeting list screen that would be ideal.

Let me know if this is something that is possible?  If not is it a feature that you plan to add?  

Thanks
Greg

**Comment by tech2serve** [comment]
You already entered this as #266.
