### ISSUE TITLE
Adding a brief message on the Meeting List Screen

### ISSUE THREAD

**Issue by indelg1** [code4recovery/12-step-meeting-list#298]
Is there a way to add a brief message to the Meeting List Screen?  Something like "In-Person" Meetings returning June 4th" or "The US has changed over to Daylight Savings Time.  The time difference between your time zone and the meetings may have changed by one hour"

I would like the placement of the short message on the top of the screen above the search fields.  I pasted a graphic below to show what I mean
.
![Meeting List Page1](https://user-images.githubusercontent.com/74081387/110530516-8cec5a80-80e8-11eb-8664-63ebf4a0eb62.png)

Would this be possible?  Would you know what needs to be edited to add such a message?

Thanks

Greg

**Comment by brianw-area24** [comment]
I've done something similar on this site - https://www.aacentraliowa.org/meetings, other than I put it it under search fields. I did this by adding styles to the theme. To go above the search fields, you could use: 
`div#tsml div#meetings div.hidden-print:before {content:"* Closed meetings are for people who want to quit drinking. Anyone is welcome at Open meetings.";font-size:0.65em; padding:5px 0 20px 15px;}`

Of course you could change/add styles to fit your needs. Biggest drawback I know of using this method is that I have not been able to add html code (ie links), but just text. 

Many themes have a place for you to add CSS code like this, but that will depend on your theme. However, if this works, it's an easy way to put a little bit of added text where you indicate.

Brian W

PS I'm going to close this issue, but can re-open it if necessary.
