### ISSUE TITLE
Feature request - consideration of spec/issues/22-25

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/12-step-meeting-list#300]
**Is your feature request related to a problem? Please describe.**
Requesting consideration of spec/issues/22-spec/issues/25.  The requests are for meeting type additions which will make their types indicated more visible and thereby attract more to those types of meetings.

**Describe the solution you'd like**
Due consideration and, if approved, implementation of desired types.

**Describe alternatives you've considered**
Presently, these types of meetings are mostly word-of-mouth and that has worked in the past, but having them 'find-able' to a larger audience can only broaden their reach and appeal.

**Additional context**
Would be nice to see treatment center meetings, pink can meetings, correctional institution or service manual/12 concepts related meetings listed on the site.  These meetings are all about service to alcoholics, whether institutionalized, in a treatment center OR someone who is looking for ways to serve the body in these areas and areas needs a foundation if literature for some additional guidance (svc manual/12 concepts).

**Comment by tech2serve** [comment]
Please see the FAQ under our Wiki for how to add custom meeting types to your site. You can do pretty much anything you like there.

I'll address the issues under the Spec repo separately.
