### ISSUE TITLE
Pagination for meeting listing page

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/12-step-meeting-list#304]
**Is your feature request related to a problem? Please describe.**
Here's the problem.  I load up my area meeting guide app and it breaks the plugin.  It's trying to load everything in 1 shot.  Then, I set the viewing option to be 50/page and the page loads faster (after i clear the server ache of course) & not overloading the plugin, but the results still run below the gutter.  Better, but not an optimal user experience.  So, am left with this request.

**Describe the solution you'd like**
Please create configurable pagination settings piece that is added to meeting app's import & settings page where we can set the max number of displayed rows per page for meeting results.
On the page itself, would like to see pagination links @ 25, 50, 100 results per page.  These would be tied to the users session and not the default setting from the settings page.

**Describe alternatives you've considered**
I have cleared the caching and utilized wordpress's internal app settings piece to accomplish this, but would like something on our side. 

**Additional context**
Doing this would present a cleaner user experience.

**Comment by tech2serve** [comment]
Do you mean TSML? Meeting Guide is the mobile app provided by GSO for smart phones?

What is your website URL?

**Comment by jcookson-infoblox** [comment]
Sorry, did not see this for some reason.  Its https://area72aa.org/meetings/

**Comment by tech2serve** [comment]
Ok. We'll discuss it. 

Have you considered adding the widget to just display upcoming meetings?

**Comment by brianw-area24** [comment]
Closed due to work that's happening in TSML-UI
