### ISSUE TITLE
ShortCode for Meeting page functionality

### ISSUE THREAD

**Issue by codehammerz** [code4recovery/12-step-meeting-list#307]
**Is your feature request related to a problem? Please describe.**
FYI .. New to working with wordpress.. 
The Meeting page that the plugin creates doesn't display properly, All the search features are cut off. Also the wordpress themes header image is not displayed:
http://aasalem.org/meetings/

**Describe the solution you'd like**
A shortcode that could be added to a page to embed all the meeting list display and search functionality so it works with the theme?

**Describe alternatives you've considered**
Looking for a different theme. 

**Additional context**
-

**Comment by tech2serve** [comment]
Hey @codehammerz --

There are hundreds of sites with TSML deployed for which the page is displaying correctly. 

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/31904316/113346631-1961f580-9302-11eb-8135-dc2b4eb4843e.png">

I have to assume there is something else going on with your site or theme. What theme do you have installed?

**Comment by codehammerz** [comment]
It probably is something with the theme.. It doesn't display the banner image.. same thing happens with the events page for events calendar... But someone mentioned that there was meetings top and meetings bottom under widgets, which gave me a work around..

Probably need to find a new theme.. been through a few already.. thats been the biggest challenge for me learning wordpress is just the time it takes to find a theme that works.

**Comment by tech2serve** [comment]
If you try the twenty-seventeen theme and don't see a meeting list layout like I showed in the screen cap above, then my guess would be that something else (perhaps another plugin?) is interfering the layout of your page. In this case, try disabling all the other plugins and see if the layout corrects.

Good luck. If you're looking for general Wordpress help, there are a lot of websites with tutorials. And you might try searching TIAA Forums, assuming you're familiar with that resource.
