### ISSUE TITLE
want to display default to the current day of the week

### ISSUE THREAD

**Issue by AnchorageIntergroup** [code4recovery/12-step-meeting-list#308]
I want the meetings list display to default to the current day of the week.  It was functioning that way before the change.  It is my fault that I didn't capture the link as it was.

I have listed what I have done below and I tried searching the wiki, and issues no luck.  How can I best fix this?  Is there a 'current day' parm?
Many thanks in advance for your help.

Ayla J Web servant Anchorage area intergroup.

I just updated my site from divi to elemenator 

and set the link https://anchorageaa.org/archives/meetings/?tsml-day=any

this did not work as I hope it displays all the meetings starting Monday not just the current day

 then changed it to https://anchorageaa.org/archives/meetings 
The change was made on WED and now it always displays meetings for Wed 

I have tried searching the documentation  (and the code) and there doesn't seem to be a parm for current day.

I also have to manually refresh the page when I select another day of the week.

**Comment by tech2serve** [comment]
On my default dev site: `?post_type=tsml_meeting` works.

I did append that to your domain ( to make `https://anchorageaa.org/?post_type=tsml_meeting`) and it still came up as Wednesday, so this doesn't appear to be a browser issue.

My first guess is to try clearing cache for the server, and refresh permalinks (Settings-->Permalinks-->Save Changes) and see if either of those steps help.

**Comment by AnchorageIntergroup** [comment]
Thanks so much for the quick response.  I tried and still have the problem but I was using a lite speed plug in,  I disabled the plug in and it seems to to working normally.
I'll test it again tomorrow to make sure.

When I press the zoom button on the page to launches zoom in the same browser tab, is there an option to launch in a new tab?  no rush just wondering?

**Comment by tech2serve** [comment]
There isn't an option for that. We tweaked it, but then found some didn't want it, some wanted a new window, and some wanted only a new tab. Bottom line, we're leaving it up users to control through their browsers.
