### ISSUE TITLE
PayPal username not working 

### ISSUE THREAD

**Issue by tribalboy3000** [code4recovery/12-step-meeting-list#309]
When I enter our group PayPal user name, it links to a blank PayPal page and not the correct group page.
![60E6DA2B-B346-44E4-86D3-4DB670621245](https://user-images.githubusercontent.com/2553727/113450845-55f72500-93c6-11eb-81a4-99e5509560a2.jpeg)
![EC371F28-529C-4319-BBAD-DA92D5E2E558](https://user-images.githubusercontent.com/2553727/113450847-57285200-93c6-11eb-8e03-516db78f2045.jpeg)
![665E5D7B-BAEF-463B-B8FF-715F7EAA91A9](https://user-images.githubusercontent.com/2553727/113450848-57285200-93c6-11eb-8bfe-1fc622dde50e.jpeg)

**Comment by tech2serve** [comment]
Pass me a link to the actual meeting, please.

**Comment by tribalboy3000** [comment]
https://www.aawidistrict04.org/meetings/third-legacy-group/

**Comment by tech2serve** [comment]
I confess I don't personally use this feature, but am pretty sure right now the issue is that you don't have the right PayPal page/username

<img width="1225" alt="image" src="https://user-images.githubusercontent.com/31904316/113455086-c5c1db80-93d7-11eb-98e2-c82321dbb932.png">

Let's start by confirming the correct PayPal.me user page.

**Comment by tribalboy3000** [comment]
It’s the correct PayPal email. I’ve tried 3 different emails and they all send back the same blank screen.

**Comment by tech2serve** [comment]
I suspect it is the correct email, but I suspect it isn't the correct PayPal username. 

Try to determine the PayPal account username with that email address, and put that in instead.

TSML uses the _PayPalUsername_ you enter to create a link of the form: `https://www.paypal.me/PayPalUsername`, that then opens in a new window. That is all it does.

In order for this to work, you have to have a valid user page at that link. Based on what I showed above, you don't have a valid page at that URL. 

So, you need to figure out the correct username, and you can test it by adding it to the `https://www.paypal.me` address and it should open up your donation page. Then move that _PayPalUsername_ to TSML.

**Comment by tribalboy3000** [comment]
This fixed it. You’re correct that we needed to create a PayPal.me page, and use that username versus the email. Thanks for your service!

**Comment by tech2serve** [comment]
Glad you got it to work. Electronic 7th Traditions are becoming increasingly important.
