### ISSUE TITLE
Meeting import CSV limited to Administrative role

### ISSUE THREAD

**Issue by charlesrbasin** [code4recovery/12-step-meeting-list#315]
We would like the Editor role to have permission to import meetings from a CSV file. We are reluctant to give out Administrator privileges to a volunteer who maintains the meeting list in an Excel file.

**Comment by tech2serve** [comment]
Let me research this further and I'll get back to you later today or tomorrow. I understand what you're asking for, but I thought we already supported it. Now I'm curious if it got lost at some point.

**Comment by charlesrbasin** [comment]
Any update on this issue?

**Comment by tech2serve** [comment]
My apologies for not getting back to you. We ran into a geocoding issue that hadn't to be the priority. 

I have confirmed that the editor role will let someone edit meetings and add new ones manually. They are not able to import (as you noted) csv files. The logic for this approach is that importing from other feeds or files provides the opportunity to write over the entire database. This is something TSML only allows an administrator to do. Our approach seems consistent with the roles established by Wordpress.

I'm willing to discuss your request with our other team members, but don't personally think it is a good change. It has not been requested by others. Nor do I find consistently overwriting the database to be a good practice, although others disagree with me on this.

An approach you might consider in the meantime is to keep your Wordpress TSML database as the true source of meeting information, then export to csv (i.e., Excel) for backups and other uses. Then you can give your volunteer editor access and they manage changes to meetings through TSML.

**Comment by 97eighty** [comment]
Feature not planned at this time. We'll revisit if additional requests come in.
