### ISSUE TITLE
Google Geocoding Not Working

### ISSUE THREAD

**Issue by lloy0076** [code4recovery/12-step-meeting-list#317]
**Describe the bug**

It seems the plugin is trying to use a Google API key even though I only use the Mapbox API key.

**To Reproduce**
1. Go to 'https://aa-stlawrenceny.org/new-site/wp-admin/post.php?post=2329&action=edit' (i.e. some meeting)
2. Enter an address
3. See error

![image](https://user-images.githubusercontent.com/1174532/115154079-057afb00-a047-11eb-9430-acedf92cc3e9.png)

The text object is:

```
{
  "status": "error",
  "reason": "Google gave an unexpected response for address <code>41 Court Street Canton NY 13617</code>. Response was <pre>stdClass::__set_state(array(\n   'error_message' => 'You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started',\n   'results' => \n  array (\n  ),\n   'status' => 'REQUEST_DENIED',\n))</pre>"
}
```

The address CANNOT be entered.

I'm trying to enter 41 Court Street, Canton, NY 13617 (i.e. https://www.google.com/maps/place/Canton+United+Methodist+Church)

It doesn't work for 9 East Main Street, Canton, NY 13617.

It DOES work for 3 1/2 East Main Street, Canton, NY 13617 but that was geocoded some time ago.

**Expected behavior**

It geocodes successfully.

**Screenshots**
See above.

**Desktop (please complete the following information):**
It is doing this on Firefox 86.04 and Chrome Version 89.0.4389.128 (Official Build) (64-bit) on Windows.

**Smartphone (please complete the following information):**
N/A

**Additional context**

This used to work - something changed.

PLUGIN VERSION appears to be 3.10.0
WP VERSION is 5.7.1

All updated.

I have tried WITH or WITHOUT new BETA API key in plugin's settings.

Note that I have worked in web development, programming and system administration for more than 25+ years (and I have coded WP plugins) so it is OK to use technical jargon with me if you need to request more info :)

**Comment by lloy0076** [comment]
I cannot remember uploading any Google Maps API key to the plugin; even so the Google API setting APPEARS to be blank:P

![image](https://user-images.githubusercontent.com/1174532/115154372-753db580-a048-11eb-9078-d49bbcb5ac30.png)

It is blank AFAICT but I haven't peeked at the DB underneath.

I have deleted BOTH mapbox and Google API keys by ensuring they are blank (highlight anything in the text box, click update), refreshed and gotten the "we need a key screen" and entered the mapbox key only.

MAPBOX's site claims it's seen no queries from our web-site which makes sense given what is being complained about.

**Comment by tech2serve** [comment]
Hi @lloy0076, 

There are a couple of things here, and yes it appears one is new issue we need to work quickly. The upgrade to Wordpress 5.7.1 seems to be breaking sites, and so if you can roll back Wordpress, it might fix things (although someone else reported it doesn't). 

You can read more in other issues and the FAQ, but TSML requires services for mapping and geocoding (two different functions, two different API keys). We currently give the user the option to use their own Mapbox key for mapping, but geocoding is still done through the Google.

The issue you're facing is with geocoding, not mapping. So, leave your Mapbox key in place and don't worry about it for now.

Something you can try that might help us find a quick solution to the new geocoding issue is to return on the Beta API Gateway.  That will bring the geocoding requests through us and let us see a few more details with what is being passed to Google.

**Comment by lloy0076** [comment]
I would prefer not to have to use any of Google's services if at all possible - or any that might require an agreement to pay on credit card; is there any way to avoid the Geocoding completely?

**Comment by tech2serve** [comment]
Hi @lloy0076--

Please try now, and tell me the results.

**Comment by lloy0076** [comment]
So it seems to be working using the beta gateway.
