### ISSUE TITLE
Cannot add new meetings - Get Google error message on attempted new additions only

### ISSUE THREAD

**Issue by aavictoria99** [code4recovery/12-step-meeting-list#318]
I am importing via normal CSV that I have used successfully many many times with no problems. Now when I do it I get the error message below from Google for new additions to the file only. I cannot add manually either. The original meetings load and display with no problems.

Latest Firefox, Latest Wordpress and Plugin.

I have Billing enabled in my Google Cloud account

Regards
Andy K

(object) array(
   'error_message' => 'You must enable Billing on the Google Cloud Project at https://console.cloud.google.com/project/_/billing/enable Learn more at https://developers.google.com/maps/gmp-get-started',
   'results' => 
  array (
  ),
   'status' => 'REQUEST_DENIED',
)

**Comment by tech2serve** [comment]
When did you upgrade to Wordpress 5.7.1? Did that coincide with this issue?

**Comment by aavictoria99** [comment]
Yes. I think it did

**Comment by aavictoria99** [comment]
The problem seems to be with the way the plugin interacts with Google Maps. If I try and enter a new meeting manually, when I type a legitimate address the plugin does not do autocomplete. If I enter the address nothing further happens and I cannot publish the new meeting.
Regards

**Comment by tech2serve** [comment]
Please try now, and tell me the results.

**Comment by aavictoria99** [comment]
Hooray, seems to be working now. Thanks so much.

Regards
Andy K

**Comment by tech2serve** [comment]
Great to hear. My apologies for the inconvenience.
