### ISSUE TITLE
Implementing json feed from one WP-TSML site to feed another WP-TSML site

### ISSUE THREAD

**Issue by aanecswebmaster** [code4recovery/12-step-meeting-list#319]
The  import/settings page has this statement: "Data Sources ..,. can be used to aggregate meetings from different sites into a single master list."  We have 3 websites using tsml.  Two intergroups that keep meeting data for parts of our state, and a state website that covers meetings for exactly the same geographic area.  We want the state site to simply import data from the two local sites.

I see information for how the master state website would pull data from local sites, but I do not see how the local sites provide the data.  I see an authorized app setting where the local sites allow Meeting Guide to pull the data. But not the same facility to allow authorizing others to pull.
thanks
ross

**Comment by tech2serve** [comment]
Hi Ross,

If I am understanding you correctly, you should be able to change sharing to public on the sites providing the feeds:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/31904316/115796308-3d5fa680-a397-11eb-8470-7939835ca8e9.png">

The link at Public Data Source is what the receiving side would use when adding a data source.

Does that make sense? Did I read your issue correctly?

**Comment by aanecswebmaster** [comment]
That is exactly the information I needed.  Thanks. (So obvious after seeing it!)
Another question.  
There is some overlap in our two data sources, i.e. same groups/meeting found in both sources.
How is that handled at the parent/receiving site?

**Comment by tech2serve** [comment]
> Another question.
> There is some overlap in our two data sources, i.e. same groups/meeting found in both sources.
> How is that handled at the parent/receiving site?

That is a good question that I've not researched this portion of the code extensively before. Here is what I *think* would (should?) happen.

If the slug is the same for both meetings/groups, the importer should see them as the same. If not, the importer will probably duplicate them.

However, I probably need to research this more. If you test and determine the answer before I can get to this, please let me know :-)

**Comment by aanecswebmaster** [comment]
Thanks. And I think it would be very low priority for you to investigate further. When we implement, we will just see what happens to our duplicates. And report back here on what we see.

**Comment by joshreisner** [comment]
Going to close this ticket because the original topic was addressed.

But to answer the second question, the plugin doesn't try to filter duplicates. The rationale for being able to import from another website is that it allows you to divide your area of responsibility, so the site doing the importing should remove their local copy of the meeting.
