### ISSUE TITLE
How to Show Zoom and Reopened for same meeting

### ISSUE THREAD

**Issue by trivalleyaa** [code4recovery/12-step-meeting-list#320]
**Is your feature request related to a problem? Please describe.**
Some of our meetigs are offering Zoom meeting simultaneous with Physical location (reopened) meeting. [...]

**Describe the solution you'd like**
Can the blue online tag be made into a feature box in the list of meeting types?

**Describe alternatives you've considered**
We will add the suggestion ***REOPEND*** and include the note about the requirements for the LIVE meeting as well as stating it is a zoom meeting also.

**Additional context**
Any suggestions to share the simultaneous without loading the title would be appreciated.

**Comment by tech2serve** [comment]
We have some changes coming soon in how the plugin handles attendance options. *Online* will be removed from types and handled as a new data type. It will be determined by the same logic (i.e., `conference_url` must be populated with a valid link) .

Hopefully this will provide the requested additional flexibility on the front end. 

We don't have a good way to flag a meeting as reopened, and I'm not sure we'll try to implement one. A basic premise of these tools is that if the meeting shows up in the list, it is open and active. If not, it isn't.

Hopefully I understood your requests?

**Comment by trivalleyaa** [comment]
Sure that will answer the questions from my group. Thanks for your fast response.
