### ISSUE TITLE
Copy / Duplicate a meeting

### ISSUE THREAD

**Issue by heatherc-dev** [code4recovery/12-step-meeting-list#321]
Hello,

It was brought to my attention that there is now no way to copy/duplicate an existing meeting in order to make subtle changes and republish. I also heard there is a plugin available for that. Is it possible to duplicate existing meetings or is there a plugin for that?

Thank you,

Heather C

**Comment by brianw-area24** [comment]
The 12-step-meeting-list (TSML) does not have a duplicate meeting feature. I did a quick look, and do see a few plugins that claim to do that. If you use one of these, you'd want one that will duplicate a custom post.

Another way you could do it would be use the "Import & Settings" page
- Go to this page, and download your meetings in CSV format
- Modify this exported file, and delete all the meetings except the ones you want to duplicate
- Modify the ones you want to duplicate with the desired changed
- Go back to the Import & Setting page, and Import your CSV file, making sure "don't delete anything" is selected

I'm not a fan of using the Import CSV feature to routinely modify existing meetings, this would be a way to duplicate existing meetings, especially if you want to duplicate a few meetings.

Brian W

**Comment by heatherc-dev** [comment]
Thank you so much Brian. Could you happen to name any of those plugins you
referred to? My office manager wants to get one I believe. Just want to
make sure I have the correct ones.

Heather




Heather Cavanaugh
Jawsbanana Creative SEO
(971) 328-1649
Schedule 15 min Chat <https://calendly.com/hlynne-cavanaugh/15min>
***@***.***
jawsbanana.com

**Comment by petermixt** [comment]
[Duplicate meetings](https://essential-addons.com/elementor/docs/duplicator/):  Is a very handy addition to our systems as we have groups that meet Monday thru Friday and my data volunteers appreciate this feature.  Be sure your webmaster sets it up correctly.
-pds

**Comment by brianw-area24** [comment]
I'm not comfortable naming any plugin because I don't have experience with using any of them. I just did a search for "wordpress plugin duplicate post". I tend to be a minimalist when it comes to plugins, the site I maintain only has 3 active plugs, 2 of which are maintained by Code for Recovery.

Brian W

PS, I'm going to close this issue, but can always re-open it if necessary

**Comment by heatherc-dev** [comment]
Thank you, Brian. I am the webmaster for neflaa.org since 2018. We do not
use Elementor on the site currently.


Heather Cavanaugh
Jawsbanana Creative SEO
(971) 328-1649
Schedule 15 min Chat <https://calendly.com/hlynne-cavanaugh/15min>
***@***.***
jawsbanana.com
