### ISSUE TITLE
Adding New Meeting Descripters

### ISSUE THREAD

**Issue by trivalleyaa** [code4recovery/12-step-meeting-list#323]
**Is your feature request related to a problem? Open physical location meetings have been not getting attendees so some have closed down again.

**Describe the solution you'd like**
Add a descripter into the choices to describe meeting such as:
Online (I think you are already planning to do this
In Person Only - some meetings do not have internet access so can only be open for physical attnedees
In Person w Online - a hybrid meeting that is open physically but also open to people who choose to attend using Zoom (or similar software)

**Describe alternatives you've considered**
We try to get the word out using our Intergroup and word of mouth, plus our website, several people only use the Meeting Guide and are not aware.  We also use a description in our Meeting Notes, however, several people are getting confused.

**Additional context**
This is the best app and helps us ALOT. Your group is doing a great job and we REALLY appreciate your service.

**Comment by tech2serve** [comment]
Duplicates #312
