### ISSUE TITLE
Unable to update location, address or region

### ISSUE THREAD

**Issue by itsdan89** [code4recovery/12-step-meeting-list#325]
**Describe the bug**
As of last week we have been unable to make and publish any changes with the plugin. 

**To Reproduce**
As soon as we change the location, address or region the option to "publish" goes away. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Tried multiple browsers and both windows and MAC

**Additional context**
I suspect some sort of issue with the google API key but I'm not sure what. More and more meetings are starting to meet in person and we arent able to get them published on the website.

Any help is greatly appreciated. Thanks in advance!

**Comment by tech2serve** [comment]
What version of the plugin are you using? If v3.10, what setting do you have for geocoding?
<img width="287" alt="image" src="https://user-images.githubusercontent.com/31904316/116437503-20055f00-a813-11eb-801e-be20774e01c9.png">

What version of Wordpress?

What is the website URL?

Please open a javascript/debugging console and look for any errors when you enter the address.

**Comment by tech2serve** [comment]
Closing due to no response from OP
