### ISSUE TITLE
Last Gutenberg 10.5.3 update crashing meeting list page

### ISSUE THREAD

**Issue by Carlsans** [code4recovery/12-step-meeting-list#327]
Got back to the old version and it works.
![image](https://user-images.githubusercontent.com/46719148/116768195-c5caf080-aa02-11eb-806e-ca9c131a8175.png)

**Comment by tech2serve** [comment]
You're using the plugin and not the version of Gutenberg distributed with Wordpress?

**Comment by Carlsans** [comment]
It's the plugin. I suppose I'll just uninstall it.

**Comment by tech2serve** [comment]
I think that is best. I was not able to read the error above, but we're not experiencing any issues with the stock Wordpress Gutenberg.
