### ISSUE TITLE
Bulk change "Updated" Date on meetings

### ISSUE THREAD

**Issue by NevisIsland** [code4recovery/12-step-meeting-list#328]
Would like to bulk change the "updated" dates at the bottom of each meeting. I tried doing a search a replace on the database, but am not sure what table the information is in. Would prefer to use Better Search and Replace than MySql.

Thanks, BTW April marked 5 years since I began using this plugin. HUGE growth since then.

**Comment by tech2serve** [comment]
Hi @NevisIsland,

TSML does update that date when changes are made to the meeting and published again.

Perhaps you can explain your use case in more detail? I'm not understanding why someone (but hey! I'm just me :-) ) would want to bulk update those dates if nothing has changed?

**Comment by NevisIsland** [comment]
Don't laugh, but I wanted them all to show the same date as my sobriety date....hey we are not a glum lot...just nuts. :)

**Comment by tech2serve** [comment]
I have not experimented with this, but you might be able to use the CSV import process to set the updated date. Frankly, I'm not positive if our importer code honors this, but you can try it. Maybe best of a test site first.

Good luck.

**Comment by NevisIsland** [comment]
Thanks for your time and help.
