### ISSUE TITLE
Meeting List plugin not working on WP 5.7.1

### ISSUE THREAD

**Issue by rockert221** [code4recovery/12-step-meeting-list#332]
**Describe the bug**

**To Reproduce**
1. Go to 'https://meetings.aalakesumter.com/'

**Expected behavior**
Page should show meeting list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**
This page was working fine until recently. Please advise as to repair steps.

**Comment by tech2serve** [comment]
I'm going to take a stab and guess that you have the Gutenberg plugin installed. We think that plugin may have a bug in it that is messing with TSML. We're monitoring the situation.

Disable Gutenberg plugin if you have it and see if your issues clear up.

BTW, I just looked at your site, and saw the meeting list displayed as it should, so  I'm not sure if you already discovered that?

Please let me know what you find out.

**Comment by rockert221** [comment]
You are exactly right. I turned off a few extraneous plugins and Gutenburg was one of them. After that things worked OK. Now the Meetings App is not showing local meetings! It was before I dug around. Suggestions?

Ron Ockert
email: ***@***.******@***.***>

**Comment by tech2serve** [comment]
What do you mean by "local meetings" and "Meetings App"?

**Comment by rockert221** [comment]
By meetings app, I mean the Meeting Guide app for Android or iOS that pulls data from the meetings page (TSML). By local I mean that our nearest town's meeting are not showing in the App. Perhaps an issue for another forum.


Ron Ockert
email: ***@***.******@***.***>

**Comment by tech2serve** [comment]
Probably not related (at least I hope not). 

While logged into your website, navigate to `https://meetings.aalakesumter.com/wp-admin/admin-ajax.php?action=meetings` You should see a complete list of your meetings.

**Comment by rockert221** [comment]
Thanks for your help.

Ron Ockert
email: ***@***.******@***.***>

**Comment by tech2serve** [comment]
You bet. 

Assuming you saw a complete list of meetings, then you should contact GSO (appsupport@aa.org) if you're not seeing meetings in the Meeting Guide app.

Cheers,
