### ISSUE TITLE
District does not auto-populate when entering new meetings for an existing group

### ISSUE THREAD

**Issue by ebart455987** [code4recovery/12-step-meeting-list#334]
**Is your feature request related to a problem? Please describe.**
We often enter multiple meetings for the same group, but the District Field does not auto-populate to the Contact Information  of a Group  section. The district must be picked every time a new meeting is added for the same group location.

**Describe the solution you'd like**
Have the district auto populate the district number based on previous entries for that group. 

**Describe alternatives you've considered**
Review all other meetings for that group, hoping to find a district listing. If not found then go to another website (e.g. www.neta65.org) look up address determine district and enter it in TSML. 

**Additional context**
To clarify further; once a district number is added to a group, all meetings for that group should reflect that district.

**Comment by tech2serve** [comment]
Hey @ebart455987,

It would help us if you could keep the title of the issue short and succinct, and took the time to fill out the rest of the request.

Thank you.

**Comment by ebart455987** [comment]
I apologize for my text, I’ll keep it in mind for the future.  I thought that was the only field available. Do you need any more information?

**Comment by tech2serve** [comment]
I’ve edited your issue and moved the text you had in the Issue line to the problem description in the comment. Please read it and see if I captured your concerns completely and correctly.

There are three other headings in the template that can be filled out. Please look and those and edit as appropriate. The most important one is for you to describe the solution you’d like to see. What gets entered here really helps us have a conversation about how the plugin is being used by you and others.  Users like you use the plugin on a daily basis and have the best insight into how it works for your needs. As a developer, my actual use of the plugin is pretty limited.

The plugin *should* apply group information to all meetings at a location if the option “Apply this group to all meetings at this location” is checked. If you tried that, and you’re not seeing that behavior, then we may have a bug, an issue with your site, or something where we need to improve the feedback.

Thank you.

**Comment by ebart455987** [comment]
Yes, the issue persists, the District does not save to the Group.  When adding a new meeting, the District field is not listed under the "Location Information" section.  It's under the "Contact Information" section, so the “Apply this group to all meetings at this location” option is not available for that section.

**Comment by joshreisner** [comment]
better late than never! a fix will be part of the next release `3.14.12`
