### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by barryjost** [code4recovery/12-step-meeting-list#336]
added pdf generator. can't find meeting list info. reverts to home page
Coigaa.org please help

**Comment by tech2serve** [comment]
I assume you're talking about the plugin 12 Step Meeting PDF. That plugin is maintained by a different author and you'll need to contact him through his support site.

If you're talking about 12 Step Meeting List plugin PDF page, please provide specific steps you take to reproduce the issue, along with a run down of your website versions and other info, and we can reopen the issue.

Thanks.

**Comment by barryjost** [comment]
We are running Gutenberg 5.7.1
What happens is that the meetings page goes to the home page. I cannot connect or find the meetings list. I would be ok to reinstall the meeting list plugin and start from scratch. I removed the pdf plug in. We are without access to the meetings don’t want to leave it like this.

Barry Jost

**Comment by tech2serve** [comment]
If you're running the Gutenberg plugin, please disable it. We think the latest version of Gutenberg has a bug in it that is messing with TSML.

**Comment by barryjost** [comment]
Thanks that fixed it!
