### ISSUE TITLE
No communication between website and meeting guide App

### ISSUE THREAD

**Issue by RBIWebsite** [code4recovery/12-step-meeting-list#337]
We had an old Linux website that worked fine.
We launched a WordPress site using the TSML plugin. The app has not updated from the site since. readingberksintergroup.org is our URL.
GSO hasn't answered my request to respond if there is something we have to do on our end when we changed the site files. (the URL is exactly the same as it was) Is there a setting i need to change or update on the plug in? 
A local area website was also pulling our data once a day. They can can longer do that, either.

**Comment by brianw-area24** [comment]
While the URL of your site hasn't changed [readingberksintergroup.org/](https://readingberksintergroup.org/), the URL of the feed that was used by Meeting Guide, and by the other local site, would have changed. Therefore, you need send both these entities a new URL to use.

First thing you need to do is find your new URL. In doing that, you need to make a decision whether to make sharing "Restricted", meaning it needs a key in the URL, making it harder to guess the URL, or "Open", which means there is no Key, and the URL can be calculated based on the URL of the site.

To use "Open" Sharing
1. Go to the "Import & Settings" page
2. Scroll down until you see "Sharing" in the left hand column
3. Select the option "Open" under sharing
4. Scroll down a little farther, and you'll see a link to "Public Data Feed"
5. Right click on this link, and select copy link

To use "Restricted" Sharing
1. Go to the "Import & Settings" page
2. Scroll down until you "Sharing" in the left hand column
3. Select the option "Restricted" under sharing
4.  Scroll down a little farther, you'd see a section titled "Authorized Apps"
5. Add one or more Authorized Apps, by typing a name into the box, and clicking the "Add" button. On the site I maintain, I've created a separate Authorized App link for each place that I give a feed, however, you could do just 1, and send that same URL to each place. Here's what my site looks like: 
![Screen Shot 2021-05-10 at 10 52 20 AM](https://user-images.githubusercontent.com/55821195/117687894-e0793400-b17d-11eb-9ba7-477115febeea.png)
6. Right click on one of the links and select copy link

Once you have the link for Meeting Guide, send it to GSO, letting them know this new URL will replace the old one they had for your site. If you create a separate link for the local area website, you'll need to go back into the Import &  Settings page, and copy the correct URL when sending them an email about the new URL. Just make sure that if you create more than 1 URL, that you send the right one to the right place.

There's a lot here, hopefully it will point you in the right direction.

Brian W

**Comment by joshreisner** [comment]
I think this can be safely closed as the discussion moved here: https://github.com/code4recovery/12-step-meeting-list/discussions/478 and it sounds like it's at least partly working again.

**Comment by RBIWebsite** [comment]
Agreed, thanks for all u do!👍🏻🤗

**Comment by RBIWebsite** [comment]
Hey Josh, I updated meeting details 2 days ago, and for some reason it is updating on the website, but not showing up on the app again. is this something I'm doing wrong, or a bug that needs to be worked out? Should I open another discussion thread since the last one is closed?  -------- Original Message -------- Subject: Re: [code4recovery/12-step-meeting-list] No communication between website and meeting guide App (#337) From: Josh Reisner ***@***.***> Date: Fri, August 06, 2021 8:03 am To: code4recovery/12-step-meeting-list ***@***.***> Cc: Steve P ***@***.***>, Author ***@***.***>   I think this can be safely closed as the discussion moved here: #478 and it sounds like it's at least partly working again. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
