### ISSUE TITLE
WordPress 5.7

### ISSUE THREAD

**Issue by district6wc** [code4recovery/12-step-meeting-list#339]
I would like to update the WordPress version from 5.5 to 5.7.  Is the 12-step-meeting-list compatible with the latest version?

**Comment by brianw-area24** [comment]
Yes, you shouldn't have any problem with this upgrade. Many sites have already done this upgrade, and they are working great.

Where we have seen issues is sites that are running the Gutenberg plugin. If you are running that plug, then we recommend that you disable it.

I'm closing this issue, however we'll reopen it if necessary.

Brian W
