### ISSUE TITLE
Ability to set custom Mapbox style

### ISSUE THREAD

**Issue by jtwg** [code4recovery/12-step-meeting-list#347]
**Is your feature request related to a problem? Please describe.**
The `streets-v9` Mapbox style is nice, but for some layouts I'd like to be able to use other choices.

**Describe the solution you'd like**
A settings field for users to put in the Mapbox style they want to use, e.g. `dark-v10`.

**Describe alternatives you've considered**
I tested some of the styles by editing the minified `.js` file, but that's not really a sustainable option.

**Additional context**

**Comment by tech2serve** [comment]
I'll add this to our list for discussion by the group. TBH, I'm not sure the priority will be real high.

**Comment by jtwg** [comment]
Thanks, @tech2serve  - I suspected that might be the case so I took the work on myself. Here is my PR:

https://github.com/code4recovery/12-step-meeting-list/pull/348

**Comment by tech2serve** [comment]
Closing as the PR has been merged and this feature should be in the next release.

Thanks again!
