### ISSUE TITLE
Ability to sort meeting type by Virtual Meeting

### ISSUE THREAD

**Issue by COMPUMEC** [code4recovery/12-step-meeting-list#353]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to sort meeting list by Virtual Meetings

**Describe alternatives you've considered**
We currently have a separate list for virtual meetings.

**Additional context**
https://csoaamaine.org/meetings/

Having the ability to sort the displayed meeting list by virtual meetings would be a great asset to us. Also a way to have the AA Meeting App have the ability to sort this way as well would be a big help to those looking for virtual only meetings. I think virtual meetings are here to stay. Thank you and I look forward to your reply!

**Comment by Grateful-Viv** [comment]
It may not be the most ideal answer, but I created a menu item for online meetings that simply uses this link: 
/meetings/?tsml-day=any&tsml-type=ONL

You should add your online meetings with your other meetings.  As long as the URL or Phone number is filled out in the expected format, it is considered an online meeting.

Then you can filter just the online meetings to display.

**Comment by tech2serve** [comment]
Hi @COMPUMEC,

As @Grateful-Viv suggested, TSML provides ways for both the users and the admins to filter by online meetings. In a future version (hopefully soon) we’ll expand that capability and make it easier for users to quickly filter by online or in-person meetings. 

Same with the Meeting Guide app (which is controlled by GSO, and not Code for Recovery). A user can filter by the types of meetings (which include online) they want to see if any of those types are within their area.

I’m going to close this as I *think* it answers your root issue. If I’m wrong, let me know and I’ll address it more.
