### ISSUE TITLE
Padding Zero Causes Issues with Some Sidebars

### ISSUE THREAD

**Issue by lloy0076** [code4recovery/12-step-meeting-list#355]
https://github.com/code4recovery/12-step-meeting-list/blob/2f8f64a517d5eac545bb5d64bed6fa01102019fe/includes/widgets.php#L35

The hard coded `padding: 0` overrides some themes' sidebar CSS and thus makes the Upcoming Meetings widget not conform to style.

![image](https://user-images.githubusercontent.com/1174532/120154337-c7343800-c1bd-11eb-8793-2bf32c246aaf.png)

So in the above image on 3.10.0 I've EVILLY commented out the `padding: 0` on that line and it looks OK.

Now I've put it back and you can see how the `Upcoming Messages` header moves to the left :(

**Comment by lloy0076** [comment]
![image](https://user-images.githubusercontent.com/1174532/120154538-fea2e480-c1bd-11eb-9979-989d95e7908f.png)
 ^^ it would help if I uploaded the second image.

**Comment by lloy0076** [comment]
NB. I could, of course, override it again in my theme's additional CSS but that seems messy to me.

**Comment by 97eighty** [comment]
@lloy0076 Have you tried your fix on other themes to see how this change might affect others?
