### ISSUE TITLE
No Map on Website

### ISSUE THREAD

**Issue by ncd12aa** [code4recovery/12-step-meeting-list#357]
**Describe the bug**
On each specific meeting page on the website the map no longer appears, and the "Get Directions" link doesn't work. The Meeting Guide app does not seem to be affected.

**To Reproduce**
1. Go to 'https://ncd12aa.org/meetings/'
2. Click on 'any listed meeting'
3. See no map
4. Click on "Get Directions"

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Firefox
 - Version: 88.0.1

I created a new mapbox api key and updated. This did not solve the issue.

**Comment by ncd12aa** [comment]
Update:

I enabled wp_debug. Here is the error message:

Fatal error: Uncaught ValueError: Unknown format specifier "n" in /home/rvqsc20767p5/public_html/wp-content/plugins/12-step-meeting-list/templates/single-meetings.php:247 Stack trace: #0 /home/rvqsc20767p5/public_html/wp-content/plugins/12-step-meeting-list/templates/single-meetings.php(247): sprintf() #1 /home/rvqsc20767p5/public_html/wp-includes/template-loader.php(106): include('/home/rvqsc2076...') #2 /home/rvqsc20767p5/public_html/wp-blog-header.php(19): require_once('/home/rvqsc2076...') #3 /home/rvqsc20767p5/public_html/index.php(17): require('/home/rvqsc2076...') #4 {main} thrown in /home/rvqsc20767p5/public_html/wp-content/plugins/12-step-meeting-list/templates/single-meetings.php on line 247

**Comment by joshreisner** [comment]
That looks like a bug! 

In Meetings > Import & Settings, on the right side, do you have Meeting / Group Contacts > Public? Try setting them to Private for now and see if the map comes back.

**Comment by ncd12aa** [comment]
That worked! Thanks!
