### ISSUE TITLE
Meeting Sorting

### ISSUE THREAD

**Issue by GCITechSC** [code4recovery/12-step-meeting-list#359]
Hey, Meeting Sorting for our Intergroup is working great by auto populating to the right day.  

Is there anyway to _add__ to that and make it pull up by the current day _and_ current time? 

Thanks guys for all you do and what you have helped me with this far.  

Scott

**Comment by tech2serve** [comment]
Hi Scott,

If I understand your question right, there are some options you can add to the via the URL or `functions.php`. 

Please check out the [plugin's FAQ](https://github.com/code4recovery/12-step-meeting-list/wiki/Frequently-Asked-Questions#can-i-change-the-default-sort-order-on-the-meeting-list-page) for a specific option to change the default sort order.

Let me know if that doesn't answer your question and I can reopen the issue.

**Comment by GCITechSC** [comment]
I do get that how to change the default sort type, but wondering if
changing it to day and time will make the meeting list pull up by the
current time.

Thanks

**Comment by tech2serve** [comment]
With our current front end, I do not believe it will do that. Our future front end (TSMLui) will do that.

We are offering TSMLui as an experimental front end to TSML through the short code `[tsml_react]`. 

Alternatively, if you trying to show "upcoming" meetings, TSML includes a widget that may do what you want.

**Comment by joshreisner** [comment]
you can link to upcoming meetings today, ex https://aasanjose.org/meetings?tsml-time=upcoming

**Comment by GCITechSC** [comment]
Ok, where's the widget?

**Comment by tech2serve** [comment]
Appearance-->Widgets. 

The widget for TSML is called "Upcoming Meetings". You should be able to add that to a variety of different places.

Or, you can do as Josh suggested. :-)
