### ISSUE TITLE
Data validation/guidance when submitting a meeting change request

### ISSUE THREAD

**Issue by namdrino** [code4recovery/12-step-meeting-list#361]
A lot of times when I receive meeting change requests via the "Request a change to this listing" feature the user will fail to include all the pertinent details (e.g. does this update apply to all meetings, only in person meetings, only Zoom meetings, etc. OR does this update apply to all meeting days or just certain days, etc.)

The suggestion would be to have change listing form populate existing meeting details (times, days, type, etc.) and force the user to ensure all fields are updated before the user can submit the request.

I have, in the meantime, added some text via CSS to instruct the user to include all the relevant details when submitting a request.

**Comment by kiyote33** [comment]
I didn't see this issue yesterday when I added #362 Enhance the 'Request a Change to this Listing' feature.  They both ask for the same thing.  I'm in the final stages of stages of a prototype development which may point a way forward. Maybe we can merge these two items.

**Comment by namdrino** [comment]
Excellent! Thank you.

**Comment by tech2serve** [comment]
Although this issue was submitted first, @kiyote33's issue has much more detail.

I'm going to close this as it effectively duplicates #362 and we'll track via it.

Thank you both!
