### ISSUE TITLE
Add Beginner Meeting type

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#363]
Please add Beginner as a type. This is a common type that should be included. 

It should be synced with the A.A. Meeting Guide App, and I should not have to enter it as a custom type.

Yes, there already is newcomer, but it's not the same.

**Comment by tech2serve** [comment]
How are you distinguishing the two?

The code for the current type is `BE` and the label is `Newcomer`. This makes me assume the definition was changed at some point, but I honestly don't know for sure.

I admit in the regions I've gone to meetings, `Beginners` is the more commonly used label, but I have seen and heard both used.

**Comment by Grateful-Viv** [comment]
Can the label be changed to Beginners? 

I don’t actually distinguish between the two, as I’ve never used the term newcomer. It might be a regional thing. Most of the meetings I gone to have been in the DC area and southern Delaware.

**Comment by tech2serve** [comment]
You can use a custom type to change the label for your site. 

I will bring up the issue with GSO regarding possibly changing the label to reflect both.
