### ISSUE TITLE
Need a bulk method to add all meetings to a District

### ISSUE THREAD

**Issue by websantafeAA** [code4recovery/12-step-meeting-list#364]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tech2serve** [comment]
This feature is provided via a csv import. Use the template in the plugin's Import & Settings page as an example document:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/31904316/120928920-efcb9e80-c6a3-11eb-975e-e295bac447dd.png">

If you run into trouble with this, let us know and we can try to help.
