### ISSUE TITLE
Yoast and Archive

### ISSUE THREAD

**Issue by GCITechSC** [code4recovery/12-step-meeting-list#367]
Hey all,

I just did some searching on here, and I see that Yoast has been problematic as an SEO, does that still remain the case?  I'm using Elation theme for aacolumbia.org, and just recently seeing that the meeting title comes up as "Archive" on the tab.  I've seen the other plug-in fix for that, but curious if it's really related still to yoast.  If it is, do you all recommend a "better" SEO plugin?  

As always I appreciate everything you guys do and your help.

**Comment by GCITechSC** [comment]
And I have tried the Archive Title plugin, no joy.

**Comment by tech2serve** [comment]
I would assume so as we've not really done anything different. As far as the meeting title page, issue #271 provides some suggestions and customizations you might try to resolve that issue. It is theme specific (and only a small number at that) so we've not tried address it.

We don't offer specific suggestions for SEO plugins. Just don't have the time to research and test them. :-)

Are you a member of TIAA Forums? You might open a topic there to converse with others using the TSML to see if they have found a good alternative to Yoast.
