### ISSUE TITLE
Settings Option To Switch User Interface

### ISSUE THREAD

**Issue by brianw-area24** [code4recovery/12-step-meeting-list#368]
I would like to make it easier for WordPress users to use the new tsml-ui frontend. As an alternative to using a shortcode on a page, I'd like to have a setting on the Import & Settings page where the user could switch back and forth between tsml-ui, and the plugin's legacy interface.

Then on the archive-meetings page, it would check which frontend is chosen. If tsml-ui is chosen, it would simply output the top widget code, next it would output the code generated by the shortcode, and lastly, it would output the bottom widget code.

This would be a good next step in encouraging people to use tsml-ui. For now, the default behavior would be to use the legacy UI, therefore new sites would use legacy for now. However, we may want to change this up sometime in the future...

**Comment by Grateful-Viv** [comment]
If I may add a few comments here, I like the idea of using the TSML UI as the front end once it’s ready, but would like to keep the plug-in front end for an easier way to find and edit meetings for the admin. Using the meeting dashboard is not the easiest way to find the meetings to edit. It can only sort by meeting name, day and time. Yes, can do a search, but it’s so much faster to go to the plug-in front end to find the meeting you’re looking for. 

As far as the widgets you mention, are you suggesting they could work with the UI, such as the html for Meeting Top, Meeting Detail Bottom?

**Comment by joshreisner** [comment]
I think it should default to use the latest TSML UI, but allow the user to select another version, which can be gotten from here:

https://data.jsdelivr.com/v1/package/gh/code4recovery/tsml-ui

default: `https://cdn.jsdelivr.net/gh/code4recovery/tsml-ui/public/app.js`

versioned: `https://cdn.jsdelivr.net/gh/code4recovery/tsml-ui@1.0.1/public/app.js`

**Comment by brianw-area24** [comment]
Yes, I was thinking a selection of 3 options for now, of course the wording could change
1. TSML Plugin - legacy
2. TSML UI - beta
3. TSML UI - stable

**Comment by joshreisner** [comment]
That might be simpler than what I had in mind with listing out the version numbers, but that could work too.

**Comment by kiyote33** [comment]
@joshreisner Do you foresee TSML_UI supporting Google Maps, or is there a reason it can't support Google?

**Comment by joshreisner** [comment]
@kiyote33 i don't think TSML Ui will ever support google maps. adding another map provider would make the javascript bundle too big

**Comment by kiyote33** [comment]
OK. I'll work with that...

**Comment by kiyote33** [comment]
Refactor Settings & Import admin page. Split non-import settings into their own Settings page and maintain Import settings in a Import/Export page.

**Comment by kiyote33** [comment]
With the ability for local admins to be able to toggle between TSML and TSML UI, it would be nice to have both a Mapbox token and/or Google key, if they are available. Is there any reason we shouldn't allow it?

**Comment by joshreisner** [comment]
just seems like it could add unnecessary complexity. if you are using the TSML frontend and have both google maps and mapbox keys entered, which option will the interface choose?

**Comment by kiyote33** [comment]
Hopefully the first one that works. In my dev environment, mapbox works for TSML UI but not TSML.  It's the reverse for Google, where Google works well for TSML but not TSML UI. When thinking of the end users, they may find it a little frustrating to have to change the mapping key every time they want to experiment with the new UI.

**Comment by joshreisner** [comment]
Hm, but Mapbox works fine for TSML - here's an example: https://aaboston.org/meetings/first-things-first-2

**Comment by joshreisner** [comment]
looks really good! the information density is very different on the import / export vs other pages. to my eye, the import / export looks like it fits the browser better. so my recommendations would be:

1. only have two pages, and make them both top level. so the left sidebar would read:
* meetings
* add new
* regions
* districts
* import / export
* settings
2. with two pages you would not need the tabs anymore (although nice job using wordpress's native tabs here!)
3. on the settings page, i would have all the descriptions be expanded (so they don't need to be collapsible anymore)
4. don't need the "12 step meeting list settings" title
5. move the logo inside the about box
6. are we ready to drop the "feed sharing" option entirely?
7. settings page could be three columns, like the import / export page is

**Comment by joshreisner** [comment]
Ok thanks @kiyote33 ! I don't feel strongly, but the reason I suggested a single navigation menu is that I know there are sites that only update their meetings by reimporting. So having two navigation steps adds some friction for them to get to that screen.

You may also then want to keep the left menu option "Import & Settings" so they know they need to click there to get to the import screen.

**Comment by kiyote33** [comment]
I think we are on the same page, although I was thinking Two tabs with the default on **Settings**. Could  put the default on **Import Export**, or maybe add a setting so the admin can pick the default.  Of course, once we do something like that then they will want every little item to be configurable, so better we select the default and go with that.

**Comment by kiyote33** [comment]
**Revision #2 - Two Tab Preview** defaulting to the Import Export tab
![image](https://user-images.githubusercontent.com/57125427/158488259-e12dd731-338f-4d27-b310-cce885258f52.png)
![image](https://user-images.githubusercontent.com/57125427/158488339-cde56d3a-ce04-492d-b45d-ca3512f0bf4a.png)
Questions/Suggestions???

**Comment by joshreisner** [comment]
Changes look great thanks! 

There's a little bit of a hierarchy problem on the fields now, due to my suggestion about removing the collapsible details. It's fine with me if you want to return to the way it was, or otherwise I think we should try to visually regroup the info. One way you might do this:

* bold the titles, eg "Distance Units"
* reduce space between the title and description to, idk, 10px? 8px? and between description and field to about the same or slightly less?
* add space between the bottom of the field and the next field (maybe about 20px?)

Maybe also make the tab Import / Export or Import & Export?

**Comment by tech2serve** [comment]
"Mapping" gets renamed to "Mapping and Geocoding"?

**Comment by kiyote33** [comment]
Revision #3 Review - Settings Tab Section Rendering. No change to Import / Export tab.
![image](https://user-images.githubusercontent.com/57125427/158516539-5ac8ef71-968e-431f-b485-3c243f0eb9c5.png)
As usual, feedback is welcome!

**Comment by joshreisner** [comment]
i think it would look more consistent to try without the gray rounded rects - i think you could just use margins to group the fields with their titles and descriptions.

**Comment by kiyote33** [comment]
Rev #3b - How's this...
![image](https://user-images.githubusercontent.com/57125427/158522823-f7bd5022-9d26-4f11-88f0-b3894056dd14.png)

**Comment by joshreisner** [comment]
the problem is not that they were rounded. it’s that they’re not standard to wordpress or our other ui screens. they add some extra visual clutter and reduce text contrast. 

like i wrote above, i think it would look cleaner to just try to adjust margins between elements

**Comment by kiyote33** [comment]
Rev #4c - feels like we may be getting closer.  Keep your input coming...
![image](https://user-images.githubusercontent.com/57125427/158649784-8c1a93d2-7d8f-4bb0-ac3b-742697961b22.png)

**Comment by joshreisner** [comment]
@kiyote33 ❤️ ✨

**Comment by 97eighty** [comment]
Looking good @kiyote33

**Comment by kiyote33** [comment]
Rev #5 - Final review (for now). Thanks everyone for your patience, support, and suggestions. Much appreciated...
![image](https://user-images.githubusercontent.com/57125427/158691568-9dc001b2-ff8f-4b70-bc8d-962b223f3591.png)
![image](https://user-images.githubusercontent.com/57125427/158693051-99e40144-fc5e-4f86-91f1-a2f333fbf751.png)

**Comment by kiyote33** [comment]
REV 5 - Final Review. Thanks for all the input on this. Looks like this is pretty much the way it will look:
![image](https://user-images.githubusercontent.com/57125427/158693612-950ac280-8681-4781-a641-90ce302eac27.png)
![image](https://user-images.githubusercontent.com/57125427/158693679-3fc7a297-9bbf-4962-8779-a5f6de554108.png)

**Comment by kiyote33** [comment]
I'm looking for feedback on the Mapping & Geocoding.  Does this make sense or do I revert to what we had yesterday. Please put your 2 cents worth in...
![image](https://user-images.githubusercontent.com/57125427/158854043-135d8a01-c8b8-44f4-a269-fb1283fbe743.png)
which expands to this...
![image](https://user-images.githubusercontent.com/57125427/158854563-616ba6fc-4f80-472d-8bb7-4214c30b0622.png)

**Comment by joshreisner** [comment]
i liked it better yesterday 👍

**Comment by tech2serve** [comment]
I just addressed another user's issue with setting up a site without having created a function mapping key. Anything we can do to improve their setup process is good imo.

**Comment by joshreisner** [comment]
@tech2serve i believe wayne shared a screencap of this somewhere recently, but if a user has no map key entered they get a gigantic message on the settings page telling them all about it. so i think from a settings-page-perspective we're already doing all we can (@kiyote33 sounds like we want to preserve this behavior in the new design). 

<img width="1583" alt="Screen Shot 2022-03-17 at 12 41 23 PM" src="https://user-images.githubusercontent.com/1551689/158883226-7b2f71e8-da2b-49ba-be07-324b76f49f4f.png">

on the meeting edit page, we also show them a message like this:
<img width="1002" alt="Screen Shot 2022-03-17 at 12 44 01 PM" src="https://user-images.githubusercontent.com/1551689/158883267-a8d70852-5eac-4a68-bee2-ccc68b126f07.png">

on the actual public UI we hide the maps on the detail page and on the list / map toggle

**Comment by tech2serve** [comment]
I understand, and yet we still have issues (relatively frequently) with users not understanding what it is they need to do or maintain for the mapping to work.

So, I support expansions and info buttons that help explain it to them. I do like the note showing on the map, and I'd hope that would help as well. 

I am not crazy about the extra clutter from the expansion arrow, so perhaps a hover window instead?

**Comment by kiyote33** [comment]
_From Slack_:
I would like to suggest a Content compromise on this which I think considers a bit from all the stated views:

1. Start with the suggested Rev 5 layout version and content from 2 days ago (which got approval from everyone), but make the following content modifications.
2. Replace General Program description text reading "**This selection determines which meeting types are available**" to read "**Select the Recovery Program your site targets here"**. Having an end user select a program based on their knowledge of what meeting types are available to each program is not the message we want here.
3. Replace **General Meeting/Group Contacts Are** heading with **Contact Visibility**.
4. Keep the new **Feed Management** section heading.
5. Modify Mapping & Geocoding content to incorporate the **Mapbox Access Token** changes I suggested yesterday at 10:03 am using the info window style suggested by [@josh](https://code4recovery.slack.com/team/U010NSRGL31) in his follow-up comment at 12:47.
6.  Modify Mapping & Geocoding **Google Maps API Key** to only include this description text: **"Enter a key from Google authorizing usage of it Maps services ([detailed instructions here](https://developers.google.com/maps/documentation/javascript/get-api-key))"**. The limited Google support we provide here may help drive users to our preferred Mapbox provider, which I think we all agree is a good thing.
7. Keep the new **About Us** and **Switch UI** sections from Rev 5.
8. Keep the modifications made to **Need Help?** in Rev 5.

Please vote thumbs up or make suggestions... (edited)

**Comment by joshreisner** [comment]
Thanks for all the work you're putting in to achieve consensus @kiyote33 -- my overall feedback is let's try to be as economical as possible with language (it demands user time and energy) and functionality (it demands developer time and energy). But it's looking / sounding great 👍

**Comment by kiyote33** [comment]
Rev #6 - Waiting Review
![image](https://user-images.githubusercontent.com/57125427/159056298-15ec3d61-bfff-4ec3-a88d-56896ec7558d.png)
![image](https://user-images.githubusercontent.com/57125427/159056654-4afa592e-4373-4dbd-b8f1-914f0111ee4b.png)
**Mapbox expands to this when NO Access Token is present**
![image](https://user-images.githubusercontent.com/57125427/159056924-eae83c67-5b1e-4f7a-8da6-33d430d30a1a.png)
