### ISSUE TITLE
TSML-UI Options page

### ISSUE THREAD

**Issue by brianw-area24** [code4recovery/12-step-meeting-list#369]
It would be nice to have an additional page on the Admin Menu under Meetings for TSML-UI options. This would allow Wordpress admins to adjust the behavior of TSML-UI on their sites. Then the code that generates the shortcode, and will also be used for [Issue #368 ](https://github.com/code4recovery/12-step-meeting-list/issues/368), would use the options from this page. This would make TSML-UI much more flexible on WordPress sites.

I think this new page would always be available, even when using the legacy front end, because the shortcode would benefit from these options as well. Once this page is in use, we may want to move the option to use TSML-UL onto this page, rather than the existing Import & Settings page, see #368

**Comment by joshreisner** [comment]
FYI pull request #341 brings feedback emails, custom meeting types, conference providers, and columns for free, and provides a new `$tsml_config` variable for specifying additional configuration options.

**Comment by joshreisner** [comment]
If possible I'd like to consider the possibility of not doing this work. I am hoping to discourage people from doing any kind of code-level customizations going forward.

(For what it's worth I think we should consider that approach with TSML too)

To that end, things like search are no longer configurable. I'm not sure what settings we'd want to be able to configure going forward from this screen. Do you have ideas? Maybe I'm forgetting something?
