### ISSUE TITLE
Odd Upcoming Issue

### ISSUE THREAD

**Issue by lloy0076** [code4recovery/12-step-meeting-list#372]
**Describe the bug**
Day 2 Upcoming Missing Result(s).

**To Reproduce**
1. https://aa-stlawrenceny.org/meetings/?tsml-day=2&tsml-time=upcoming --> no results!
2. https://aa-stlawrenceny.org/meetings/?tsml-day=3&tsml-time=upcoming --> has results!

This is at 10:42 PM. There are no meetings until noon on the next day which is day (3).

**Expected behavior**
There should be results!!!

**Possible Explanation**

```
<?php
if (!empty($arguments['time'])) {
    $this->time = is_array($arguments['time']) ? array_map('sanitize_title', $arguments['time']) : array(sanitize_title($arguments['time']));
    if (in_array('upcoming', $this->time)) {
        $this->now = current_time('H:i');
    }
}
//callback function to pass to array_filter
public function filter_time($meeting)
{
    if (!isset($meeting['time'])) {
        return false;
    }

    foreach ($this->time as $time) {
        if ($time == 'morning') {
            return (strcmp('04:00', $meeting['time']) <= 0 && strcmp('11:59', $meeting['time']) >= 0);
        } elseif ($time == 'midday') {
            return (strcmp('11:00', $meeting['time']) <= 0 && strcmp('16:59', $meeting['time']) >= 0);
        } elseif ($time == 'evening') {
            return (strcmp('16:00', $meeting['time']) <= 0 && strcmp('20:59', $meeting['time']) >= 0);
        } elseif ($time == 'night') {
            return (strcmp('20:00', $meeting['time']) <= 0 || strcmp('04:59', $meeting['time']) >= 0);
        } elseif ($time == 'upcoming') {
            return (strcmp($this->now, $meeting['time']) <= 0);
        }
    }
}
```

I won't comment on whether using `strcmp` and times makes sense. IMHO these would be better handled as DateTime or Carbon instances.

That said, it could just be there are no meetings on Tuesday after 10:44PM and there will be upcoming meetings shown after midnight (or should I say early on in the morning).

But that's ODD to me.

@joshreisner  wrote some of this code according to git blame; what's the code meant to be doing?

**Comment by lloy0076** [comment]
PS. I'm not sure if this is a bug or if this is expected behaviour.

**Comment by lloy0076** [comment]
So I have logged the comparisons and with some data I see:

```
[16-Jun-2021 03:18:11 UTC] "upcoming"
[16-Jun-2021 03:18:11 UTC] "12:00"
[16-Jun-2021 03:18:11 UTC] "03:18"
[16-Jun-2021 03:18:11 UTC] true
[16-Jun-2021 03:18:11 UTC] "upcoming"
[16-Jun-2021 03:18:11 UTC] "12:00"
[16-Jun-2021 03:18:11 UTC] "03:18"
[16-Jun-2021 03:18:11 UTC] true
[16-Jun-2021 03:18:14 UTC] "upcoming"
[16-Jun-2021 03:18:14 UTC] "12:00"
[16-Jun-2021 03:18:14 UTC] "03:18"
[16-Jun-2021 03:18:14 UTC] true
```

With:

```
    //callback function to pass to array_filter
    public function filter_time($meeting)
    {
        if (!isset($meeting['time'])) {
            return false;
        }

        foreach ($this->time as $time) {
            error_log(json_encode($time, JSON_PRETTY_PRINT));
            error_log(json_encode($meeting['time'], JSON_PRETTY_PRINT));
            error_log(json_encode($this->now, JSON_PRETTY_PRINT));
            error_log(json_encode(strcmp($this->now, $meeting['time']) <= 1));

            if ($time == 'morning') {
                return (strcmp('04:00', $meeting['time']) <= 0 && strcmp('11:59', $meeting['time']) >= 0);
            } elseif ($time == 'midday') {
                return (strcmp('11:00', $meeting['time']) <= 0 && strcmp('16:59', $meeting['time']) >= 0);
            } elseif ($time == 'evening') {
                return (strcmp('16:00', $meeting['time']) <= 0 && strcmp('20:59', $meeting['time']) >= 0);
            } elseif ($time == 'night') {
                return (strcmp('20:00', $meeting['time']) <= 0 || strcmp('04:59', $meeting['time']) >= 0);
            } elseif ($time == 'upcoming') {
                return (strcmp($this->now, $meeting['time']) <= 0);
            }
        }
    }
```

Honestly, there almost has to be a better way to do this time of comparison. `upcoming` is ***not** a time at all, and besides relying on the presumed underlying collation is a tad bizarre to say the least.

**Comment by lloy0076** [comment]
Actually #51  and #55 imply this might be expected behaviour...but it's 11:25 PM on my local machine and my LOCAL install is showing a noon meeting for TOMORROW....

**Comment by lloy0076** [comment]
Well it's 12:03 AM and the "View More" definitely thinks that it goes to the third day.

![image](https://user-images.githubusercontent.com/1174532/122156158-6b60e480-ce36-11eb-805b-f1a0dde36196.png)

But I still see:

![image](https://user-images.githubusercontent.com/1174532/122156181-761b7980-ce36-11eb-8471-95ba95fdfc0d.png)

https://aa-stlawrenceny.org/aa-12-steps/

**Comment by lloy0076** [comment]
And they just appeared; we're close enough for the server time to be an issue but I wonder if the fastest cache plugin might be causing issues here.

**Comment by lloy0076** [comment]
I think there are several issues that all intersect with each other:

- It is not clear whether the "upcoming meetings" means "meetings within a certain number of hours" or just "meetings on this day"; #51 and #55 seem to imply "on this day"
- The code that calculates all the times may or may not be working and personally I identify several potential issues...

Issues with the code:

- The filter code seems to rely on the typical collation of the times that are retrieved
- As OPPOSED to interpreting the times
- It's especially weird to `strcmp` the word `upcoming` with a time like `04:00` -- what does that even MEAN.

I think I'm seeing various oddities related to the calendar time(s) I've been looking at the sites and the way the times are filtered; although I'm not fully sure.

It is also possible that the WP Fastest Cache may be causing issues but I really don't believe this to be the case.

**Comment by joshreisner** [comment]
Caching can definitely affect what you see in the upcoming view.

The other thing that can affect this is your timezone setting in your general WP settings, be sure this is set correctly.

This view shows all the meetings for the rest of the current day.

Here is a demo site: https://tsml.joshreisner.com/meetings?tsml-day=2&tsml-time=upcoming

It's set to Pacific time, as of 9:29pm PT it shows upcoming meetings at 9:30, 10, and midnight.

**Comment by lloy0076** [comment]
@joshreisner I wonder if it would be better named `TODAY'S MEETINGS` vs. upcoming meetings? I'd argue it's not upcoming meetings because a meeting on 2/Feb/2021 12:01AM is definitely an upcoming meeting if you check at 1/Feb/2021 11:59PM.

Think of it this way: "The meeting that happens in 2 minutes' time is *not* upcoming..."

**Comment by joshreisner** [comment]
👍 I agree. We're getting rid of this view in the new version of the meeting finder we're working on and showing all the meetings sorted by upcoming as the default view: https://react.meetingguide.org 

This way the next meeting is always at the top of the list (unless you filter to show specific days).
