### ISSUE TITLE
PayPal "pool" account type seems to not work

### ISSUE THREAD

**Issue by sfconn** [code4recovery/12-step-meeting-list#374]
One of our groups uses a PayPal "pool" account, not a standard PayPal personal account.  When I enter their URL (https://paypal.me/pools/c/8u6vmq54mC) in the meeting guides it accepts the information.  When I click save, the tool truncates the entry to be only the last part or UserName: 8u6vmq54mC as it normally does with other PayPal URLs.  When I view this meeting from the web, it has the PayPal button.  When I click the button, I get an error from PayPal: "We can't find this profile".  

If I look at the URL displayed in the error message, it is now looking for this URL https://www.paypal.com/paypalme/8u6vmq54mC.  As you can see, the new URL is missing the "/pool/c/" part.  If I try to add this "/pool/c/" text in the tool in front of the account UserName, when I click save on the meeting, the tool strips the extra text out.  

To me, it seems like PayPal "pool" accounts are not currently supported.  Can you add support for this type of PayPal account?

![PayPal Pool Account not found](https://user-images.githubusercontent.com/84883067/122652465-e9054880-d0f3-11eb-8d7e-1e7429919fd8.JPG)

**Comment by tech2serve** [comment]
Correct, they are not supported.

I'll need to discuss this with others as it would also require a change to the Meeting Guide specification unless PayPal provides a simple way to convert the pool nomenclature to a regular PayPal user name.

An alternative is for the group in question to change to a traditional PayPal account, or one of the other supported forms of accepting 7th Tradition contributions. This is the first group I'm aware of that is using a pool.

**Comment by joshreisner** [comment]
Closing this as PayPal appears to be shutting down this service. https://www.finextra.com/pressarticle/88766/paypal-discontinues-money-pools
