### ISSUE TITLE
v3.11.0-b BETA - Active Meeting With TC Status Detail View

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#376]
These comments are all for the way the meeting detail view is.

**Active Online Meetings with TC status** (the meeting used to meet inside).

1. Would it be possible to put /Women, Online Meeting or /Men, etc. back the way it was on the same line and bold and green, instead of on the next two lines like it is in the beta version?
2. There's a big white space where the map was. Any chance we could be an image up if it's an active online meeting?
3. Would it be possible to change Closed Meeting text with **_Closed meetings are for A.A. members only, or for those who have a drinking problem and “have a desire to stop drinking_**" instead of **_This meeting is closed; only those who have a desire to stop drinking may attend_**?
4. Would it be possible to change Open Meeting with **_Open meetings are available to anyone interested in Alcoholics Anonymous’ program of recovery from alcoholism._** instead of **_This meeting is open and anyone may attend_**?

See comparative screenshots.

![3 Detail - Tuesday](https://user-images.githubusercontent.com/62247421/122673673-8e292b00-d19f-11eb-994e-2d18d0c1085a.png)
![3b Detail - Tuesday](https://user-images.githubusercontent.com/62247421/122673675-91bcb200-d19f-11eb-8970-11c8235194b1.png)

**Comment by tech2serve** [comment]
1. Will take another look at the flags.
2. Not sure. May leave that as a feature associated with TSMLui, but we'll discuss it.
3. Duplicated #330
4. Duplicates #330

**Comment by 97eighty** [comment]
These can be modified using a local config. Value is stored in the type_descriptions array:

'type_descriptions' => array(
				'C' => __('This meeting is closed; only those who have a desire to stop drinking may attend.', '12-step-meeting-list'),
				'O' => __('This meeting is open and anyone may attend.', '12-step-meeting-list'),
