### ISSUE TITLE
v3.11.0-b BETA - Active Meeting With TC Status List View

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#377]
These comments are all for the way the meeting list view is.

**Active Online Meetings with TC status** (the meeting used to meet inside).
1. Would it be possible to leave /women or /men or /online meeting the way it was? That was after the meeting name, in bold green font. It doesn't improve anything to have, for example, (women) on the next line, when the current version shows it in the same line and stands out since it is green color and bold.
2. The location field is using the group name if it's an online meeting, but that makes no sense to most anyone since the group name has nothing to do with the location. For active online meetings, it also is dimmed (or greyed out) and doesn't look right. How about not having the location name listed (and greyed), but replace that with the word online (as what is started), but make it bold and perhaps another color such as green.
3. Suggest not removing the address. Dim it or cross it out instead.
4.  Suggest not crossing out the region name should not be done. I would dim it or leave it alone. These meetings and groups are very much aligned to their districts and former locations where they will probably go back to.
5. Any possibility of displaying this list like the UI version is with the graphical images for zoom, phone, address, etc.

Below is a screenshot of current plugin (v3.10.0) and beta (v3.11.0-b). 
![3 - Tuesday](https://user-images.githubusercontent.com/62247421/122672754-3be60b00-d19b-11eb-8fd6-e3a560eb0d02.png)

![3b - Tuesday](https://user-images.githubusercontent.com/62247421/122672763-41dbec00-d19b-11eb-92b5-b7449d2da837.png)

A few more thoughts about location field. I know you want to encourage meetings to become groups, but I do not believe TSML is the way to do it. We can do a better job of educating A.A. members about groups and why meetings should consider doing so. Here at intergroup we do hold workshops and have information on the website about the value of becoming a group, and we encourage meetings to register with GSO because they then have a voice in the decision making process of A.A. 

We also encourage A.A. members and groups to make seventh tradition contributions and provide information on how to do so.

But each group, whether formally registered or not, is autonomous, provided they don't affect other groups or A.A. as a whole (tradition four). 

We cannot direct what each autonomous group can or cannot do. We are not even part of the general A.A. Service Structure. Our role is to serve the local needs of groups in their common purpose of carrying the A.A. message by providing services that the individual groups cannot readily provide for themselves, such as local meeting lists,  answering inquiries about A.A., establishing local public information committees, etc.

**Comment by tech2serve** [comment]
1. We're trying to clean up the UI. Still making tweaks, but I personally am not crazy about the old style as they look cluttered. Anyway, still discussing this.
2. You're right. We need to change the column heading to "Location/Group" as has been done for TSMLui.
3. Showing an address for meeting locations that are not open to the user and for online meetings doesn't make sense. Removing it cleans the UI. As is the case with most of these, CSS can bring them back if you want for your site.
4. Agreed. That may be a bug. Thanks.
5. Unlikely. We're still planning to replace the TSML frontend with TSMLui, and so we're not trying to continue developing two version.

**Comment by tech2serve** [comment]
I believe we've addressed the issues we're going to address in this thread. Still looking at some UI tweaks for the single meeting page, but that issue is captured elsewhere.
