### ISSUE TITLE
v3.11.0-b BETA - Labels for Meeting Status 

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#378]
I like that this version tells us it's in-person, or online, or Temporarily Inactive, etc. Is there any way to make that stand out better? Would it be possible to put in on the same line as the meeting name in the detail view? 

See before and after screenshots.

This is for suspended meetings.

![Suspended Plugin](https://user-images.githubusercontent.com/62247421/122674221-245e5080-d1a2-11eb-80ef-1e07a2e61c9b.png)

![Suspended UI](https://user-images.githubusercontent.com/62247421/122674230-2aecc800-d1a2-11eb-87ac-902cf0c2ced0.png)

This is online only meeting (no TC status)

![Online Plugin](https://user-images.githubusercontent.com/62247421/122674251-435ce280-d1a2-11eb-99f1-ae99f0f2f034.png)

![Online UI](https://user-images.githubusercontent.com/62247421/122674255-48219680-d1a2-11eb-85a3-7ac7ac5eb617.png)

This is a hybrid

![hybrid plugin](https://user-images.githubusercontent.com/62247421/122674323-959e0380-d1a2-11eb-8ec1-491af2f38c1e.png)

![hybrid UI](https://user-images.githubusercontent.com/62247421/122674329-9a62b780-d1a2-11eb-845c-605ebaf490e8.png)

**Comment by tech2serve** [comment]
I think they do stand out, quite a bit. 

I'm going to close this as it effectively duplicates item 1 in #376. We'll discuss flags, but I'm more concerned about putting some flags in parenthesis and others in bold. As I look at it again, it seems inconsistent.

**Comment by Grateful-Viv** [comment]
Is there some reason why it has to be on the next line and not next to the meeting name as in the current plugin? It is smaller font and I don't think it stands out as much as current plugin.
