### ISSUE TITLE
chr() expects parameter 1 to be int, string

### ISSUE THREAD

**Issue by lloy0076** [code4recovery/12-step-meeting-list#383]
**Describe the bug**
Warning: chr() expects parameter 1 to be int, string given in /home/q0afnjbk/public_html/wp-content/plugins/12-step-meeting-list/includes/tcpdf/include/tcpdf_fonts.php on line 1671

**To Reproduce**
1. Install it
2. Get District 42's meetings
3. Go to https://aa-stlawrenceny.org/wp-admin/edit.php?post_type=tsml_meeting&page=import and click on full page

**Expected behavior**
No warnings are issued.

I believe using PHP 7.4 has caused these AND MANY OTHER warnings to appear.

I would turn warnings off but for the life of me I cannot figure out how to do so on our hosting service (and besides, warnings are not good to have anyway).

**Comment by tech2serve** [comment]
Hey @lloy0076 --

Sorry for the delay on answering this. 

I've updated my dev site to PHP 7.4 but still haven't been able to reproduce this specific issue. 

We did release v3.11.1 that addresses some PHP warnings. Please update to that version and report back if this warning issue still persists.

Thanks.

**Comment by lloy0076** [comment]
@tech2serve Set your WP_DEBUG to `true`.

**Comment by brianw-area24** [comment]
We think version `3.11.1` should address this issue. Please update to this version. If the problem persists after the update, then please let us know and we'll look into this farther.

**Comment by tech2serve** [comment]
> @tech2serve Set your WP_DEBUG to `true`.

My dev site is run with debugging on.

**Comment by tech2serve** [comment]
@lloy0076 — Just released v3.11.2. Please test and report back the status of this issue. 

Thanks.

**Comment by joshreisner** [comment]
I am running PHP 8 and have `WP_DEBUG = true` - when opening the PDF I get "there's been a critical error on this website."

Updating the TCPDF files to latest fixes it.

**Comment by joshreisner** [comment]
Complete with release of `3.12`
