### ISSUE TITLE
Notification emails not sending to select addresses

### ISSUE THREAD

**Issue by A46webchair** [code4recovery/12-step-meeting-list#385]
Published a new site yesterday (June 22, 2021). Our meeting editor is not receiving notifications from the new site. I (webchair@nm-aa.org) are receiving them fine but meeting@nm-aa.org and meetings@nm-aa.org are not.  Domain has not changed. I am sure I probably missed a setting somewhere.  Any ideas?

![image](https://user-images.githubusercontent.com/72042564/123138198-fed77e00-d411-11eb-977e-2fbab4aced5d.png)

**Comment by 97eighty** [comment]
@A46webchair 
This is likely a mail server issue. Check the final destination of the meeting@ and meetings@ email addresses. Are these forwards? If so, then possibly the final mail server is blocking or sending to SPAM.

**Comment by A46webchair** [comment]
thank you.  I will check into that.
