### ISSUE TITLE
Publish Date not Changing with Edit

### ISSUE THREAD

**Issue by A46webchair** [code4recovery/12-step-meeting-list#386]
**Describe the bug**
when changes are made by our meeting editor to a meeting and published again, the publish date is not changing.

**To Reproduce**
1. Go to meeting record and make an edit
2. Click on "Update"

**Expected behavior**
The publish date used to update automatically. Now we are doing it manually There was an option to manually update with one click.  Now that option is gone and each field (month, day, year and time) must be manually updated. 

**Screenshots**
![image](https://user-images.githubusercontent.com/72042564/123148458-7e1e7f00-d41d-11eb-8462-e8314425eec3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 PC
 - Browser [Firefox]

**Additional context**
I am also on a PC and the update feature works fine for me. As of yesterday Meeting Editor has a custom WP role and can only access the TSML plugin.  However, she said this issue has been ongoing for quite some time.

**Comment by 97eighty** [comment]
@A46webchair A quick look at our code doesn't show that we update this field directly. This is a function of WordPress. I suggest manually looking at the post_date, post_modified fields in your database to see if they are updating properly.

**Comment by Grateful-Viv** [comment]
The publish date should be a static date from when it’s first published. It shouldn’t change if you update any information. You aren’t republishing it, just updating. This same logic would apply to any page or post in Wordpress.

**Comment by brianw-area24** [comment]
Yes, I agree with @Grateful-Viv and @97eighty, this date doesn't normally change, unless you edit it yourself. I just verified this by editing a normal WordPress post, not a meeting, and it exhibited the same behavior.

I'm going to go ahead and close this issue.
Brian W
