### ISSUE TITLE
v3.11.0-b BETA - Online meetings tagged as Location Temporarily Closed

### ISSUE THREAD

**Issue by courage2change** [code4recovery/12-step-meeting-list#387]
**Describe the bug**
Wanting to add online-only meetings, but they're being flagged as Location temporarily closed.

**To Reproduce**
1. Add Meeting
2. Add approximate address in Location field
3. Add valid Zoom details in URL field
4. Meeting is displayed as Online meeting and Location temporarily closed.

**Expected behavior**
I wouldn't expect the meeting to be tagged as Location temporarily closed as it never had a location.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser:  Chrome
 - Version  91.0.4472.114 

**Additional context**
Will add a separate issue regarding approximate addresses and the logic around assigning online/in person/location temporarily closed.

**Comment by brianw-area24** [comment]
I'm not finding where this is happening while displaying the meetings with the plugin, but of course, I could be missing something. It would help us track this down if you could send us a URL of the page where your seeing it flagged as Location Temporarily Closed, or upload a picture showing where you're seeing this.

Thanks, and again, thank you for testing the beta version of the plugin!
Brian W.

**Comment by Grateful-Viv** [comment]
I just tried to reproduce the behavior using steps above. The address was an intersection of two streets, but not an exact one.

The meeting published as online and in person (aka hybrid).

**Comment by tech2serve** [comment]
Closing this as we've released the official version. If the OP is still experiencing an issue, please review #405, #406 and #408 for more discussion on how the logic works, and open a new issue with meeting particulars if questions still exist.
