### ISSUE TITLE
“/ Online Meeting” tag has been causing confusion.

### ISSUE THREAD

**Issue by abacusBytes** [code4recovery/12-step-meeting-list#389]
**Is your feature request related to a problem? Please describe.**
**_The two options I saw were "Bug Report" and "Feature Request". I am not sure what this falls under._**
When looking up a meeting, I have been told that the green, "/ online meeting" tag makes it look like the meeting is **only** online. Whether a meeting is Online Only, or Hybrid, they get the same green "/ Online Meeting" tag appended to their name. It is easy enough to list the meeting as "Hybrid", "On-line", or "In-person" in the meeting name or description, so this tag has become a confusing redundancy.

**Describe the solution you'd like**
I would like the "/ Online Meeting" tag to be removed from all listings.

**Describe alternatives you've considered**
Removing the tag entirely seems most practical, but if a tag is necessary, perhaps variations could be added so we could have the choice to select the one we prefer be displayed (e.g. "/ Online Meeting", "/ In-Person Only", or "Hybrid")

**Additional context**
![Untitled](https://user-images.githubusercontent.com/84578716/123423461-94e3e380-d58d-11eb-8b5f-19907b4a7221.png)

**Comment by tech2serve** [comment]
Hi @abacusBytes,

We are not going to remove the flags, but they are changing a bit with the version currently being tested (3.11.0-b), including making it clearer when a meeting is available online AND in person. Hopefully that will resolve your issue.

If you still want them off your site, you’ll need to use CSS to hide them. That is beyond the scope of our direct support, but you can search the issues to see if others have done something similar. TIAA Forum is another source where some folks may help you. 

Good luck! And thanks for sharing your thoughts.
