### ISSUE TITLE
v3.11.0-b BETA Type Dropdown

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#390]
1. Any chance we could select inactive in the dropdown type?
2. Any chance it could display a count next to the types?

Both of these exist in TSML-UI, so wondering if it is not difficult to add similar logic to the plugin.

**Comment by tech2serve** [comment]
Good catch on the active vs inactive. There are two schools of thought, and I’m not sure which will win out. Frankly, they both have merit, and they both work. I’ll add it to the list of things for us to discuss.

Not going to try and implement a count. That will remain a feature distinction for TSMLui.
