### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by brianw-area24** [code4recovery/12-step-meeting-list#393]
Over time, sometimes parts of the code are no longer used. This issue is a request to start cleaning up some of this old code, which will hopefully make the code a little more readable, and make future updates easier.

I would like to create a new branch, called code_cleanup, for this purpose. Anyone is welcome to add commits to this branch, which should only be used to refactor code to make it cleaner. No new features here.

For example, just a few things I'm aware of include:
- Typo's where function/variable names start with tmsl_ instead of tsml_
- Functions that are no longer used, including db_update_addresses_cache_approximate_location, db_update_tsml_locations_approximate_locations, and decide_if_location_approximate
- A notice about TC being available, that should have been displayed since the end of April, 2020
- Some spacing that makes the code harder to read
- Missing comments

**Comment by joshreisner** [comment]
Complete with release of `3.12`
