### ISSUE TITLE
Upcoming Meetings Widget

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#401]
For online meetings, the street address is displayed. Can it be crossed off or not displayed?

![Sidebar Widget](https://user-images.githubusercontent.com/62247421/124012296-03baa580-d9af-11eb-9703-306a904f1f02.png)

**Comment by tech2serve** [comment]
I don't see any street addresses being shown in the widget.

On my dev site, "Online" is shown in the Location column.

What is your theme?

**Comment by Grateful-Viv** [comment]
I did not update the plugin on the live site as there's still some bugs and inconsistencies that need to be worked before using it. I did put in draft mode all suspended meetings, so the only meetings on the website are active.

**Comment by tech2serve** [comment]
So this is with v3.10? 

We're not going to make any changes to that. We don't maintain multiple versions.
