### ISSUE TITLE
Public Feed missing all Meetings

### ISSUE THREAD

**Issue by christopherokc** [code4recovery/12-step-meeting-list#404]
**Describe the bug**
Just today, we're suddenly seeing zero meetings on our meeting page (/meetings) even though all of our meetings are still listed in the admin console > meeting. We haven't changed any settings. 

All other pages and functions of our Wordpress instance work fine. 

**To Reproduce**
1. Go to https://okcintergroup.org/meetings/
2. Observe no meetings
3. Go to https://okcintergroup.org/wp-admin/edit.php?post_type=tsml_meeting
4. Observe all of the meetings are listed
5. Download CSV
6. CSV has no meeting data
7. Open public feed https://okcintergroup.org/wp-admin/edit.php?post_type=tsml_meeting&page=import
8. Page times out.

Multiple users are experiencing the above on multiple devices with mixed OS, mobile, desktop, safari, Firefox, etc..

WP Current version: 5.7.2
PHP 7.2.34

**Comment by joshreisner** [comment]
Hm! 🤔 I'm assuming your meetings are all published.

Sometimes editing and saving a meeting (even if there are no changes) can help refresh the cache (if it's a caching issue)

**Comment by christopherokc** [comment]
> Hm! 🤔 I'm assuming your meetings are all published.
> 
> Sometimes editing and saving a meeting (even if there are no changes) can help refresh the cache (if it's a caching issue)

We show they are published. I have edited and "updated" a meeting. That worked!! 
Josh, You are always so helpful and of service. Thank you!!

**Comment by christopherokc** [comment]
We now see all meetings as expected after editing one meeting and immediately republishing/"update" the same meeting without any changes to the meeting.
Public feed is generating as expected.
CSV is generating as expected.
Issue resolved.
Closing.
