### ISSUE TITLE
TSML Updated : now extremely sow

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/12-step-meeting-list#415]
**Describe the bug**
After updating to 3.11.0, my area's meetings portion seems extremely slow.  Updates and imports are taking upwards of 2-3x longer.  Am getting frequent 503's on updates.  Was there some backend changes done with this update? 
Wondering if there are any other reported performance issues after upgrading to 3.11.0.

**To Reproduce**
1. Update TSML from previous version, say most recent WP 5.7 compatible version prior to this.
2. Select meetings section
3. Import meetings -or-
4. Update meetings

**Expected behavior**
Some delay is expected for processing changes and imports, but anything longer than say 5-10 secs should be looked into.  And, 503's are not kosher.

**Laptop/Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [Version 91.0.4472.114]

**Comment by jcookson-infoblox** [comment]
Additional data, I sometimes open multiple browser tabs with different meeting info in each one to work en-tandem.  Have encountered 503's (a lot and predictably regularly) when submitting more than 2 diff tabs (each with diff meeting info submitted one after the other).  This should be allowed, because each tab should be placing a lock on that specific meeting's info and none others.  So submissions en-tandem would be processed one after the other.

**Comment by tech2serve** [comment]
Please clear browser and website cache. And try again. This is a total guess, but it is the best I have with the information provided :-)

I’m really not sure what is going on, but our update didn’t touch import logic.

In the past we’ve had people experience import issues when the hosting providing made changes. You might also check with them.

What PHP version are you using? And errors showing in the console (outside of the 503s)? 

If you close other tabs, does the import speed up?

Are all imports slow? Or only from some districts? 

Are you importing CSVs or all JSON feeds from other sites? 

What version of the plugin are they using?

I’m converting this to a Discussion which is where we are trying to move public conversation to. If we confirm a bug, I’ll open a new issue.
