### ISSUE TITLE
Contacts are public in JSON even when set to private

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#425]
Private contact information is visible in JSON in https://aasanjose.org/wp-admin/admin-ajax.php?action=meetings

Despite "Meeting/Group Contats Are" being set to "Private"

![Screen Shot 2021-07-09 at 7 34 36 AM](https://user-images.githubusercontent.com/1551689/125094687-50c20a00-e088-11eb-82d3-712a17ff80d0.png)

**Comment by joshreisner** [comment]
Hm, this isn't going to be so easy. There have been a lot of refactors to the caching which will require some discussion. Cache rebuilding has been moved to a side effect of `tsml_get_meetings`

**Comment by brianw-area24** [comment]
I've been thinking about this one for a while. I think the way to strip out the contact information would be to put a foreach loop in the `tsml_ajax_meetings()` function. In addition to striping out contact information, we should strip out `attendance_option` as well.

**Comment by joshreisner** [comment]
ah right, `attendance_option` 👍 

the problem with putting it on `tsml_ajax_meetings` is then you have to do that CPU work every time the data is accessed. if you don't write it to JSON at all then you only have to do it when the JSON data is updated

**Comment by brianw-area24** [comment]
Here's what I understand should happen to resolve this issue:
- Meetings cache file should be moved from tsml-cache-<id>.json, to meetings.json
- When writing this cache, use the "Meeting/Group Contact Are" field (from settings) to include/exclude this info in the cache
- The existing admin-ajax.php URLs should continue working for now, but should get deprecated sometime in the future
- CSV export should not use the cache, it should query the database to get all information, including source feed
- CSV import should import all information, including source feed, and if that feed doesn't exist on the imports & settings page, it should create it
