### ISSUE TITLE
Potential Improvements to PDF Export

### ISSUE THREAD

**Issue by lloy0076** [code4recovery/12-step-meeting-list#426]
The current behaviour of the export to PDF is a little odd in several ways:

**Meeting types run into the address**

[meeting-schedule.pdf](https://github.com/code4recovery/12-step-meeting-list/files/6794168/meeting-schedule.pdf)

Notice how in the above the meeting types run into the address.

**Online Meetings**

You'd not know they're online meetings! So Nooners during the week are all online but it's listed as meeting at Maple St!

**Possible Changes**

[meeting-schedule(14).pdf](https://github.com/code4recovery/12-step-meeting-list/files/6794171/meeting-schedule.14.pdf)

So I played about a bit with the code and came up with the above; notice that:

- I've put the meeting types onto their own line
- If it's an online meeting I've made it just print out the URL

**Further Changes/Enhancements**

1. Make it more configurable
2. Make it template-able
3. Add internationalisation (i18n) --> it's very English specific ATM
4. Print out the name of the start day

(If you change L154 https://github.com/code4recovery/12-step-meeting-list/blob/d06856d27e52fddb93cd7dfa69bacc805886f42e/includes/pdf.php#L150 to something like):

```
if (isset($meeting['attendance_option']) && $meeting['attendance_option'] === 'in_person') {

		$this->Cell($day_width, .1, '', 0, 0);
	        $this->Cell($time_width, .1, '', 0, 0);
                $this->MultiCell($right_width, .1, $location . ', ' . @$meeting['formatted_address'], 0, 'L');
                $this->Ln(.1);
} else {
		$this->Cell($day_width, .1, '', 0, 0);
	        $this->Cell($time_width, .1, '', 0, 0);
                $this->MultiCell($right_width, .1, 'Check this URL: ' . $meeting['url'], 0, 'L');
		$this->Ln(.1);
}
```

Now, I might be motivated to put some effort into this but am wondering if there is a ROADMAP to improve this functionality already, who else might be working on this, or what any work in this area might affect.

**Comment by tech2serve** [comment]
Moving this to our new Discussions page.
