### ISSUE TITLE
Meeting Page MISSING (?) Upgraded to 3.11.0

### ISSUE THREAD

**Issue by lloy0076** [code4recovery/12-step-meeting-list#429]
**Describe the bug**
I upgraded from 3.10.0 to 3.11.0 and the meeting page is "just gone".

**To Reproduce**
1. Install WordPress
2. Install 3.10.0
3. Upgrade

**Expected behavior**
https://aa-stlawrenceny.org/meetings-by-day/?tsml-day=any should show several meetings.

**Screenshots**
![image](https://user-images.githubusercontent.com/1174532/125163471-5177a080-e15b-11eb-9f24-88a5b36cd27a.png)

**Additional context**
![image](https://user-images.githubusercontent.com/1174532/125163492-5f2d2600-e15b-11eb-8512-e7dcefb4a0cb.png)

[meeting-schedule(16).pdf](https://github.com/code4recovery/12-step-meeting-list/files/6795288/meeting-schedule.16.pdf)

The system KNOWS the data is there.

It's possible the page for displaying the list of meetings have changed.

**Comment by lloy0076** [comment]
It does seem that the short codes do still work, e.g:

![image](https://user-images.githubusercontent.com/1174532/125164096-7ae5fb80-e15e-11eb-9726-f9da7ba5ad68.png)

**Comment by tech2serve** [comment]
Converting to our new Discussions page.
