### ISSUE TITLE
Locations divorced from online meetings make them harder to find

### ISSUE THREAD

**Issue by alex-m-dc** [code4recovery/12-step-meeting-list#436]
Hello,
By totally removing the location from an online meeting (Except for a regional approximate) makes it harder to find meetings.

Say someone knows a meeting as "the grace church 6pm" meeting, one of many held there, but they have different names and some are in-person and some are online. Yes, you can still search for the location and see all held there but when viewing a standard listing of upcoming meetings they won't see that location name and it may confuse them.

And... clubs... this is really bad for them when someone is used to looking up the "Dupont Circle Club 6pm" even though it's called "Beginner Basics" if the club name isn't there... they can't find it.

Please bring back location names for online meetings in the list - you could still prevent the street address from showing up... 

And not having them greyed out would be good - I've had people complain it makes the location look closed even though there are in-person meetings being held there, just that one is online only.

THANKS!!!

--Alex M
267-231-2174

**Comment by Grateful-Viv** [comment]
I agree with you Alex, but for different reasons. 

What they decided to do is keep the location name if it's in person (e.g. Dupont Circle Club), but if it's an online meeting to use group name if there is one, and if there isn't then it's empty. You can see the conversation over in this [thread](https://github.com/code4recovery/tsml-ui/issues/119) which started before this WordPress plugin was updated to v3.11.0.
