### ISSUE TITLE
Geocoding Problem? Re: [code4recovery/12-step-meeting-list] Can I currently attend this meeting in person? wont update (#459)

### ISSUE THREAD

**Issue by COMPUMEC** [code4recovery/12-step-meeting-list#465]
**Describe the bug**
After further testing it seems it is just 2 meetings held at a particular location so far that wont update.
This is the location.

https://www.google.com/maps/place/Fairfield+United+Methodist+Church/@44.5975075,-69.5996224,15z/data=!4m5!3m4!1s0x0:0x4f642ddc76beb1f4!8m2!3d44.5975071!4d-69.5996111

What do you think?
Thank you,
Bob-

**To Reproduce**
This address wont let me change from temporarily closed to open.

**Expected behavior**
Change from temporarily closed to open.

**Screenshots**

**Desktop (please complete the following information):**
Win 10
Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tech2serve** [comment]
Duplicates #459. 

Please don't open new issues. We're moving all public support to Discussions. The thread you've already started is linked above.
