### ISSUE TITLE
Not updating phone app since updating TSML

### ISSUE THREAD

**Issue by RBIWebsite** [code4recovery/12-step-meeting-list#476]
Since updating to V3.11.2  I'm not seeing meeting data transfer to the phone app. Ive edited meeting times and info, and even added a brand new one, and 2 days later the old info is still on the app.

from Readingberksintergroup.org

 **Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by joshreisner** [comment]
hi @RBIWebsite did you report this yet to appsupport@aa.org? there are lots of reasons why a listing might not update in meeting guide, and they are the best equipped to know what's going on

**Comment by RBIWebsite** [comment]
Yes, i have. No response yet.thanks for your time, hopefully they will be able to sort it out.


-------- Original Message --------
Subject: Re: [code4recovery/12-step-meeting-list] Not updating phone app
since updating TSML (#476)
From: Josh Reisner ***@***.***>
Date: Wed, July 28, 2021 6:30 am
To: code4recovery/12-step-meeting-list
***@***.***>
Cc: Steve P ***@***.***>,  Mention
***@***.***>

 hi @RBIWebsite did you report this yet to ***@***.***? there are lots of reasons why a listing might not update in meeting guide, and they are the best equipped to know what's going on —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
