### ISSUE TITLE
All meetings reverted to open (in-person)

### ISSUE THREAD

**Issue by michaelvenzor** [code4recovery/12-step-meeting-list#484]
Looks like the Type "Temporarily Closed" was removed and all the meetings are listed as able to be attended in person. This is a huge issue. Can we revert?

Under Location Information in each meeting, there is a new Question that says "Can I currently attend this meeting in person?" Basically, this should be set to "No" for all the meetings that were "Temporarily Inactive".

I manually changed Third Step One Flight Up on Monday  to "No" and it is correctly showing correctly as "Temporarily Inactive".

Ugh, what a headache. I hope we don't have to manually change them all again.

https://brooklynintergroup.org/brooklyn/meetings/?tsml-day=any

**Comment by michaelvenzor** [comment]
This is for https://brooklynintergroup.org/brooklyn/in-person-meetings/

**Comment by michaelvenzor** [comment]
Sorry, this is the correct link: https://brooklynintergroup.org/brooklyn/meetings/?tsml-day=any

**Comment by joshreisner** [comment]
Oh no, it sounds like you lost data? If you export your meetings to CSV do you see any marked as location temporarily closed?

For what it's worth I haven't heard of this happening on other sites, I wonder what was different in this case...

**Comment by michaelvenzor** [comment]
I don't think we lost data. It's just that all the meetings that were temporarily closed are now set to active (in-person). I can't find where to export the meetings - can you show me where to do that?

**Comment by joshreisner** [comment]
Sure it's on Meetings > Import & Settings on the right side there is a link to download a CSV

**Comment by michaelvenzor** [comment]
Sorry I found it. When I download the CSV, it DOES say Temporarily closed.

**Comment by joshreisner** [comment]
EXCELLENT, so you haven't lost data. Have you customized your theme by any chance? Do you have a custom `archive-meetings.php` page?

**Comment by michaelvenzor** [comment]
I believe so, yes. We've added our own Types. So I'm assuming that means we customized.

**Comment by michaelvenzor** [comment]
I'm going to try adding "Location Temporarily Closed" as a custom type and see if the data displays correctly.

**Comment by michaelvenzor** [comment]
That didn't work, so I deleted all the meetings. I re-uploaded the CSV and they all came back with the correct settings.
