### ISSUE TITLE
[Bug]: inaccurate information drawn into "Location" panel of WP meetings details page. 

### ISSUE THREAD

**Issue by WMikeCarroll** [code4recovery/12-step-meeting-list#534]
### Contact Details

sc-events@comcast.net

### Website With Issue

ContraCostaAA.org

### What happened?

For Zoom Meetings only - 
![ElSobProbs](https://user-images.githubusercontent.com/90402795/134823489-d944b030-1ede-4d19-bad4-8ed9709c0a46.JPG)
)
Inaccurate, apparently info is drawn into the "locations" panel on the meetings detail page
[Meetings CoCoCounty 9-26-2021.xls](https://github.com/code4recovery/12-step-meeting-list/files/7232218/Meetings.CoCoCounty.9-26-2021.xls)
I have attached our Excel file for anyone interested.

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output/errors

```shell
None
```

**Comment by Grateful-Viv** [comment]
Shouldn't address contain the street address, city, state, and zip code? I just downloaded our meetings and there is no city field. Maybe the template is different and the city, state, zip code fields are different.

But if this is an online meeting I am curious why you have 94803 in the zip code field and CA in the State field for the Monday El Sobrante Fellowship 830AM meeting.
