### ISSUE TITLE
Meeting Table of all meetings sorted and displayed in Responsive HTML

### ISSUE THREAD

**Issue by lovethecodelabs** [code4recovery/12-step-meeting-list#54]
A shortcode was put together, calling the tsml functions to loop through an array in foreach for the meetings and times and locations.

https://github.com/lovethecodelabs/12-step-meeting-list/blob/master/includes/shortcodes.php

$mtArray = tsml_get_meetings(); allows all meeting information to be processed by PHP within a wordpress plugin.

A simple meeting class was written and meeting objects instantiated, with a foreach loop. Meeting information is then echoed from the returning get() method of the meeting.

Administrators have editing capabilities when viewing this table with one-click editing in the site frontend.

**Comment by joshreisner** [comment]
Not sure what the request is here. Thrilled that you're finding the plugin useful as a starting point for your endeavors!

**Comment by lovethecodelabs** [comment]
I'm wondering about including this as a shortcode within the TSML codebase to show all meetings in a sorted table.
