### ISSUE TITLE
[Bug]: PDF generator button open window with error

### ISSUE THREAD

**Issue by petermixt** [code4recovery/12-step-meeting-list#544]
### Contact Details

petermixt@gamil.com

### Website With Issue

aalaroundup.org

### What happened?

https://pdf.code4recovery.org/?json=https%3A%2F%2Faalaroundup.org%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dmeetings

returns: We can’t connect to the server at pdf.code4recovery.org.

-pds

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Firefox

**Comment by tech2serve** [comment]
Please try it now. We had a domain transfer hiccup, and it should be fixed. Please let us know.

**Comment by petermixt** [comment]
gets to the generator page then... Returns a new error...
![Screenshot 2021-10-03 at 17-27-43 PDF Generator](https://user-images.githubusercontent.com/38595503/135778871-5ce966aa-15bc-4eee-a77a-94f0016739dc.png)

**Comment by petermixt** [comment]
I've updated the info at github...

[image: Screenshot 2021-10-03 at 17-27-43 PDF Generator.png]
Pete Struve
Petermixt
for AALAroundup.org

**Comment by tech2serve** [comment]
Is your meeting feed close or open?

I'm wondering if this is the issue; my guess is there is something with your link, but I'd like very much to get it figured out.

<img width="678" alt="image" src="https://user-images.githubusercontent.com/31904316/135780087-4213d68b-a9de-4034-892a-821b330420ca.png">

**Comment by petermixt** [comment]
Sharing is set to OPEN
-pds

**Comment by tech2serve** [comment]
Ok. I suggest focusing on the certificate and getting that resolved, and seeing if the issue clears up.

(until it is, I won't look at the feed to validate the link :-) )

**Comment by petermixt** [comment]
I re-installed the certificate and this has fixed the issue.
Your pdf works though it lacks info and configuration ae: copyright though it can be added manually.
Too bad "online" is not included... though I think I understand your reasons why.
Thanks... 
Pete

**Comment by alangrady** [comment]
It's working for me now. ...  _but i wishing that you guys had more styling to it_   😄
