### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by alangrady** [code4recovery/12-step-meeting-list#545]
### Contact Details

alan.grady@inetalliance.net

### Website With Issue

clicking on "Generate Pdf" gets "This site can’t be reached"

### What happened?

When I click on "generate pdf"

This site can’t be reached

https://pdf.code4recovery.org/?json=https%3A%2F%2Fraleighaa.com%2Fwp-admin%2Fadmin-ajax.php%3Faction%3Dmeetings

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by tech2serve** [comment]
Duplicates #544

**Comment by tech2serve** [comment]
Please try it now. We had a domain transfer hiccup, and it should be fixed. Please let us know.
