### ISSUE TITLE
[Bug]: Meeting back button leading to 404 error instead of meeting page

### ISSUE THREAD

**Issue by Carlsans** [code4recovery/12-step-meeting-list#553]
### What happened?

The return button on a specific meeting page lead to an empty page.
![image](https://user-images.githubusercontent.com/46719148/137519427-4fd9384c-6cad-49a5-b3d9-279f19db2544.png)
Thanks again :)

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by Carlsans** [comment]
I would suggest the removal of the meeting folder alltogether ex:
https://aa89.org/wordpress/meetings/?post_type=tsml_meeting
would become :
https://aa89.org/wordpress/?post_type=tsml_meeting
solved it for me :)

**Comment by tech2serve** [comment]
If I understand correctly, this is not really an issue. It sounds like you might have had permalinks that needed to be refreshed? 

If I’m wrong, we can reopen and move this to Q&A Discussion to sort out what is going on with your site. At this time, I don’t see this as a bug.
