### ISSUE TITLE
[Bug]: Default meeting closing time

### ISSUE THREAD

**Issue by CoryBofLI** [code4recovery/12-step-meeting-list#565]
### Contact Details

webmaster@nassauny-aa.org

### What happened?

Bug Report:

While some of our groups due stick to the 1 hour format, many do not. 
Because of this we have never included a closing time for meetings unless they specify one.
When creating a new meeting, and many time when updating a current entry - when the entry gets "updated" a time gets filled in by default.
Sometimes it is exactly 1 hour other times it seems to be a random closing time.
It can take as many as 3 or 4 updates in a row before TSML finally realizes we don't want to include a closing time.

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by 97eighty** [comment]
Hey @CoryBofLI - Trying to reproduce. Which browser are you using? I'm running OS X w/ Safari & Chrome and I simply delete the auto-generated text and it saves the first time.

**Comment by CoryBofLI** [comment]
Using latest Chrome/TSML/Win.
Sometimes it works on 1st update - some times I have to delete closing time and update several times before it finally believes me that I want to leave that field blank.

**Comment by 97eighty** [comment]
@CoryBofLI Had a thought. What hosting provider are you using? Do you have any caching plugins or does the hosting provider cache your website?

**Comment by 97eighty** [comment]
@CoryBofLI I have tried OS X Firefox, OS X Safari, OS X Chrome, Windows Chrome, Windows Firefox and unable to reproduce this error. Without being able to reproduce I'm unable to direct my efforts. Have you seen the error in other configurations or had other users report?
