### ISSUE TITLE
Meetings showing in-person and Zoon[Bug]: 

### ISSUE THREAD

**Issue by keligirl43** [code4recovery/12-step-meeting-list#574]
### Contact Details

keligirl43@gmail.com

### Website With Issue

https://savannahaa.com/meetings/

### What happened?

All of our Zoom meetings are showing in-person as well. We've checked our spreadsheet and it says Zoom only. I'm not sure why this is happening. Any help would be appreciated! 

Thank you
[11.17.21.csv](https://github.com/code4recovery/12-step-meeting-list/files/7581118/11.17.21.csv)
! 

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Chrome

**Comment by Grateful-Viv** [comment]
Look at the actual meetings in your WordPress Admin.  If it is online and not meeting in person, then under Location Information, the answer to the question "Can I currently attend this meeting in person?" should be no.

The way it was explained to me by the developers is there are four types of attendance options. 

1. **In person** - the Location Information question should be "yes".  
2. **Online** - the Location Information question should be "no", but there must be a valid URL or phone number.
3. **In person & online** - the Location Information question should be "yes" & must have a valid address that Google can map to & must have a valid URL or phone number for the online info.
4. **Inactive** - the Location Information question should be "no", and nothing in the URL, but it must have a valid address that Google can map to.

**Comment by tech2serve** [comment]
Looking at your website, it appears you have this figured out. It is not a bug.

If you do need further help, please open a [Discussion](https://github.com/code4recovery/12-step-meeting-list/discussions).
