### ISSUE TITLE
[Bug]: Meeting import: confused #570 in Discussions

### ISSUE THREAD

**Issue by OSAwebsite** [code4recovery/12-step-meeting-list#575]
### Contact Details

os.website.a86@gmail.com

### Website With Issue

al-anon.alateen.on.ca

### What happened?

The field or toggle that is responsible for showing 'part of a group' (or individual meeting) is not part of the import sheet.
Is it possible to include this? I am looking at a mass update of my data (over 300 meetings) and if I can do that using the import feature without having to go back in and adjust that identifier, it would save me a lot of work.

As an in general I feel that the plugin would be better useable for all if any data that determine how a listing is shown in the front end would be accessible, at least via import. I remember somebody saying that the import sheet has not gotten a lot of developer attention and to this day it looks unchanged to me.

My issue is in the Conversations part so if you want more details, let me know.

Thanks for your consideration,
Nicky

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output/errors

```shell
I wish the import sheet was able to produce errors or remarks about the out put. There are none.
Compare what the import of the Calendar plugin looks like: it has a preview option where you can change the field mapping. It would be great if that was part of the meetings plugin as well.
```

**Comment by tech2serve** [comment]
@OSAwebsite,

Please stick to Discussions and leave the Issues feature for developers unless we create an issue from your question. That will help the team keep things organized and plan work.

This issue appears to duplicate #570, for which we provided an answer. Maybe we got it wrong? Or, maybe this is a little different, but still related? In any case, please use that thread to discuss further.

I will offer that it shouldn’t be necessary for you to have a column in the spreadsheet for “Part of a Group” because the importer should detect that if the Group information is completed. This check box is a UI feature to help show what fields you need to complete. This is similar to the dialogue about meeting in person. It isn’t necessary (and actually makes data validation harder) if fields like that are included in an import file.

Duplicates #570.

**Comment by OSAwebsite** [comment]
Thanks for looking at this.
To clarify: can you check the import sheet and see that it indeed chooses
the correct 'part of a group option?
All of my meetings have group information but it does not toggle to the
right choice for me.


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by OSAwebsite** [comment]
Oh hold that. I saw the post. Will check what info goes where. And then get
back to you.


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by OSAwebsite** [comment]
Hah! Found it. Some of my import fields shifted and I was totally blind to
it. Things work fine now. Thanks for your patience and help.

I still would love for the team to provide some sort of rule sheet that
shows with clarity which information is automatically set following which
conditions.
I know most of them now, but it took a long time to find it out and I think
it would be helpful.

It would look something like this:

If information is present in [fields], then the value of [field] is set to
[value]

If we had had such a sheet at the latest big change that sets the tags
(in-person and on-line, temporarily inactive, etc.) it would have been
easier for the non technical folk like myself (when it comes to this kind
of programming) to understand which data are needed in order to get to a
correct posting.

Maybe the team can consider providing this?

Thanks!


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by tech2serve** [comment]
> Hah! Found it. Some of my import fields shifted and I was totally blind to it. Things work fine now. Thanks for your patience and help. I still would love for the team to provide some sort of rule sheet that shows with clarity which information is automatically set following which conditions. I know most of them now, but it took a long time to find it out and I think it would be helpful. It would look something like this: If information is present in [fields], then the value of [field] is set to [value] If we had had such a sheet at the latest big change that sets the tags (in-person and on-line, temporarily inactive, etc.) it would have been easier for the non technical folk like myself (when it comes to this kind of programming) to understand which data are needed in order to get to a correct posting. Maybe the team can consider providing this? Thanks! - Yours in service, Nicky D Ontario South Website Coordinator al-anon.alateen.on.ca *This too will pass...* On Sun, Dec 19, 2021 at 11:29 AM OS Website ***@***.***> wrote:
> […](#)

This is a great idea and would be a nice addition to our new website (@blafving). 

@code4recovery/developers are discussing 2022 goals, and one is to put together a Documentation Team to work on this kind of stuff. It sounds like with the experience you have you might be a good addition/lead? :-)

But if you’re tapped out service-wise, perhaps at least open a new discussion thread (Ideas category) to capture the proposal and what you’ve learned?

**Comment by OSAwebsite** [comment]
If I can help with that in any way, sure. Always up for service!


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by OSAwebsite** [comment]
I have been working on a document that shows the rules for the TSML plugin,
as I understand them.
Where do I send that document so that you might be able to draw from it for
future plugin user documentation?


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by blafving** [comment]
Send it to me Nicky!

Best,
Brandon D. Lafving

Lafving Llc
"Content that converts"
1127 McKean St.
Philadelphia, PA 19148
(215) 375–2475
***@***.***

**Comment by OSAwebsite** [comment]
Attached...

It is a 2 part document: first I tried to capture what the rules were, then
I make some suggestions for what I would consider improvements.
I might be making wrong assumptions or propose something that is not
within your working principles: that is fine. I just wanted to commit them
to one document. Hope this adds some value and clarity and I am always
available for testing of helping with user documentation in the future.

Cheers,



-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*
