### ISSUE TITLE
Update button is greyed out when trying to update a meeting.[Bug]: 

### ISSUE THREAD

**Issue by district6wc** [code4recovery/12-step-meeting-list#578]
### Contact Details

district6wc@gmail.com

### Website With Issue

https://alanonalateen6nc.org/wp-admin/post.php?post=569&action=edit

### What happened?

A bug happened!  I'm trying to update a meeting and remove the zoom information to make it a in-person meeting.  When all my changes have ben made, the only option is Preview changes instead of update.  Even when I click on Preview changes, nothing happens.

I have tried using chrome and edge browsers.  Wordpress version 5.8.2 

12 Steps Meeting List version 3.
![Meeting Upddatebutton](https://user-images.githubusercontent.com/1336342/144139030-305e7ccc-ef46-4a2c-bdff-c114d085eadc.JPG)
12

### TSML Version

Latest (default)

### Wordpress Version

Other (Identify version in text above)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

**Comment by district6wc** [comment]
When I hit the refresh button on the browser, the update button appears but the is greyed out after a second.

**Comment by district6wc** [comment]
Well, I have figured out what is wrong, I think.  I noticed map was not showing locations and was blank. I updated the API under import and settings and now I'm able to update a meeting with no problem.  However, the API flashes the map and them give error that "This page can't load Google Maps correctly".  For development purposes only

**Comment by tech2serve** [comment]
You’re on the right track. There is a problem with your API key. Most users have an easier time with MapBox, but if you prefer to use Google you’ll need to fix your API key.

**Comment by district6wc** [comment]
I also found that somehow, my API needed to be relinked with the billing account.  When I linked it back. everything worked perfectly again.
