### ISSUE TITLE
Meetings on one street will not update

### ISSUE THREAD

**Issue by ljmorrone** [code4recovery/12-step-meeting-list#579]
**Please help**

The location information is not updating to "yes" for "Can I currently attend this meeting in person?" for two of our meetings. The two meetings are at the same location. This is not happening for other meetings at other locations. Every time I select "yes" and click "update", the selection reverts back to "no". 

This meeting https://albuquerqueaa.org/meetings/serenity-group-3/ shows as Temporarily Inactive when it is active. 

This meeting https://albuquerqueaa.org/meetings/progress-not-perfection-2/ shows as Online when it is both online and in-person.

I am having a similar issue with this meeting https://albuquerqueaa.org/meetings/serendipity-group/, where I am trying to add a URL in the Meeting Information, but every time that I put in the URL and click 'update', the URL goes away and the meeting is not updated. I created a new meeting listing with the same information, but ran into the same problem. This meeting and the two meetings linked below are on the same street: Montaño Rd NW in Albuquerque. This meeting is not at the same location as the other two, but is on the same street. Any insight in how to get these meeting listings up-tp-date and accurate would be greatly appreciated.  

I believe I am using plug-in version 3.12, and WordPress version 5.8.2.

Thank you!!!

_Originally posted by @ljmorrone in https://github.com/code4recovery/12-step-meeting-list/discussions/561_

**Comment by Gary4593** [comment]
word press 5.8 does not support meeting guide as of yet -  I had my wordpress auto updated and have the same issue - when I go to publish a meeting it stayed in draft which was not available prior - my meeting do not show up - wordpress updated messed it up and even after going back to 5.6  - My meetings do not appear - frustrating!!!

**Comment by ljmorrone** [comment]
> word press 5.8 does not support meeting guide as of yet - I had my wordpress auto updated and have the same issue - when I go to publish a meeting it stayed in draft which was not available prior - my meeting do not show up - wordpress updated messed it up and even after going back to 5.6 - My meetings do not appear - frustrating!!!

I think this is a different issue than mine! I have been able to publish meeting just fine. I have been able to update other meetings just fine. This is not the same problem.

**Comment by tech2serve** [comment]
Duplicates #561
