### ISSUE TITLE
Add support for API (Geocoding) Gateway

### ISSUE THREAD

**Issue by tech2serve** [code4recovery/12-step-meeting-list#592]
### Contact Details

tim@code4recovery.org

### Requested Feature/Enhancment

The interfaces for the endpoints of the API Gateway are [described here](https://github.com/code4recovery/api-gateway/tree/develop#interfaces-to-use-gateway-v1-endpoints).

TSML should be modified to remove the current embedded geocoding feature, and replaced with calls to the new API Gateway. 

Actual usage of the API Gateway by a site first requires registration. Once a valid registration payload is sent to the API Gateway, an API Token is emailed to the registrant. This user then will need to be able to enter the API Token into TSML. This token will then need to be included in geocoding requests. 

Should end-users be able to override use of the API Gateway by entering their own Google Geocoding API Key into a child theme? If so, then the code to parse Google's response will need to be retained as the API Gateway provides a generic standardized response. 

Work is progressing on deploying the v1.0 of the API Gateway. The beta deployment of this is available for testing if necessary. Both links will be shared privately. 

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by 97eighty** [comment]
@tech2serve To ease our end user pain and suffering I wonder if we should try and handle this all without user intervention. Pull the email address and other meta from the WordPress install and have a key returned via the response. The user would still receive an email with the key for future use. We might even have a confirmation link in the email.

**Comment by tech2serve** [comment]
> @tech2serve To ease our end user pain and suffering I wonder if we should try and handle this all without user intervention. Pull the email address and other meta from the WordPress install and have a key returned via the response. The user would still receive an email with the key for future use. We might even have a confirmation link in the email.

I've been sitting on a public reply to this, but I believe it is time :-)

I support the notion of making it easier for the end user, but remain committed to the validation of an email address (on record) that we can use to communicate with the web servant when appropriate. 

I do believe there are some secondary effects though:

1. There should be a step in the process that has them validate the email address in the Wordpress config. There is a good chance the current email address for the site does not match the email address of the current webmaster. 
2. We will still need to communicate with the user about the need to click on the confirmation link in order for the registration to remain valid. 
3. We need to decide how much time they have to validate the email address before the registration request and API Token are deleted. I'm leaning towards a week (but this is arbitrary).

There may be more, but 2 and 3 already will require tweaks to the Gateway.

**Comment by tech2serve** [comment]
An email address is no longer required for registration (although it remains preferred to be provided for the reasons listed above).

The API Token is returned with the registration process so no user intervention is required.

Can we shoot for this in v3.15 or v3.16? 

One approach for a transition period is to have the gateway be the preferred for geolocation, and if for some reason a successful response is not received, TSML reverts to legacy. Not sure if this would work for csv imports into a new database, but we can test that.

**Comment by joshreisner** [comment]
as also noted on https://github.com/code4recovery/api-gateway/issues/4 -- getting the following error when not passing email, as well as when sending an already-registered email:

```
{
    "name": "REGISTRATION_CREATION_ERROR",
    "serviceError": "APIError",
    "httpCode": 500,
    "isOperational": false
}
```

**Comment by joshreisner** [comment]
We have a number of changes already slated for `3.14.3` and so my rec is to add this to the `3.15` milestone (adding support for the gateway). 

Making default can potentially be part of `3.16` (as well as migrating people who are using the existing alpha (known in the plugin as BETA) gateway to this method.

**Comment by joshreisner** [comment]
I definitely agree that we should do this, but since this is not actionable now i'm going to close the issue. 

If a new service is created that allows the API workflow to stay the same (same return, no registration process) we can open a new issue and it should be an easy fix on the TSML side
