### ISSUE TITLE
Widget on WordPress Dashboard

### ISSUE THREAD

**Issue by brianw-area24** [code4recovery/12-step-meeting-list#595]
### Requested Feature/Enhancment

Add a widget to the WordPress Dashboard. Initially, this widget should show information about the new Code for Recovery web site, including a call out to the new Donate option.

It is anticipated that the information in this widget could change quite often with new releases, and may even go away in some releases if we don't have anything we need to highlight.

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by 97eighty** [comment]
@brianw-area24 Good idea. Had a thought. What about pulling a page or feed from the code4recovery website? This way it can be updated by the website group and populated in the dashboard.

**Comment by brianw-area24** [comment]
I can't take credit for the idea, @tech2serve suggested it during our call earlier today. I also like this idea from @97eighty to pull from the web site, maybe now, maybe a future release. Depends on how much work it would be on the website to get something to pull.

I could also see doing something here to highlight when feeds have changes as an enhancement to the feed notification that's being worked on?

For now, I'm going to put up a Pull Release with a static message, but we can always change it...
