### ISSUE TITLE
Remove the word District from District Dropdown

### ISSUE THREAD

**Issue by tech2serve** [code4recovery/12-step-meeting-list#597]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/586

<div type='discussions-op-text'>

<sup>Originally posted by **Grateful-Viv** December  7, 2021</sup>
I can select "District" from the District dropdown when adding/editing a meeting and that should not be the case. It should be removed and certainly should not be the default choice. 

In our case, we have four districts entered as possible options and only these four should show up on the list.

![District](https://user-images.githubusercontent.com/62247421/145046562-9e4b94be-a1cd-40b1-98d0-2bc0582e3847.png)

</div>

**Comment by 97eighty** [comment]
Merged into Develop with #621
