### ISSUE TITLE
Don't use PHP Anonymous Functions

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#60]
Users with PHP < 5.3 will get the following error when trying to update the plugin:

```
Parse error: syntax error, unexpected T_FUNCTION in /home/content/82/14032682/html/meetings/wp-content/plugins/12-step-meeting-list/includes/functions.php on line 499 
```

This is due to some code I checked in on 11/22 in b07e113

**Comment by tech2serve** [comment]
Should we be supporting PHP5? Version 5.6, the last of that major release, reach EOL over a year ago and doesn't appear to even get security updates.

Wordpress suggests 7.3+.

My vote is to drop support after this unless there is a compelling reason to maintain it. 

Other thoughts/votes?

**Comment by joshreisner** [comment]
I would guess 95% of sites running it are on 5.x. Let's look and see if we can release an update that requires 5.6+ so that users like Greg who have a lower version don't see the update and can continue to run the existing version.

Also we should finalize our geocoding plan first if a segment of users won't get updates anymore.

**Comment by tech2serve** [comment]
You're right. My call for the [demise of PHP 5.x](https://w3techs.com/technologies/details/pl-php) is premature :-)

This is "force" me to get docker running to so I get a PHP5 test platform set up. However, I don't think I'm going to get that done in time to fully test the issue he had, and you clearly understood the underlying issue, so I'll work on releasing it so he get his meetings list working again (although, it isn't clear the the displays in publicly; might just be to feed the app?)

**Comment by pjaudiomv** [comment]
Seems like an easy enough fix, I wouldn't spend much time fixing things to support pre 5.6.  It's just enabling poor practices. Going forward 7.1 could be supported version. That'd be my vote.
