### ISSUE TITLE
Sudden issues with menu options: not sure it is tsml related but asking for input

### ISSUE THREAD

**Issue by 97eighty** [code4recovery/12-step-meeting-list#606]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/605

<div type='discussions-op-text'>

<sup>Originally posted by **OSAwebsite** December 24, 2021</sup>
I am writing this to find out if any of you have seen the same behaviour described below. When you read on, you will see why I am posting here. As the heading says: I have no idea if there is a connection to the tsml plugin, but better safe than sorry.

By accident I found out yesterday that some of my Wordpress menu items were damaged. The original label of the items flipped to 'new meeting' when I checked an existing menu, without making a change. The menu still showed the link to the correct webpage. Just the label was messed up. I was stumped. I ended up finding multiple errors in the new Wordpress widget are, even referring to plugins I don't even have. The only thing I found online to rectify this was to install a plugin 'classic widget'. The issue was largely gone after that, but it does pop up now and then.

I am on WP 5.8.2 and I am on TSML 3.12.1. I have a very straight forward website with no commenting or ping backs. I have limited visuals and most of them are from screenshots, so not very big. I talked to my hosting provider the other day and they said that the size of the website is not even at 50% of what I am allowed with shared hosting. I am not on managed Wordpress, I am on Wordpress with CPanel at GoDaddy.

The reason I am posting this here is to see if others have had this issue as well and how they fixed it. I am curious why the menu item label changed to 'new meeting'. There really is no reason for that to happen and it sort of hints to TSML because that is the only 'meeting' thing I have on the website.

Looking forward to your comments. If any of you have ideas of where to look when this starts happening again, I would be most grateful to hear. I am not a Wordpress specialist. I have been the website coordinator for my area for 2 years now and things have run smoothly in general. This is the first time something happens that I really do not understand. It is kind of scary because I have no clue of where to look to troubleshoot.

I now have my old widget area back, the plugin 'Classic widget' gets rid of the block structure in Wordpress 5.8.2 that was announced with so much fanfare. I have found no information about a fix.

Any help welcome!

Thanks for reading.....

Happy holidays!

Nicky</div>

**Comment by kiyote33** [comment]
Nice fix Mark. Did the job nicely...
