### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by OSAwebsite** [code4recovery/12-step-meeting-list#629]
### Contact Details

os.website.a86@gmail.com

### Website With Issue

al-anon.alateen.on.ca

### What happened?

A bug happened!
'Types' are no longer imported.

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Safari

**Comment by brianw-area24** [comment]
Duplicate of Issue #633
