### ISSUE TITLE
[Bug]: Import sheet errors

### ISSUE THREAD

**Issue by OSAwebsite** [code4recovery/12-step-meeting-list#633]
### Contact Details

os.website.a86@gmail.com

### Website With Issue

al-anon-alateen.on.ca

### What happened?

Please see the attached documentation about the failing TSML import sheet.
I am posting this here because it seems like a technical issue but feel free to move it to another section. As long as the team reads this and responds, I would be fine with that.

[TSML troubles.pdf](https://github.com/code4recovery/12-step-meeting-list/files/7825811/TSML.troubles.pdf)

[503626test.csv](https://github.com/code4recovery/12-step-meeting-list/files/7825766/503626test.csv)

Thanks for your consideration,

Nicky D

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Safari

**Comment by 97eighty** [comment]
@OSAwebsite Thank you for your efforts in documenting the process you went through. I'm sorry you're having difficulty. I'm trying to understand the entire picture. Please tell me if this is correct:

1. You have your own data in a different database.
2. You have an export process to CSV
3. You are using WordPress and trying to import the CSV file
4. It used to work but now its broken.

Is this correct?

A few more answers might help.

1. Is your WordPress meeting database empty or are the same meetings already present?

Could you attach a complete CSV file from your database?

Could you attach a CSV export from WordPress, if these meetings exist?

I may have more questions as I look at the data.

**Comment by brianw-area24** [comment]
Please take a closer look at CSV file you posted above. When I open that file, I'm only seeing one meeting, and that meeting has things in the wrong columns. The group notes are in the column "Sub District", types are in the Group Notes column, and the Types column is blank.

Trying to import the CSV file as provided in this post will cause issues as you describe because the information is in the wrong columns.

**Comment by OSAwebsite** [comment]
Wow. I bow my head in shame. This was pointed out to me before and I
thought I had fixed it but one little sliver was still there.
Thanks so much for pointing this out: I totally missed it. Self-inflicted
agony.....


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by OSAwebsite** [comment]
Can you still address the other issues?

4. Feedback to users during import
I am using the Events Calendar for events and they offer a preview. I use that to check if fields line up. It would have instantly made clear to me where my error was and I would have been able to correct it. I would be good to see the field mapping in the same way in TSML and take the whole import logic out of the dark box.
It saves you a lot of explanation too towards users.

5. Adjust bulk actions:
I am no Wordpress or plugin expert but why is there no action to set a meeting to temporarily inactive, due to closures, when there is one for ‘Re-open for in-person attendees’? Especially these days meeting stop and restart often. By the same token, is it possible to have a bulk action to publish a selected series of meetings, or, alternatively, to set them to draft?

Somebody on github suggested “set to e-open” to publish draft meetings without further explanation and I did not understand what to do with that. Do you?

The way I did the restore yesterday was to get all old previously deleted meetings from the trash, but that sets them to draft so I had to do all 306 manually. I know all of this was due to the import error that I completely missed, but I can see this as a scenario that might re-occur. Not the import error, but having to do the same action for a bunch of meetings, be it publishing, reopening or closing.

Thanks!

**Comment by OSAwebsite** [comment]
I did a follow up today and have some findings I will share later. We are
not out of the woods yet... I am having someone double chek me so I don't
use up your time with any obvious mistakes... :)


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by OSAwebsite** [comment]
OK, a new day, new opportunities.
I critically inspected my data in my off-website database.
At the recommendation of an IT colleague I made sure that there are no hard
returns in any of the 3 fields that typically do have them in my own files:

   - The notes field shown underneath the checkboxes in the TSML edit mode
   - The venue address
   - The group notes field shown in the Group Contact section in the TSML
   edit mode

I then imported the full meeting set in my staging site.

   - All types were properly imported.
   - The yes/no toggle for in person attendance was correctly set

*Yay!*

The group contact notes however, still fail....

*Yuc...*

I tested and you can repeat the following in your own environment to test
that you see the same thing with the two .csv's attached:

   1. I create a .csv for a meeting of an existing group, that has *never*
   been uploaded before. Information after import seems correct.
   2. Mimicking my usual MO, I then delete the meeting created in step 1
   because I want a full new upload with changes
   3. I make a small change in the meeting contact notes section of my
   files, and create a new .csv and import it into TSML. The changed meeting
   contact notes are not imported. Instead, I see the notes I imported in step
   1.

Result in group notes stay the same, despite new content in .csv file:
[image: Screen Shot 2022-01-07 at 6.31.48 PM.png]
What this looks like to me, is that in the background, group notes of
meetings that were created in the past, linger in the plugin and are
re-used. I have no idea why that is: that is for you to figure out. What I
expect to happen is that, when I delete a meeting in order to re-import it
with new details, those new details are imported and shown in the listing.
Especially when I have distinguished a meeting to be a part of a group.
Maybe that is where the misconception is. My meeting notes are stored in
the group contact section, however they can be different per meeting.
Highly unlikely but they can. In any case, I should be able to change them
via an upload.


Looking forward to your feedback!


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by OSAwebsite** [comment]
Final note:
I have changed my database to show what was previously shown in the Group
notes in the Meeting notes (underneath the checkboxes in the admin page).

Now I really do see this shortcoming in the Group Details in motion.
I had removed the information previously there and just replaced it with
much less (but still relevant) information and I cannot get rid of what was
there originally.

So before I can make my change on the real site, I need to be able to wipe
whatever is on file in the plugin and start from scratch.
I hope this can be done without re-installing the plugin? And will a
re-install even do it - or will the plugin still remember what was there
before? I hope not!

I really do need access to this group contact information bit via the
import sheet.


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by OSAwebsite** [comment]
I have found a workaround.
I used the third import option, delete everything. And imported one bogus
group to see if it worked and it did.

So this is probably my best option for the complete refresh on the live
site, later this weekend: delete everything and then start anew with the
newly structured data.

I had one group in London that got an address error. Not sure why. I looked
up the location and the name of the venue and it seemed to all be fine. So
I adjusted that one manually. Glad I did not have to do a re-install of the
plugin.

Anyway, I am very tired now so I am calling it a day. I made progress, that
is always good.

**Comment by brianw-area24** [comment]
Glad to hear that you are making progress. In your situation, I think you're right in using the third option to "delete all meetings, locations, groups, districts, and regions". This should ensure that your WordPress database has clean information.
