### ISSUE TITLE
Filtering by district and sub-districts

### ISSUE THREAD

**Issue by TheGreenSourcerer** [code4recovery/12-step-meeting-list#64]
# Current behavior

Currently, when I select a district on an archive page only the meetings of the groups directly attached to this district are searched.
Is there any way to change this behavior so that all the meetings from sub-districts are displayed as well?

As an example – this list displays no meeting:

https://spis.aa.org.pl/index.php/meetings/?tsml-day=any&tsml-district=region-galicja

# Changed behavior

What I would like to achieve is that is will display all the meetings from intergrupa-kresy AND intergrupa-malopolska AND … AND intergrupa-sadecka which are the sub-districts of the region-galicja district. In other words – select them recursively by the district.

# Proposed solution

WDYT about adding all taxonomy terms - from the top to the bottom of the hierarchy - to the meeting post type?
With this approach, it should be pretty easy to query all the meetings that contain any of the district/sub-district.
The downside is the need for migrating the existing meetings data.

**Comment by joshreisner** [comment]
I could be wrong, but at first glance this seems like a simple bug. 

In the same way that https://spis.aa.org.pl/index.php/meetings/?tsml-day=any&tsml-region=polska includes all the sub-regions, filtering by a district *should* be including its sub-districts, although I see that it is not.

What I'm saying is, I think we need to dig into the filtering to see what's going on, but probably not change the data structure.

**Comment by TheGreenSourcerer** [comment]
Any updates on this issue?

**Comment by TheGreenSourcerer** [comment]
When do you plan to release this fix? 😊
