### ISSUE TITLE
Location Approximate Not Updating

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#677]
Here are the lines that update location when saving, when the location already exists in the database: https://github.com/code4recovery/12-step-meeting-list/blob/master/includes/save.php#L241-L267

We need to copy this line: https://github.com/code4recovery/12-step-meeting-list/blob/master/includes/save.php#L279 and have it execute when saving and the location already exists, so we should probably paste it in that block above.

The reason is that when the geocoder is in conflict with the location's saved data, the location saved data should get overwritten.

Not having this is preventing CER from updating the "can i attend this meeting" value, because the location can't get set to not-approximate.

See https://github.com/code4recovery/12-step-meeting-list/discussions/663 for more info

CC @kiyote33

**Comment by brianw-area24** [comment]
Looking more into this. This fix (PR #687) will save "approximate" when the form is saved. However, it won't help for any location that is currently in the database incorrectly. Do we need to add something to database_updates.php to update the approximate location in the database if it doesn't match what's in the address cache?

**Comment by joshreisner** [comment]
you could! this addresses a complaint about difficulty applying changes when saving, so my temptation would be to move forward with this simple fix and roll out a more ambitious one only if requested.

**Comment by julien-paris** [comment]
Hi folks, jumping in to know if there is any progress on this issue. 
We are still stuck on our side. 
Much thanks in advance, 
Julien

**Comment by joshreisner** [comment]
hi @julien-paris the team released version `3.13` a few hours ago, were you able to try it yet?

**Comment by julien-paris** [comment]
Hi @joshreisner  I waited a little to answer because I wanted the whole team to go through the process to make sure all is fine, and I can confirm it is now working. 
What a relief! 
Thanks so much for your service folks.

**Comment by joshreisner** [comment]
Yay! Thanks! Thanks also to @kiyote33 and @brianw-area24 for jumping on this 🥇
