### ISSUE TITLE
Widgets for TSML UI

### ISSUE THREAD

**Issue by Grateful-Viv** [code4recovery/12-step-meeting-list#686]
I am using the widgets for the TSML plugin. Specifically, custom HTML for Meeting Top where I have a lot of information to convey, and Meeting Detail Bottom where I have more custom HTML. I like these options, and hope this will be available on the front end in future rollouts.

If I add the header stuff on the page and then the shortcode underneath, it will be there in the meeting detail view and that is not what I want.

You can see what is in use here: https://sussexaa.org/meetings

**Comment by brianw-area24** [comment]
This a part of version 3.14

**Comment by brianw-area24** [comment]
Reopening issue, based on #768, I'm liking @joshreisner's suggestion here, https://github.com/code4recovery/12-step-meeting-list/issues/686#issuecomment-1037300915

I think the CSS would look something like:
`body.tsml-ui-meeting .widgets.meetings-widgets.meetings-widgets-top,
body.tsml-ui-meeting .widgets.meetings-widgets.meetings-widgets-top {
  display: none;
}`

**Comment by joshreisner** [comment]
these classes are added to TSML UI now. in TSML we should be able to do something like:
```
body.tsml-ui {
    .meetings-widgets, .meeting-widgets { display: none; }
    &.tsml-ui-table, &.tsml-ui-map {
        .meetings-widgets-top, .meetings-widgets-bottom { display: block; }
    }
    &.tsml-ui-meeting {
        .meeting-widgets-bottom { display: block; }
    }
}
```

**Comment by lovethecodelabs** [comment]
Widgets in Plain Vanilla JS & TSML meeting API
[next.zip](https://github.com/code4recovery/12-step-meeting-list/files/10669883/next.zip)

**Comment by lovethecodelabs** [comment]
The widget code posted is a fully working plain JavaScript that shows the next upcoming Meetings for today, configured for querying a Central Office website.  If this could be merged or set up as a TSMI-UI widget it could be very helpful.  The zipfile is composed of html (less than 20 lines), js (76 lines), and css (less than 20 lines)

This would be great for an additional widget, again.

**Comment by joshreisner** [comment]
thanks @lovethecodelabs the purpose of this issue is to enable regular WordPress widgets in the correct places on the main meetings page when using the TSML UI appearance, not to add new widgets to TSML

we're not looking to add new javascript add-ons, but if you want you are welcome to make a pull request :)

**Comment by lovethecodelabs** [comment]
Oops already replied on github without seeing this email.I'd love to attempt a new widget to add to tsml!On Feb 7, 2023 12:44 PM, Josh Reisner ***@***.***> wrote:
thanks @lovethecodelabs the purpose of this issue is to enable regular WordPress widgets in the correct places on the main meetings page when using the TSML UI appearance, not to add new widgets to TSML
we're not looking to add new javascript add-ons, but if you want you are welcome to make a pull request :)

**Comment by joshreisner** [comment]
ok! probably before preparing the PR it would be good to create a new discussion and describe the gap that this widget would fill (how would it improve on the existing upcoming meetings widget?)

you're also welcome to join us in our biweekly zoom meetings and bring it up as a topic. we have one coming up this saturday at 10am PT

**Comment by lovethecodelabs** [comment]
I'm not sure if a new "View" can be created in TSML-UI, to accommodate a smaller area of data for Next (Upcoming) Meetings, and I'm not sure how to access the React way of fetching the meetings or the React way of comparing the meeting times, days etc.

I'd love to discuss Saturday 10am, and as it stands, the existing Next plain JS gets all meetings from API, parses the json, and sorts it chronologically.  The improved version then loops through the next 12 meetings if they are not inactive...

WIll talk on Saturday, thank you!!

**Comment by joshreisner** [comment]
Hi @Grateful-Viv just want to check in on this ancient issue. We have a fix ready to go for this but just wanted to alert you that it means that the "Please help us keep the fellowship informed" would disappear from the meeting detail screens on your website.

To be clear, users will still see it when they land on the `/meetings` page, but it will disappear when they click on a meeting, and then reappear when clicking back.

It will add the ability for you to have a different message show up below the meeting detail that does not appear below the main meeting list.

Still go ahead? I think it's a good change but wanted to check if you still wanted it.

**Comment by Grateful-Viv** [comment]
Hi @joshreisner 

I got used to seeing what was in the meetings top widget appear in both the `/meetings` page and the meeting detail page. Same with the meetings bottom widget (which you would have to scroll a long way down to get to read it on the `/meetings` page. But it was nice to see it there and the meeting detail bottom widget was no longer displaying anything.

Are you saying this new TSML release will no longer include whatever info is posted in the meetings top widget? There is no widget called meeting detail top.

**Comment by joshreisner** [comment]
i suspected you might have! if we move forward with the PR, then yes

we can also close the ticket and not make any changes

**Comment by Grateful-Viv** [comment]
Does this mean it's going to stay the way it currently is?

Thanks.

**Comment by joshreisner** [comment]
that's up to you! should we keep it how it is or proceed with implementing the change? 

i don't really have an opinion on it -- i just don't want to make the change if it's not an improvement. we're not hearing other requests to make the change from what i can tell

**Comment by joshreisner** [comment]
done, thanks. we can always revisit if needed.
