### ISSUE TITLE
Meeting time should not reset to default when day of week changes

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#688]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/652

<div type='discussions-op-text'>

<sup>Originally posted by **OSAwebsite** January 22, 2022</sup>
This has bitten me in the backside more than once and I would like to enter an urgent change request:

Whenever I change the day of a meeting, the times jumps to 12am. This makes no sense to me whatsoever.
Sometimes a group changes their meeting day, but the time usually stays the same. Sometimes the day is given to me in error so I want to be quick and adjust it and then I often miss the time change.

I would like the time, if there is one entered already, to stay the same, even when I change the day. It is very easy to miss and I don't see the reason why it would be changed if all I do is adjust the day....

Pretty please?
Nicky</div>

**Comment by OSAwebsite** [comment]
I just noticed that the latest plugin update still has not fixed this. Please do as soon as possible.
Thanks!

**Comment by brianw-area24** [comment]
I'm working on another issue how, and this is the next one on the list. Hopefully it will make the next release.

**Comment by OSAwebsite** [comment]
Okidoki!


-
Yours in service,
Nicky D
Ontario South Website Coordinator
al-anon.alateen.on.ca

*This too will pass...*

**Comment by brianw-area24** [comment]
Included in v3.14
