### ISSUE TITLE
Mobile Meeting Guide Initial Screen = FOR LIST OF TEMPORARY MEETING CLOSURES - CHOOSE TYPE = "TEMPORARY CLOSURE"

### ISSUE THREAD

**Issue by CCFAAWebmaster** [code4recovery/12-step-meeting-list#71]
Thanks for new Type = "Temporary Closure",  We are using & works as advertised. Well done.

In WP, Widget, was able to locate where to put header = <b>ATTN: FOR LIST OF TEMPORARY MEETING CLOSURES - CHOOSE TYPE = <font color="red">"TEMPORARY CLOSURE"</font></b>

http://aasacramento.org/meetings/

Can there be a (mobile) Meeting Guide entry splash page with same note?

**Comment by CCFAAWebmaster** [comment]
Apologies for the shout + lack of filter :/

**Comment by tech2serve** [comment]
This GitHub space is only for `12 Step Meeting List` plugin and not for the Meeting Guide App which is managed by GSO. Please contact them with suggestions for changes.
