### ISSUE TITLE
Filtered meetings dissapeared

### ISSUE THREAD

**Issue by TheGreenSourcerer** [code4recovery/12-step-meeting-list#73]
**Describe the bug**

After the recent update, when I try to filter the meetings list by district/sub-district/areas, in some cases the list blinks and disappears immediately. When I hit refresh (`CTRL`+`R`/`CMD`+`R`) all the filtered meetings were displayed correctly.

The bug is obviously related to the user filter action.

**To Reproduce**

1. Go to https://spis.aa.org.pl/index.php/meetings/?tsml-day=any&tsml-district=intergrupa-chelmska
2. In "Districts" filter, expand "Region Lublin" and click "Intergrupa Lubelska"
3. The lists blinks and an **empty list is displayed**
4. Hit the browser refresh button (or `CTRL`+`R`/`CMD`+`R`)
5. The list is displayed correctly

The same happens on other sub-districts and areas filters as well.

In some cases, only a part of the list is displayed on changing the filter (and the whole when refreshed).

**Expected behavior**

The list should be displayed with all the meetings assigned to specific sub-district.

**Screenshots**

After changing the sub-district filer:

![image](https://user-images.githubusercontent.com/51343011/77117223-dce29500-6a31-11ea-84e4-e933704737a1.png)

After refreshing the page:

![image](https://user-images.githubusercontent.com/51343011/77117334-19ae8c00-6a32-11ea-8539-90280c9cfa6d.png)

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser - observed on Chrome and Edge
 - Version - both were the latest versions

**Smartphone (please complete the following information):**

Was not testes on smartphone

**Additional context**

The network console shows a successful AXAJ call for filtered resources.

After changing the filter, the following JS error is displayed on the browser console:

```
Uncaught TypeError: Cannot read property 'split' of undefined
    at formatAddress (public.min.js?ver=3.5.3:1)
    at Object.<anonymous> (public.min.js?ver=3.5.3:1)
    at Function.each (jquery.js?ver=1.12.4-wp:2)
    at Object.success (public.min.js?ver=3.5.3:1)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at x (jquery.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery.js?ver=1.12.4-wp:4)
```

Looks like an unhandled null pointer exception.

**Comment by TheGreenSourcerer** [comment]
One thing that I observed - for some reason, in the meetings marked as "Temporary closed" ("Tymczasowo zawieszony" in Polish), the adres dissapeared in the source data... Maybe those two issues are linked?

**Comment by tech2serve** [comment]
I'm trying to reproduce this behavior. In my first attempt using your website and Safari, the list displayed correctly after I took the filtering steps you provided.

I'll try Chrome and Firefox next. 

What theme are you using?

**Comment by tech2serve** [comment]
> One thing that I observed - for some reason, in the meetings marked as "Temporary closed" ("Tymczasowo zawieszony" in Polish), the address disappeared in the source data... Maybe those two issues are linked?

Are you saying that any meeting for which you've added the TC tag has had it's address disappear? If so, I'm definitely not seeing that behavior. I see on your screen where it isn't displayed, but if it is no longer in your database, then something weird is happening on your system. We could have a CSS issue, but nothing we've changed, AFAIK, has touched the database. Please confirm on your backend and post a screen cap of that.

I've only been able to get the list not display one time. And I've only seen the `split` error once. I'll focus in on that.

**Comment by TheGreenSourcerer** [comment]
@tech2serve

> What theme are you using?

We are using "Twenty Nineteen" theme, with no customizations.

> Are you saying that any meeting for which you've added the TC tag has had its address disappear?

Yes and no 🙂 I think this should be treated as coincidence of two things that happened in more or less the same time.

Before the "Temporary closed" feature was introduced, some of our meetings list admins used to hide the meetings by moving them to trash... (which, I know, is not the optimal way of doing this). When the TC option was added, they started to move those meetings back from trash to published state and adding TC attribute at the same time. 

It looks like the meetings that were moved to the trash and restored back are missing the address field after this operation. It's a pure coincidence that they also happen to have TC attribute assigned. The meetings have just the TC attribute assigned (with no state changes) are displayed fine.

Although this particular issue is pure on the front-end side (js logic not expecting an empty address field), there might be still some bug in the move-to-trash/restore logic. Should I create another issue on this on GH?

**Comment by tech2serve** [comment]
I suggest starting with making sure all meetings have addresses and republishing them. That field shouldn't be blank; if it is, then yes that is going to cause the error in question.

**Comment by TheGreenSourcerer** [comment]
List admins are already working on filling the missing addresses and I bet that this will cover the front end issue.

Do you plan to add the null-check in JS?

**Comment by tech2serve** [comment]
So we need to look at that as I thought it was already there. That is why I'm trying to figure out how the addresses end up missing in the first place. That shouldn't happen, and I think I've another website where this issue is happening.

Since you have replaced the addresses, have you seen any more issues?

Did/do you have the Berlin "plugin" installed?

**Comment by TheGreenSourcerer** [comment]
Nope, after replacing the addresses I don't see any more issues

We don't have the Berlin "plugin" installed (whatever it is 😄 )

**Comment by tech2serve** [comment]
Thank you. That rules out (although it was a long shot) the work done by one of our members in Europe. 

We suspect the problem is with the logic of when a meeting is restored from trash, so that is where I'll focus.

**Comment by TheGreenSourcerer** [comment]
Was this issue solved on the front end side (null-check in JS)?

**Comment by joshreisner** [comment]
Looks like you might have a meeting that has an undefined address. The code should be more resilient here, we should check if address is defined:

https://github.com/code4recovery/12-step-meeting-list/blob/90d5d6c879571b8e4dddd004413aa39bd4db3052/assets/src/maps.js#L80

For now though you should check to see if you have any meetings with no address and see if you can give them one.

**Comment by joshreisner** [comment]
Ok judging by the screenshot all the addresses are blank :)

This isn't something that's easy for me to reproduce locally because WP won't let me save without an address. Did you do maybe use a CSV import @TheGreenSourcerer?

**Comment by TheGreenSourcerer** [comment]
> Ok judging by the screenshot all the addresses are blank :)
> 
> This isn't something that's easy for me to reproduce locally because WP won't let me save without an address. Did you do maybe use a CSV import @TheGreenSourcerer?

I believe that there was another reason. I talked with a servant who was updating the meetings. When the covid epidemy started and the "Temporary closed" attribute was not yet available, he the temporarily closed meetings to the trash. When the TC feature was introduced he restored them back from trash. Those meetings were missing the address part in location
