### ISSUE TITLE
Incompatibility between TSML UI shortcode and GoDaddy website caching

### ISSUE THREAD

**Issue by toddjsaunders** [code4recovery/12-step-meeting-list#754]
We've been using TSML-UI with no issues for a while at http://gayaainthedesert.org/meetinglist

Sometime overnight or early this morning the plug-in stopped working, and is showing the message: "An error was encountered loading the data."

We hadn't done any updates to the site other than some text edits on the home page.

Looking around, I saw a message that our theme was out of date, after updating, no change to the plug-in.

Thankfully the older interface is working at http://gayaainthedesert.org/meetings  so for now I've redirected to that page.

Any help would be greatly appreciated!

**Comment by 97eighty** [comment]
Hi @toddjsaunders. Interesting problem you've brought us. I've never used GoDaddy's CDN implementation but curious if they have controls to exclude files. Do you know?

**Comment by toddjsaunders** [comment]
Hi Jason -- that code is working, thanks very much.

97eighty, the only setting I see related to CDN in the GoDaddy admin area is a simple on/off toggle, I see no options to exclude files, and a search of their FAQ came up empty.

Thank you,

Todd

**Comment by toddjsaunders** [comment]
Hi again,

Was there any updating of TSML overnight?  Our search broke again, and we're still using the code Josh supplied.

Thanks!

Todd

**Comment by joshreisner** [comment]
ah, yes there was. i think the best solution would be to turn off the website caching so you could go back to the regular `[tsml_ui]` shortcode, but barring that, the next step would be to briefly go back to the `[tsml_ui]` shortcode so we can see what it's outputting and then we can update the replacement code accordingly

**Comment by toddjsaunders** [comment]
Hi Josh,

I turned off the caching, and all is good again.

Thanks!

Todd

**Comment by joshreisner** [comment]
great! i think for now our solution is "don't use GoDaddy website caching"

if this becomes an especially bad problem, or if there is some case where the caching is really necessary, then we can reopen and consider adding an option to the settings screen so that TSML UI always uses the dynamic `admin-ajax.php` route, which should not be affected by caching
