### ISSUE TITLE
CVS File vs Main App field mismatch

### ISSUE THREAD

**Issue by ebart455987** [code4recovery/12-step-meeting-list#76]
The CSV  download file has several fields which do not match the fields in the main app. 
I asked WP Support and they sent me here to submit this issue.  https://wordpress.org/support/topic/csv-file-mismatche-with-webpage/#post-12580729

The reason the CSV file is important to us: we can use it as a repository for all our Group/Meeting Info. We can then import into printable templates; keep track of group numbers; keep track of which group is in which district, etc. We don’t have that ability today, it’s currently a kludge of incomplete / scattered data.

I’m not a developer nor an I.T. person, so I truly appreciate all the kind and patient support those of you have provided to Central Offices and volunteer web servants.

Thanks for all you do.
Eric B

**Comment by tech2serve** [comment]
Which fields are missing other  than the mailing address?

**Comment by ebart455987** [comment]
This is what I found: 







Have a great day!
Eric Bartoletti

**Comment by CCFAAWebmaster** [comment]
I may have found 2 additional fields that do not import = Conference URL AND Conference Phone
These fields tie into recent Version 3.6.2 additional of Type = Online Meeting.

This becomes important as we want to import ~500 Online Meetings into our instance.

From this = https://docs.google.com/spreadsheets/d/18Cq4GLp90B9hDOnZCyorBAmEeGpFPeAxQ2W0upzgKGA/edit?usp=sharing

To this  
https://aasacramento.org/meetings/?tsml-day=5
https://aasacramento.org/meetings/rio-linda-fellowship-virtual-3/?tsml-day=5

If we can match up those fields we can format into .csv and pop em right in.

Thanks so much for all of the extra code efforts. It's an honor to be in service with you all.

- Pete B

**Comment by tech2serve** [comment]
Hi Pete--

Please see #88. We're focusing on that, which may also correct some of the CSV import field mismatches.

**Comment by joshreisner** [comment]
Hi @ebart455987 not sure where you're seeing Mailing Address but that's not a field in TSML. We have Address aka `formatted_address`

**Comment by joshreisner** [comment]
Wow I am wrong, I don't remember adding that field, that's probably why it was overlooked!

**Comment by ebart455987** [comment]
<img width="937" alt="Screen Shot 2020-03-30 at 9 54 29 PM" src="https://user-images.githubusercontent.com/55007577/77978878-21dbb680-72d1-11ea-8ab4-5a96685a3d90.png">
Click on "Part of a Group" radio button, the the Mailing address appears.  When I download the CSV file that field is missing.
