### ISSUE TITLE
Duplicate Meetings at same location

### ISSUE THREAD

**Issue by miketcurley** [code4recovery/12-step-meeting-list#77]
When I Add New a meeting that meets daily I have two options::
1) Manually add a meeting for each day and enter the same data in each field
2) Add one meeting, export the csv, edit (copy, paste) in Excel , then import the csv back.

I would prefer being able to add multiple days through the plug in's UI. For example when I select Day, I would like to be able to select more than one day.

Perhaps the solution would be to make the Day field similar to the Types field in that it can have multiple values.

**Comment by joshreisner** [comment]
I see how this could save time, but think the tradeoff is that this leads to notes fields that explain format changes (Mondays are Speaker, Tuesdays are Big Book) which makes the types less meaningful overall and degrades the user experience.

In my experience, meetings that meet at a regular time are not identical.

**Comment by miketcurley** [comment]
That's true. In those cases, each meeting is unique and should be treated separately.
Early morning "Daily Reflections" type meetings tend to be identical.
The requests we are getting for early morning zoom meetings are all identical so far.

**Comment by bejhanj** [comment]
@joshreisner makes a good point. However, I don't think it's justification to not go ahead with this feature. Rather it's a consideration for the person configuring the meetings. If the meeting format differs, this feature need not be used and they can be created as separate meetings, just as they are now. But if the meeting format does not differ, this feature would reduce so much work. I am in the same boat as @miketcurley, with several meetings in my area that meet multiple times a week with the exact same format. Every time there is a change, I have to update multiple (up to 7) meetings individually.

**Comment by scottvanwa2** [comment]
I would like to place my vote for a multi meeting/single entry option. Most of our multi day/single location meetings here are the same format each day. In addtion if the meeting moves locations and one entry is forgotten to be updated the address will be inconsistant. Third Normal Form dictates each record should only have to be updated once. I think a Mon, Tue, Wed... series of checkboxes on a single meeting entry would be a good solution

**Comment by jcookson-infoblox** [comment]
Is thee are report within the app itself that I can pull which tells me if a meeting was imported VS one that was not ... i want to get this listing so that I can reconcile the listing and remove duplicates?  If not, feature request?

**Comment by tim-rohrer** [comment]
> Is thee are report within the app itself that I can pull which tells me if a meeting was imported VS one that was not ... i want to get this listing so that I can reconcile the listing and remove duplicates? If not, feature request?

There is not, nor have I heard anyone talk about a workflow like what you're describing.

The easiest way to address what you're trying to do is to export the database to a csv, then use your spreadsheet (eg, Apple Numbers) to sort and filter and find duplicate that way. Then go into Wordpress and delete the duplicates.

**Comment by tech2serve** [comment]
> Is thee are report within the app itself that I can pull which tells me if a meeting was imported VS one that was not ... i want to get this listing so that I can reconcile the listing and remove duplicates? If not, feature request?

There is not, nor have I heard anyone talk about a workflow like what you're describing.

The easiest way to address what you're trying to do is to export the database to a csv, then use your spreadsheet (eg, Apple Numbers) to sort and filter and find duplicate that way. Then go into Wordpress and delete the duplicates.

**Comment by brianw-area24** [comment]
When you edit a meeting in WordPress, if it came into your site because of a feed, it will have a note at the top of the screen that says "This meeting was imported from an external data source. Any changes you make here will be overwritten when you refresh the data." 

If you have duplicate meetings, delete the one that doesn't have this note at the top.l If they both have it, then it's likely the meeting is in 2 separate feeds that you're importing.

**Comment by 97eighty** [comment]
Could support a need for recurrence/exceptions in the spec.
https://github.com/code4recovery/spec/issues/34

**Comment by joshreisner** [comment]
You can already use the spec to make `day` and array, eg `day: [1, 3],`

**Comment by joshreisner** [comment]
i think that we should close this issue as a `wontfix`. here one reason why i think it's a good practice, when a meeting meets on a recurring weekly basis, to keep them as separate listings:

i manage the listings in my area and notice that virtually every recurring meeting has difference in the meeting types between day. (for example monday is big book, tuesday is discussion, friday is birthday.) if we were to implement recurrence then this information would go into the meeting notes. now say someone is looking for a birthday meeting, either all the days are marked birthday, or none of them are. either option is not as good as separate listings would be.

**Comment by 97eighty** [comment]
Perhaps a possible direction is to create a duplicate post plugin that replicate the meeting and location to a different day.

**Comment by jcookson-infoblox** [comment]
Interesting.  Its been my local experience that locations that have 4 - 6 meetings a day, 7 days a week have general format's for the meetings and then they leave it to the meetings individual chair / planners to decide the type, etc.  Just having the ability to generically add a daily meeting would save time.  We'd add the meeting in the most general way.  The app would generate 7 individual meeting entries and we could then edit them individually, if need.  We could add the reference "daily" to the slug, which would help identify things.

**Comment by tech2serve** [comment]
I have not personally experimented with this, but it seems adding multiple meetings at the same location and time, but on different days, is something that *could* be accomplished using carefully crafted csv file that is then imported for the first load. After that, each meeting should be edited individually any way.

Would this work? If so, would someone be willing to experiment with this and post procedures? Code for Recovery can then add those steps to documentation.
