### ISSUE TITLE
[Bug]: Support gone for displaying upcoming meetings widget on my theme 

### ISSUE THREAD

**Issue by Oclair** [code4recovery/12-step-meeting-list#796]
### Contact Details

feedback@aavienna.com

### Website With Issue

https://www.aavienna.com

### What happened?

Hi there,

We’re using the Optimizer Pro https://optimizerwp.com/ theme since 2016 and the upcoming meetings widget no longer displays on pages. It also appears that the theme does not support the shortcode feature. I disabled all plugins including Jetpack and can safely attest there is an incompatibility between the theme and the 12 step meetings plugin.

Note: I do administrate another 12 step website https://www.navienna.com where the theme and your plugin do not exhibit this incompatibility. (talk about doing the same thing and expecting it to work...)

Thank you for all the support, passion and service!
Kind Regards from Vienna,
Oclair

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Relevant log output/errors

```shell
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.aavienna.com%2F
```

**Comment by Oclair** [comment]
![image](https://user-images.githubusercontent.com/619643/166152968-a374a1bb-f12c-4c94-a6e4-9c8c88465f09.png)

**Comment by 97eighty** [comment]
@Oclair Sorry you're having problems with the site. At first glance there doesn't appear to be any obvious console errors that would prevent the widget from rendering and I don't believe it to be a caching problem as I was able to bypass Rocket Cache. The problem may be deeper.

Have you tried to put WordPress in debug mode to see if there are any PHP errors?

Try removing the Widgets from the sidebar and placing a single Text Widget with some random text in its place. This will at least indicate if there is another problem with Widgets.

I'll install the theme you use to see if I can troubleshoot this a bit more.

**Comment by Oclair** [comment]
My bad. I am really sorry, it appears that we did not have another meeting today, had three earlier.
![image](https://user-images.githubusercontent.com/619643/166154898-e893ff16-5525-4476-b4a6-15d7c0d0b8d1.png)

**Comment by Oclair** [comment]
I suppose having upcoming meetings list meetings within the next 24 hours or so would be a feature suggestion...

**Comment by Oclair** [comment]
gosh what a huge effort I went through today....
