### ISSUE TITLE
[Bug]: Rename columns not working on new UI

### ISSUE THREAD

**Issue by nmbgeek** [code4recovery/12-step-meeting-list#807]
### Contact Details

clintjohnson@nmbgeek.com

### Website With Issue

https://aamyrtlebeach.org

### What happened?

Enabled the new UI and wanted to simplify the column names (remove / in Location and Address columns. Added this to the functions.php with no luck:

```
$tsml_columns = array(
	'time' => 'Time',
	'name' => 'Name',
	'types' => 'Types',
	'location' => 'Location',
	'address' => 'Address',		
	'distance' => 'Distance',
	'region' => 'Region'
);
```

The JS hack below does work but because wp_footer still ends up above the TSML code I have to set a timeout to execute the script so that it doesn't happen before TSML is loaded.  I tried onload and a few other methods and this was the only way I could get it to work.  Of course this causes the column title to change after the user sees the original naming.

```
function tsml_rename_columns() {
  $page = get_page_by_path("meetings");
  if ($page) {
    ?>
        <script>
		setTimeout(function () {
			document.querySelector("th.location_group").innerHTML = "Location";
			document.querySelector("th.address").innerHTML = "Address";
		}, 1000);
        </script>
    <?php
  }
}
add_action('wp_footer', 'tsml_rename_columns');
```

Thank you all for your great work.

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Relevant log output/errors

```shell
I really just want to rename the columns so that they do not have slashes.
```

**Comment by joshreisner** [comment]
hi @nmbgeek coincidentally we were just talking about something similar internally, which is the underlying reason that`$tsml_columns` and the new interface are not currently in sync.

for the time being, the following hack should work a little better, you won't see the flicker in the column heading

```
<script>
  var tsml_react_config = {
    strings: {
      en: {
        location_group: 'Location',
        address: 'Address',
      },
    },
  };
</script>
```

**Comment by joshreisner** [comment]
hi @nmbgeek thanks again for the report, a fix should be coming in the next release
