### ISSUE TITLE
[Bug]: Sync/Import - Regions hierarchy not working

### ISSUE THREAD

**Issue by julien-paris** [code4recovery/12-step-meeting-list#809]
### Contact Details

ecomm.cer@aamail.org

### Website With Issue

https://alcoholics-anonymous.eu/meetings/

### What happened?

Bug report submitted by CER (Julien) and Berlin (Soren) following extensive testing

As an admin, I am setting up data sources to be pulled into the CER (Continental European Region) website;
I set a parent region;
**Expected behavior**
copies of the source regions should be created or re-used under the selected parent region, regardless of whether they previously exist outside of the parent region or not.

**What happened**

2 issues arise: 

1.a. when I select a parent region wihch **does not** exist in the source website, the regions of the source website become a top-level region in the CER website
1.b. when I select a parent region whch **does** exist in the source website, the regions of the source website become a top-level region in the CER website

2. in both scenarios above, the regions are marked with 0 meetings associated. And in meeting list, the meetings are not associated with the correct region. they are "regionless", until i manually re-save them, in which case they then are associated with their region. 

**Context** 
This has been tested both with "Change detection" on and off. 
The bug also happens with other data sources. 
We have tested both with the region existing and not yet existing
We tested with Berlin as a parent region.
We also tested with Germany as a parent region - which does not exist on the Berlin website.
Both sides using the latest TSML version 3.14.3
The data source: https://www.alcoholics-anonymous-berlin.de/wp-admin/admin-ajax.php?action=meetings&key=39eca0e9954989d7080c24284097fd05

Please don't hesitate to request a zoom/TeamViewer session  in order to dig in. 

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output/errors

```shell
Example meeting: 
Geocoded:  
Object
approximate: "no"
city: "Berlin"
formatted_address: "Jungstraße 26, 10247 Berlin, Germany"
latitude: 52.5113636
longitude: 13.4659246
status: "cache"
[[Prototype]]: Object
```

**Comment by kiyote33** [comment]
Hi Julien, your bug report looks like it's a bit complicated. As I dive into this I would like to make sure I understand the configuration of your website where the reported issues are occurring.  If I remember correctly, you are using the Hello theme with Elementor. Is all your data imported using our Data Source import utility? Are there multiple data sources in addition to the berlin data source you provided?
If I understand correctly, the region hierarchy no longer works as it did before. You've outlined two different scenarios and neither produce the expected results. I've imported the Berlin data source into my sandbox and the region dropdown looks like this:
![image](https://user-images.githubusercontent.com/57125427/169571402-1e686d91-c5ad-4732-acd0-0013f41de1d4.png)
Is this the same as you are seeing?

**Comment by kiyote33** [comment]
Good day again Julien,
Looking at this today, I think there are two features involved here which are not really directly related.

1. **Region hierarchy** which is completely managed through the Admin menu Region link.
2. **Import Data Source** which uses the term "Parent Region" to identify data source records associated with a feed from one particular  URL, so we know which records to perform maintenance operations against. I prefer to add a unique region to the available region listing which is not normally used in the region hierarchy. Something like Germany Intergroup Committee to identify the Parent Region associated with the data source URL for the Germany records. This parent region should always have 0 records associated with it as it is not part of the hierarchical scheme and should not show up in the normal Region dropdown. 

I'm rethinking  the use of the term "Parent Region" and the use of the region dropdown here. "Parent Source" would be less confusing to end users. The use of a simple textbox accepting any term you want to call the "Parent Source" would also be less confusing. 
Hope this helps clear up the issue for you.

**Comment by julien-paris** [comment]
Hi and thanks.

Regarding 2: all scenarios failed - regardless.

Are you available for a zoom by any chance? I think if i showed you it would work great. Alternatively, I can do a screencast.

Julien

**Comment by kiyote33** [comment]
Sure, let's do a zoom. We can use this link [ZOOM Direct Link](https://zoom.us/j/92694176842?pwd=WVBCdHMyOWlnZGxMTG9tVW5Yb0lGQT09)

**Comment by kiyote33** [comment]
I'm online now if you want to join me.

**Comment by joshreisner** [comment]
as per discussion just now with @kiyote33, parent region is not being set on imported records, we need to add some code above this line: https://github.com/code4recovery/12-step-meeting-list/blob/main/includes/ajax.php#L387

**Comment by kiyote33** [comment]
@julien-paris reports: 
**Latest synchs are good ... and code4recovery has successfully resolved this issue which is absolutely amazing.**

**Comment by joshreisner** [comment]
great work @kiyote33 🥇
