### ISSUE TITLE
[Bug]: TSML UI: distance unit is mi instead of km while kilometers is set in the settings tab

### ISSUE THREAD

**Issue by Piteurrr** [code4recovery/12-step-meeting-list#810]
### Contact Details

adj-webmestre@aa89.org
### Website With Issue

https://aa89.org/wordpress/reunions

### What happened?

the distance displayed in search result should be in km as it is set to kilometers unit in settings General section.
Here in Québec (Canada), mi is not a valid distance unit...
it is only recognized by older people as we use kilometers SI unit since 1970's  ;-)

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Firefox

**Comment by joshreisner** [comment]
thanks @Piteurrr for the report. the bug has been fixed in `main` branch and the issue has been closed, it will make its way to you as part of the next release

**Comment by Piteurrr** [comment]
> thanks @Piteurrr for the report. the bug has been fixed in `main` branch and the issue has been closed, it will make its way to you as part of the next release

Merci beaucoup Josh !
;-)
