### ISSUE TITLE
Saved a Zoom meeting URL to one meeting, then updated another (same location) but most recent URL post wins

### ISSUE THREAD

**Issue by degrees57** [code4recovery/12-step-meeting-list#82]
**Describe the bug**
I updated Meeting A and entered a URL for the Video Conference Details.
I then updated Meeting B and entered a different URL for the Video Conference Details.
Both meetings are in the same location.
Checking Meeting A, I see that it now has the Zoom meeting link (URL) for Meeting B

**To Reproduce**
1. Log in to the WordPress Administration web page.
2. Click on 'Meetings'
3. Locate the meeting you want to edit; begin editing.
4. Scroll down to 'Contact Information'; the bottom two fields under 'Video Conference Details' are URL and Phone.
5. Put the information for a Zoom meeting into the URL field.  For example, https://zoom.us/j/760741434
6. Click the Update button to save the changes (it is in the opposite sidebar, up near the top).
7. Start to repeat the process from step 2 - click on 'Meetings' in the WordPress Administration sidebar.
8. Locate another meeting.  Note that this problem may depend on the other meeting being at the same Location or as a part of the same Group.
9. Begin editing the other meeting.
10. Repeat step 4.
11. Put in the information for a different Zoom meeting into the URL field.  For example, https://zoom.us/j/664622100
12. Click the Update button to save the changes.
13. Click on 'Meetings'
14. Locate the first meeting you edited.
15. Examine the field near the bottom under 'Video Conference Details': URL

**Expected behavior**
The first meeting URL field should show https://zoom.us/j/760741434

**Unexpected behavior**
The first meeting URL near the bottom shows https://zoom.us/j/664622100

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OpenSuSE Tumbleweed
 - Browser Firefox
 - Version 72.0

**Additional context**
I do have installed the Plugin "AA Berlin Addons" - although I think they affect rendered HTML output and not input.

I noticed that the URL and Phone were pre-populated for the second meeting.  That second meeting is at the same Location and is a member of the same Group.  I have updated a third meeting and a fourth meeting that are at different Locations and not a member of any Group, and the URL and Phone fields were not pre-populated.  I do still have data in the Notes field, with UPDATE: in there as the trigger to invoke the AA Berlin Addons plugin.  Neither the third nor the fourth meeting show the unexpected behavior.

**Comment by joshreisner** [comment]
I'm assuming both meetings also share the same group?

**Comment by degrees57** [comment]
You are correct.

**Comment by degrees57** [comment]
It is definitely some sort of carry-over from Group membership.  I updated a meeting that was a member of a group, for which no other meetings in that group have online presence.  The initial entry had empty fields.  I went and looked at another meeting for the same group, and the URL and phone numbers were pre-populated.

**Comment by joshreisner** [comment]
Yep! This is how groups work. My expectation was that groups would want to share conference info, that's how my local groups work. But I see it's not universal. I'll be switching the conference info to be per-meeting tomorrow.
