### ISSUE TITLE
[Feature Request]: Expand tsml_feedback_url to include additional template variables

### ISSUE THREAD

**Issue by 97eighty** [code4recovery/12-step-meeting-list#849]
### Requested Feature/Enhancment

Our existing template variables include {{slug}} and {{id}} only. This PR proposes adding additional variables {{title}}, {{dow}}, {{start}}. 

Or consider supporting any meta field?

'tsml_meeting' => '"day", "time", "end_time", "types", "group_id", "website", "website_2", "email", "phone", "mailing_address", "venmo", "square", "paypal", "last_contact", "attendance_option", "conference_url", "conference_url_notes", "conference_phone", "conference_phone_notes", "data_source"' . (current_user_can('edit_posts') ? ', "contact_1_name", "contact_1_email", "contact_1_phone", "contact_2_name", "contact_2_email", "contact_2_phone", "contact_3_name", "contact_3_email", "contact_3_phone"' : ''),

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by joshreisner** [comment]
so a fully loaded URL would look more-or-less like:

```
$tsml_feedback_url = "/feedback?slug={{slug}}&id={{id}}&name={{name}}&day={{day}}&time={{time}}&end_time={{end_time}}&types={{types}}&notes={{notes}}&conference_url={{conference_url}}&conference_url_notes={{conference_url_notes}}&conference_phone={{conference_phone}}&conference_phone_notes={{conference_phone_notes}}&location={{location}}&formatted_address={{formatted_address}}&region={{region}}&location_notes={{location_notes}}&group={{group}}&group_notes={{group_notes}}&district={{district}}&website={{website}}&email={{email}}&phone={{phone}}&venmo={{venmo}}&square={{square}}&paypal={{paypal}}";
```

this isn't so bad. i think if we include this example (or similar) in the readme this is pretty easy to implement. i was briefly considering suggested appending all the fields automatically but i think there will always be someone who needs to make adjustments

feel like some of the other fields like individual contacts and `last_contact` are more for internal office use and probably aren't needed
