### ISSUE TITLE
URL Validation for GoTo.com (was GoToMeeting)

### ISSUE THREAD

**Issue by tech2serve** [code4recovery/12-step-meeting-list#852]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/850

<div type='discussions-op-text'>

<sup>Originally posted by **degrees57** July  2, 2022</sup>
(I saw that someone posted this in the old WordPress support forum for the 12 Step Meeting List plugin, and thought that I could just re-direct them here -or- I could go ahead and bring it up here and _then_ redirect them here.  I chose the latter.)

narundi wrote:

History: On 02-Feb-2022 “GoToMeeting.com” company rebranded as “GoTo.com”
TSML Version 3.14.4: Provides two URL Aliases ('gotomeet.me', &amp; 'gotomeeting.com').
Recent: GoTo stopped redirection of legacy GoToMeeting.com URL's to GoTo.com
Effect: GoTo.com meeting URL's do not validate &amp; old-style meeting links (e.g. GoToMeeting.com/...) do not redirect.
TSML Users See: Only a Phone-in meeting (i.e. the A/V URL has been suppressed)
Work-around: In file "variables.php", within "$tsml_conference_providers", add “'goto.com' =&gt; 'GoToMeeting',” (without dbl-quotes) to list of valid URL's.
Caution: This manual source code edit will be overwritten by Plugin Re-install or Update.
Request: Please add GoTo.com validation mapping in next Version.
Thanks.</div>

**Comment by joshreisner** [comment]
this change has been merged and will be handled in the next release ✅
