### ISSUE TITLE
Regions Dropped When Using Block-based Theme

### ISSUE THREAD

**Issue by kiyote33** [code4recovery/12-step-meeting-list#886]
### Discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/885

<div type='discussions-op-text'>

<sup>Originally posted by **COMPUMEC** July 25, 2022</sup>
Hello, Please help.
This is an ongoing problem I have been trying to resolve.
I have a problem importing meetings. 
The import process is dropping Regions and I don’t know why.
I used the Region column to organize meetings by town.
The exported meeting list shows missing Regions as well.
Attached is my clean meeting list.
I have a video showing the problem.

https://www.dropbox.com/s/jetsfgfywkmyyd9/Dashboard%20%E2%80%B9%20Central%20Service%20Office%20%E2%80%94%20WordPress%20%E2%80%94%20Mozilla%20Firefox%202022-07-25%2018-33-36.mp4?dl=0

[meetings.csv](https://github.com/code4recovery/12-step-meeting-list/files/9185284/meetings.csv)

</div>

**Comment by kiyote33** [comment]
The CSV Import of @COMPUMEC's meetings.csv loads all regions correctly when using a classic theme. The issue arises when using a block-based theme like Twenty Twenty-Two, where 3 regions are mysteriously dropped during the import.

**Comment by douggreen** [comment]
I can't reproduce the problem on twenty twenty-two. I'm on Wordpress 6.0.2 and the current version of TSML (3.14.6). I tried all three options for "delete all meetings, locations, groups, districts, and regions". Every time I ended up with 175 regions.

Can @COMPUMEC try again? Are there any errors in the console log? Are you on twenty twenty-two OOTB or with customizations? Are you on WP 6.02? TSML 3.14.6?

**Comment by kiyote33** [comment]
I can confirm @douggreen's report. Identical import results of @compumec's clean CSV for both classical and block themes: 
![image](https://user-images.githubusercontent.com/57125427/189675949-08594563-6156-4234-b669-807e2c2ea0f5.png). Only sites located on network solutions seem to be able to recreate the issue.

**Comment by kiyote33** [comment]
Unable to reproduce with the latest 3.14.6 code.

**Comment by douggreen** [comment]
It's sounding like a potential PHP or Browser version problem? I'll try with other PHP versions locally. But it would help if the original reporter could report what they are using (both for PHP and for the Browser).
