### ISSUE TITLE
Ability to set meeting type as "online" for unsupported conference type

### ISSUE THREAD

**Issue by breckeni** [code4recovery/12-step-meeting-list#91]
What I would like to do is, for unsupported conference types, leave the link & dial-in number blank but still be able to tick the “online meeting” box and save it. That way those meetings would show when searching for online meetings.

**Comment by joshreisner** [comment]
What's an example of an unsupported conference type?

**Comment by breckeni** [comment]
Our district uses Callbridge.com for 7 online meetings which is unsupported and uncommon.  Our other meetings are on Zoom.

**Comment by joshreisner** [comment]
Can you add a line of code to your theme? Try
```
$tsml_conference_providers['callbridge.com'] = 'Callbridge';
```
That will add it for you as an authorized provider.

**Comment by breckeni** [comment]
Thanks Josh.  I'm new at this so first I did a backup.  Can I use the Code Snippets plugin and add html short code and run snippet everywhere?

**Comment by breckeni** [comment]
Josh,
I just heard from our groups using Callbridge.com and they are now going to move all their meetings to Zoom.  Hope I didn't waste your time and perhaps this post can help someone else out there.
Thank you.

**Comment by joshreisner** [comment]
Oh no worries! To answer your previous question, I don't think that would work. I'd recommend someone try to add that to the current theme's functions.php file using FTP or a file manager. No need to back up the database first, but do be careful…
