### ISSUE TITLE
API Credential Usage > 28.5K

### ISSUE THREAD

**Issue by CCFAAWebmaster** [code4recovery/12-step-meeting-list#92]
More of an API question than a "feature",

Site = aasacramento.org
Plugin = 12 Step Meeting List Version 3.6.3
Google Maps API Key set = 6/7/2018

I have a note (to the effect that) Google Map (credential) Usage should not exceed 28.5K
Well golly gee willikers, we pushed thru that in March of 2020 to = 35,692

Makes sense as usage is way up PLUS, we may push more as with Type= Online Meeting, requires a physical address (we cannot spoof a physical address)

1) Do I care that we exceeded 28.5K?
2) If I do, in what manner do I insure all is well in Google API land?
3) Do we in Sac, CA. need to insure additional $'s to increase usage?
4) If yes to #2, 

Reference:

https://cloud.google.com/free/docs/gcp-free-tier#always-free-usage-limits
https://cloud.google.com/billing/docs/how-to/budgets

Thanks as always for the positive feedback and hard work.

**Comment by tech2serve** [comment]
It sounds like you've set up your own Google account and entered an API key? 
<img width="289" alt="image" src="https://user-images.githubusercontent.com/31904316/78176013-6e360c00-7421-11ea-9b1f-5f6f8c77b63b.png">

**Comment by CCFAAWebmaster** [comment]
Correct to our own API key
Best I can determine from billing is as follows:

Mar 1 – 31, 2020 | Maps API Dynamic Maps: 18767 Counts | $131.37
Mar 1 – 31, 2020 | Credit Maps Free Tier | −$131.37

Um er seems a wash.
Let me open up a ticket w/ Google Cloud Platform

Thanks

**Comment by CCFAAWebmaster** [comment]
Thanks as always for the team support.

**Comment by Nedescon** [comment]
I just put City and Stae im my online meetings-

![Location](https://user-images.githubusercontent.com/32148114/78261904-d7735900-74cd-11ea-800b-6f2976735bbf.PNG)
