### ISSUE TITLE
TSML Feature Request: Online Contributions Link

### ISSUE THREAD

**Issue by asteinberger** [code4recovery/12-step-meeting-list#93]
I would like to request a new feature for the TSML. I am requesting that we add a new field called `contributions_url` that's supported by the JSON input method as well as the back-end manual input field for a meeting that takes the user to whatever web page a given meeting is using to accept online contributions.  On the front-end this could be a button with a dollar sign on it or a basket symbol or whatever works. I know right now we have a `venmo` field, but at this point that field doesn’t make all too much sense anymore anyways because you need a dedicated physical phone with it’s own phone number in order for Venmo accounts to be created or logged into these days. Not a lot of meetings have the money to buy their own phones.  Anyways, please let me know if this is a feature that can be added and if there is priority for it to get done.  Thanks!

**Comment by tech2serve** [comment]
We've added a number of other online payment options, and will entertain others. I don't see use add any additional buttons on the front end. So, unless @asteinberger chimes it with some other related change suggestion, I'm going to close this as completed.
