### ISSUE TITLE
Ability to set time zone at the meeting (or location?) level

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/12-step-meeting-list#930]
### Requested Feature/Enhancment

Already requested a few times, for example https://github.com/code4recovery/12-step-meeting-list/issues/266. Also recently discussed in https://github.com/code4recovery/12-step-meeting-list/discussions/929

TSML UI will soon be adding the opt-in ability for sites to normalize a variety of meeting timezones into the user's timezone, but this would require those timezones being in JSON

Not having this is already a barrier for multi-zone sites such as CER to adopt TSML UI

[Meeting Guide spec](https://github.com/code4recovery/spec) already has `timezone` as a supported key. Format must be in IANA timezone format, eg `America/New_York` or `Africa/Cairo` here is a [complete list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).

There is a native wordpress function that could be helpful: https://developer.wordpress.org/reference/functions/wp_timezone_choice/

An ideal solution would set this value automatically based on the meeting location entered using an API such as the [Google Timezone API](https://developers.google.com/maps/documentation/timezone/overview), but that may be a challenge from a financial and administrative perspective.

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

**Comment by iHwy** [comment]
Possibly start by adding a Timezone field to the Location Meta Box. This default to the Wordpress timezone. When the API is available the field would default to returned value.

Or perhaps the timezone should be with the time values?

![Adding-Timezone-Field](https://user-images.githubusercontent.com/2140146/191080261-865c1fc8-157f-4134-ac60-2ac24910a425.jpg)

**Comment by 97eighty** [comment]
Possibly start by adding a Timezone field to the Location Meta Box. This default to the Wordpress timezone. When the API is available the field would default to returned value.

Or perhaps the timezone should be with the time values?

![Adding-Timezone-Field](https://user-images.githubusercontent.com/72317744/191080482-7d0d5d1e-c1e2-49d8-b401-1ba71204df21.jpg)

**Comment by joshreisner** [comment]
yeah that's a tough one, i see the logic both ways. i think website admins might expect it to be near the time but i think it really should be part of the location because all meetings at a given address should share a timezone

**Comment by jbearden41** [comment]
It's not clear from this discussion what changes got made here, or when, but based on the timeline (21 days ago), something must have gotten changed, about then, that introduced a new problem. The "12 Step Meeting List" plugin that we're using on out "test" Web site (http://test.cnia30.org/) suddenly started displaying the message "Configuration error: time zone is not set." and refusing to show any meeting information, even though the Web site DOES have the time zone set (correctly) to Pacific Time (UTC-8). As I say, I don't know if this is connected, but the timing, and the coincidence of the "time zone" factor, make me think that there is some connection. Please let me know if this is connected. Thanks.

**Comment by joshreisner** [comment]
@jbearden41 could you try switching to `America/Los_Angeles` for your timezone? this should be more accurate than UTC-8 because it will account for DST

**Comment by petermixt** [comment]
Is this dead?

**Comment by joshreisner** [comment]
we are looking for a developer to pick this up, if you know one 😉

**Comment by kiyote33** [comment]
I don't mind picking this up, as I'm still waiting for feedback on #1116. I lean towards keeping the time zone with Location as multiple meetings use the same location. Imagine the confusion if the different meetings at the same location had different time zones. Who's right? Maybe we could set the time zone in Location Info and do a read-only display in Meeting Info as a compromise...

**Comment by joshreisner** [comment]
thanks @kiyote33 - let's sync as a team so we can get aligned on the approach, but i agree probably keeping it with the location makes the most sense

it would be great to ask google for the correct address based on the time zone API, but i'm guessing there isn't a big appetite to add more google API requests. in lieu of that, probably it should default to the user's time zone, if they are using a proper `America/New_York` type timezone and not a GMT offset

if they don't have the time zone set or are using an offset, we should probably put an alert on the admin screens like we do when https is not enabled

one question though, what to do with existing meetings - i don't think we should assume that they are all in the WordPress timezone, although this is probably true in most cases

**Comment by gobborg** [comment]
@kiyote33 @joshreisner has this been picked up?

**Comment by kiyote33** [comment]
Not yet that I  know of. I was going to start it at one point, but chose to go a different direction. Anyone that's interested in picking it up is welcome.

**Comment by gobborg** [comment]
It looks like [spec](https://github.com/code4recovery/spec) is still not integrated but instead meetings are based on templates, such as [single-meetings.php](https://github.com/code4recovery/12-step-meeting-list/blob/cf3673cc7222bc7a86c55b47b7cf41487d39f5b4/templates/single-meetings.php) or [admin-meeting.php](https://github.com/code4recovery/12-step-meeting-list/blob/cf3673cc7222bc7a86c55b47b7cf41487d39f5b4/includes/admin_meeting.php).

Would it be preferable to address this change in the single-meeting.php file or elsewhere?

**Comment by joshreisner** [comment]
the first problem is that we are not storing the timezone inside TSML anywhere, yet. so this will need to be addressed initially on admin_meeting.php and save.php, and then we'll need to make sure it's saved in the JSON feed and displayed on single-meeting.php. we'll also need to update our importer to look for and store this value if present

there's a lot still to talk about and decide. if you're interested on working with us @gobborg you're welcome to join us https://code4recovery.org

**Comment by furick1** [comment]
I suggest storing all times in UTC in the DB and use the user's timezone from browser request to offset the meeting time to the user's timezone. In the react world i have used moment to do the offset easily.

**Comment by joshreisner** [comment]
yes TSML UI uses react and the newer iteration of moment (called luxon) and can do the second part of your suggestion - translate the meetings into the users time zone. so one we store the right info we'll unlock some cool features for sites like yours that have meetings in lots of time zones

we do need to capture the actual time zone in this case however because we can't convert a weekly time to utc for daylight savings reasons

**Comment by gobborg** [comment]
@joshreisner I sent an email asking to join the slackspace and attend the next Zoom, but I haven't heard back yet. Could you help me follow up on this?

**Comment by joshreisner** [comment]
thanks @gobborg for the excellent conversation about approachs in slack. 

having thought about it a bit i would like to try it first on the location with no change to the meetings box. the ethos of the plugin is minimalism / simplicity / reliability, and i think this is the approach that best encapsulates that

benefits of putting it on the location: prevents situations where meetings at the same location have different timezones, or some have it and some don't, and fewer changes needed for users

because we are using IANA time zones, the dropdown will appear geographic, with values like `America/New_York`, so i think it will look right going in that box

**Comment by DerekDen** [comment]
Great to see this issue is being worked on already.  We just had a new meeting start in the Azores (islands that are a part of Portugal) that has a different time zone from the rest of Portugal.

**Comment by furick1** [comment]
@joshreisner we launched the meeting list live on recovery dharma global yesterday April 1st. The feedback has been good but there has been some confusion over timezone for meetings as we converted all times to ET in the interim until this update comes thru.

**Comment by joshreisner** [comment]
yes i bet that is confusing. i think until TSML adds this support, the best option for sites who list meetings across multiple time zones is to use the "Legacy UI" and keep them in their native time zones, example: http://alcoholics-anonymous.eu/meetings/

**Comment by furick1** [comment]
we are using legacy but listing in local timezones caused more confusion per the team as many of the meetings are online and have attendees in multiple time zones. I prefer your approach but based on consensus, we are sticking with all ET but look forward to the new timezone support whenever it comes.

**Comment by furick1** [comment]
@joshreisner I wanted to check to see if there were any updates or a more solidified plan for the time zone change? Can you confirm approach and next steps?

Approach:
1. Agree that time zone will be set on location vs address field
2. Time zone select options will not be EST, MST, PST but rather city name based so day lights savings time applicability can be derived. Where is that city list coming from? Maybe somewhere like https://timezonedb.com/time-zones . Is that list pulled by plugin or statically set and updated in new releases? I'm assuming updated per release. I also thought about the majority of sites not having to worry about different time zones per location and having a global option to set all locations to one time zone in the main meetings settings in one drop down so if set it ignores lower level time zone selection per location.
3. As user interacts with meeting list the day/time will be adjusted based on offset from user's time zone provided by browser and the meeting source local time that was set.

Next Steps:
1. Gain consensus on approach
2. Modify plugin per approach. Who will handle the change? Are we waiting on someone to volunteer to submit a PR? I might be able to help with some of the code changes but didn't want to head off in a direction that won't get approved/merged for mainstream release.
3. Test
4. Release

Hope all is well.

Thank you,
Grant

**Comment by joshreisner** [comment]
hi @furick1 yes we do have two members currently working on it - have you been to one of our meetings? if not please feel free to join us, our next meeting is 10am PT / 1pm ET this saturday

yes the time zone will be set manually on the location which is unique by address, so when it is set, each meeting with that address will get the updated time zone

the time zone list is like the link you sent, eg `America/New_York`, and will come from WP's internals (there is a similar list on the General Settings screen, but we will not be provding timezone offsets as an option as they do)

for now the meetings will be rendered in the website's local timezone. a future update will allow sites instead render in the user's timezone if the TSML UI appearance is selected. (this will be an easy change, because TSML UI already supports this)

hope that helps! if you want to get involved in the dev we'd love to have you join us: https://code4recovery.org

**Comment by joshreisner** [comment]
released today in version `3.14.35` 🎉 

handled in https://github.com/code4recovery/12-step-meeting-list/pull/1422

**Comment by DerekDen** [comment]
Many thanks to everyone involved.  I have already modified our site to add timezones to each meeting.  All seems good.  We had one meeting in a different timezone.  Now it's showing correct data.  All the other meetings are good too.

https://aaunityportugal.org/aa-meetings/?meeting=azores-island-serenity

**Comment by petermixt** [comment]
Thank you all
.
Peter D Strruve
CMA GSO WebTechs

**Comment by furick1** [comment]
thank you all @joshreisner and team for this update. This change has been applied to RD Global at https://recoverydharma.org/meetings/ . We are using the TSML UI and have set the IANA time zone at the meeting level for all meetings so we could leave the time zone blank in the plugin settings. Given our users are all over the world along with meeting locations in combination with online, this change was important to support users needs automagically. 

I noticed when flipping to TSML UI that the meeting feedback reverts to an email vs the form flow you get with Legacy.  Is that going to stay a triggered email vs form submission or will the mtg feedback plugin be updated to support the full form flow with TSML UI?

Rock on Open Source!

**Comment by joshreisner** [comment]
@furick1 we're in the planning stages on a service to handle this for you that sites could opt into, but in the meantime if you want there is a way to send that to a URL of your choosing - you could potentially use a form-builder plugin to set up a feedback form. more info here: https://wordpress.org/plugins/12-step-meeting-list/#can%20i%20set%20a%20custom%20%22update%20meeting%20info%22%20button%20in%20tsml%20ui%3F
