### ISSUE TITLE
Temporary Closure does not gray address with Online Meeting

### ISSUE THREAD

**Issue by megaabite** [code4recovery/12-step-meeting-list#94]
**Describe the bug**
When both Temporary Closure and Online Meeting are checked the address is not grayed out.
Appears as if the meeting is still live AND online.

**Expected behavior**
Temporary Closure should control graying of address.

**Ideal situation**
To me, the best solution for both temporary closure AND online meeting would be 
- gray all of the text
- "/Temporary Closure, Online Meeting" next to the name

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version N/A

**Comment by tech2serve** [comment]
The styling described was intentional; the opacity was removed for online meetings in order to show the meeting was occurring. `Online Meeting` indicates the meeting is online, but the single meeting page will still show `Temporary Closure`.

If having those meetings grayed out is a better fit for your website, I suggest overriding the style with your own theme/styling.

The class to override:

```type-onl {
							opacity: 1 !important;

							.name {

								small {
									color: $color_online;
									font-weight: bold;
								}
							}
						}```

**Comment by megaabite** [comment]
> The styling described was intentional; the opacity was removed for online meetings in order to show the meeting was occurring. `Online Meeting` indicates the meeting is online, but the single meeting page will still show `Temporary Closure`.
> 
> If having those meetings grayed out is a better fit for your website, I suggest overriding the style with your own theme/styling.
> 
> The class to override is`type-onl`. Set the opacity to 0.5:

Thanks.  Understand the design decision.  Seems mis-leading. Guess people will know when they find the door locked.

I would follow your suggestion to fix out site but have absolutely no idea how to implement it.
Any tutorials anywhere?

**Comment by tech2serve** [comment]
> I would follow your suggestion to fix our site but have absolutely no idea how to implement it.
Any tutorials anywhere?

There are a number of options and guides available. If you're an AA member, some of these have been discussed in the TIAA Forums. Fire up your favorite search engine and you'll find a lot of information including child themes, or adding CSS through the Wordpress customization pages (depending on what theme you're using).

**Comment by megaabite** [comment]
> > I would follow your suggestion to fix our site but have absolutely no idea how to implement it.
> > Any tutorials anywhere?
> 
> There are a number of options and guides available. If you're an AA member, some of these have been discussed in the TIAA Forums. Fire up your favorite search engine and you'll find a lot of information including child themes, or adding CSS through the Wordpress customization pages (depending on what theme you're us

> > I would follow your suggestion to fix our site but have absolutely no idea how to implement it.
> > Any tutorials anywhere?
> 
> There are a number of options and guides available. If you're an AA member, some of these have been discussed in the TIAA Forums. Fire up your favorite search engine and you'll find a lot of information including child themes, or adding CSS through the Wordpress customization pages (depending on what theme you're using).

Thanks anyway.

**Comment by wokat** [comment]
Hej @megaabite,

Which is your site? I can help you cobble something together...

**Comment by megaabite** [comment]
cachevalley.org

Could also use some help fixing the DNS records so that all the pages use
the domain not the static IP...

**Comment by wokat** [comment]
I incorporated your suggestion in a collection of workarounds I'm maintaining for AA Berlin. It should be relatively safe to download a plugin zip from Github below and upload it under **"Plugins / Add New"**, **activate it**, and configure it under **"🥕 AA Berlin Addons"**:

https://github.com/aa-berlin/alcoholics-anonymous-berlin.de/releases

You _might_ want to remove the mail bits from your post :sweat_smile: (there's an unsubscribe link in it :joy:)

Uuuh let me look at your site for the DNS thing you are mentioning...

**Comment by megaabite** [comment]
Thank you!  That's really awesome.

Been doing embedded firmware and all manner of PC applications from Algol to Fortran to C# but this web stuff is all gibberish - tech2serve tried to help but made no sense.  Could eventually figure it out - launched WordPress virtual machine using free GCP account then created the website in about a week... - but it's a steep learning curve.

Feel free to point me in a direction and I will do my best to figure it out.

**Comment by wokat** [comment]
Hmm, hej @megaabite, I'm not finding a TSML installation at http://cachevalley.org/ but get redirected to cachefoodpantry.com.

I guess we can take this discussion off the issue chat. You can find my ECLO email at alcoholics-anonymous-berlin.de/contact (Sorry, a bit superstitious about copying it even more public places...)

Annnd going to bed now, running (barely) on CEST. 

Find this setting in the plugin described above: **Mute address in listing, if both ONL(-INE) and TC**

**Comment by megaabite** [comment]
Thanks.  Sent email to webmaster at ELCO...
