### ISSUE TITLE
Allow Online Only meeting with no address

### ISSUE THREAD

**Issue by megaabite** [code4recovery/12-step-meeting-list#95]
**Is your feature request related to a problem? Please describe.**
We have an Online Only meeting.  But the plug-in requires an address.  So we used our Intergroup PO Box.  Now it appears that the meeting occurs at the Post Office...

**Describe the solution you'd like**
Allow an online meeting to be listed without an address.  

This would also be useful for a professionals only meeting which requires an invitation. Some meetings require you to call a phone number in order to get the address.

**Comment by tech2serve** [comment]
Hi @megaabite, We're are aware of this idea and will re-evaluate in the future. For the time being, we consider the massive shift to online meetings to be temporary in nature. The `12-Step-Meeting-List` is designed to handle in-person meetings, and we expect we'll stick with that going forward. 

Other work is being evaluated for managing online meetings in the long term. Having online meetings shown in this plugin remains a temporary solution. If this changes, we'll publish an announcement.

Thank you for the input.
