### ISSUE TITLE
Allow online meeting type to be checked for NON direct meeting links

### ISSUE THREAD

**Issue by alex-m-dc** [code4recovery/12-step-meeting-list#98]
Hello,
With all the crap happening around zoom right now a lot of our groups are asking to take the direct link off of our site - they provide just a phone number to call in or an email address to ask for the link - or even a link to another site they control (and can change more rapidly) for the actual meeting links.

None of these options currently allow their meetings to show up in the online meeting list I've just moved all our meetings over to. Currently we have a two-tier system with zoom meetings in the plugin-meeting finder and a page with the odds and ends meetings separately... kind of a pain and really puts those other meetings at a disadvantage.

And/Or... maybe we can get a "phone meeting" type? almost all our older folks really like that option and the ability to one-click has been KEY for that and I really thank you!

--Alex M
alex.m@aa-dc.org

**Comment by tech2serve** [comment]
The online Conference Phone field can one used for regular phone meetings. It doesn't have to be tied to an online provider.

Did you see our request for feedback on a possible setting we could add to the plugin that would improve security? There are drawbacks of our possible approach. Anyway, the message is in both TIAA Forum and in the Wordpress Support forum.

**Comment by alex-m-dc** [comment]
Thanks for this - getting better all the time!! Take a look at my screenshot tho - even tho it accepts a phone number - it does not allow the "online meeting" type to be added. This leaves it off the list of online meetings we're pushing everyone towards.

I'd like the "online meeting" to be allowed even when there are NO details in the phone or website fields - people will see that they can go to the club or group's page in the notes. (i.e. https://laurelrecovery.org/zoom-meetings/) 

As far as plugin security - the filtering of the URL should be sufficient, right? I'll check the other forums for specifics on the app security issue.

![image](https://user-images.githubusercontent.com/62864449/78504788-368ad500-773d-11ea-837f-d13ad16dff13.png)

THANKS!!!!!

**Comment by tech2serve** [comment]
Hi Alex,

We're discussing a change that would allow for the Conference Phone and Online Meeting type to be used together.

If you don't want to wait for us to finalize the decision/implement any changes, you should be able to set `$tsml_conference_providers = array();` in your theme. This turns off validation for the conference providers.

**Comment by wokat** [comment]
Hi @alex-m-dc @tech2serve, 

I have a feature switch for just this case in my collection of workarounds at AA Berlin: https://github.com/aa-berlin/alcoholics-anonymous-berlin.de/releases

You can download the plugin zip there and install via upload and activate.

Then find all settings in Dashboard left menu "🥕 AA Berlin Addons".

**Comment by alex-m-dc** [comment]
WHAT!! That thing is essential! Thank you so much!! I'm going to look through your other options - any off the top you recommend?

Check out our site - https://aa-dc.org/ one thing you might want to add to this is a way to add some HTML right above the list of meetings like we did here: https://aa-dc.org/meetings?tsml-time=upcoming&tsml-type=ONL

The password thing threw us for a LOOP and the banner (simple banner) just wasn't cutting it since people just quickly scroll down to the list.

It was one of those things that I always wanted to do - and because I was afraid to break the plugin I spun up a whole other server (a nanode of course) to test ways of doing it. found it was really simple in the end but have to keep re-doing it with every update.

THANK YOU!!
